### ISSUE TITLE
Blinking cursor in Toolbar's subtitle and custom dialogs

### ISSUE THREAD

**Issue by enricocid** [enricocid/Music-Player-GO#104]
<img src="https://raw.githubusercontent.com/enricocid/Reveal-fragment-example/master/screen.gif"  height="500px" align="right"/>

**Toolbars subtitles** in fragments and **titles from custom dialogs** (material dialogs lib) in the upcoming release (4.0.0) are showing a sort of **blinking cursor for a few seconds** when they are shown.

The same issue is discussed [**here**](https://issuetracker.google.com/issues/146012760) as it is probably related to the development platform itself.

I also opened a [**repository**](https://github.com/enricocid/Reveal-fragment-example) on GitHub with a stripped version of MPGO 4.0.0 to let the google devs to **replicate** the issue and navigate the code for the better.

Still can't find a solution. I have tried to apply a different styling, to change focusability attributes and to make cursor not visible but the problem is still there.
For the Toolbar in the revealed fragment I've found that reducing the reveal animation time (1000 -> 500 ms) mitigates the issue, making the cursor not visible.

Cursor on material dialogs titles is still there. Any help, once 4.0.0 will be released, will be highly appreciated

**Comment by bullheadandplato** [comment]
Downgrading preferences library to `1.1.0-alpha01` seems to solve the issue for now. I tried to find the real cause by examining the commits [alpha01 to alpha04 commits](https://android.googlesource.com/platform/frameworks/support/+log/eb8080404ca0086bdb1ad89235f849e25e6a6997..968f440307eb94a35ed10a2d281749b2312b6e40/preference)  but failed to find anything that could work. [Here](https://github.com/bullheadandplato/Music-Player-GO/commit/00a807542e6d91b2451975372aa04ee084d6a374) are my changes

**Comment by enricocid** [comment]
Weird, gonna try asap. Thanks for reporting 😁

**Comment by bullheadandplato** [comment]
[Problem](https://android.googlesource.com/platform/frameworks/support/+/2e053b737b878d743b2a62f73ea43236fdd60f79%5E%21/#F0) was in this commit. `PreferenceFragmentCompat` tries to apply default theme to activity if `R.attr.preferenceTheme` is not present in activity theme. So adding `<item name="preferenceTheme">@style/DialogsStyle</item>` fixed the issue. I will do PR now

**Comment by enricocid** [comment]
closing then. Thanks :)

**Comment by imknown** [comment]
I think downgrading or removing all scrollbars are not good ideas.
They will cause the scollbar of PreferenceFragmentCompat not working.

So just remove the scrollbar of subtitle:

``` kotlin
private fun initSubtitle() {
    setSupportActionBar(toolbar)
    supportActionBar?.subtitle = MyApplication.getMyString(R.string.lld_json_loading)

    val subtitleTextView = Toolbar::class.java
        .getDeclaredField("mSubtitleTextView")
        .also { it.isAccessible = true }
        .get(toolbar) as TextView
    subtitleTextView.isVerticalScrollBarEnabled = false
}
```
