### ISSUE TITLE
Blank activity on Galaxy S7 edge (reported by an user via email)

### ISSUE THREAD

**Issue by enricocid** [enricocid/Music-Player-GO#105]
<img align="right" src="https://user-images.githubusercontent.com/7274841/71686378-5061f800-2d9b-11ea-9251-450b19c8d0ef.jpg" height="500px"/>

- **Affected devices**: Galaxy S7 edge
- **Build info**: hero2ltexx-user 8.0.0 R16NW G935FXXS6ESI4 release-keys
- [**bugreport-2020-01-01-10-58-11.zip**](https://github.com/enricocid/Music-Player-GO/files/4017030/bugreport-2020-01-01-10-58-11.zip)

Opening the app after it was removed from recents results in a blank ViewPager. The issue is not reproducible on my devices (Mi A2 lite, Mi A1, Nexus 5 e Redmi 3) and no other users have reported this issue.

How to reproduce:

1. Open the app, play some music
2. Remove MPGO from recents
3. Open it back to get blank activity
4. Reopening app from multitasking fixes the issue

**Comment by GuinnessX** [comment]
I have the same problem on my S8, but it is persistent...  Maybe I don't know what "reopening the app from multitasking" means, but there is no way to open the app on my device that works.  The most recent update has not changed my situation.  I cannot do anything but play the last song I was playing three versions ago.

**Comment by enricocid** [comment]
Could You try this?

https://drive.google.com/open?id=1g-uMohsvPYdfegzCPCl8i6eT__H8ZDjU

and send me a bug report (enable developer options -> open bug report -> interactive -> reproduce the issue while recording the bug report). Thanks

**Comment by GuinnessX** [comment]
> 
> 
> Could You try this?
> 
> https://drive.google.com/open?id=1g-uMohsvPYdfegzCPCl8i6eT__H8ZDjU
> 
> and send me a bug report (enable developer options -> open bug report -> interactive -> reproduce the issue while recording the bug report). Thanks

I installed this version, but I am not able to access anything but the play button.  I can't access developer options...

**Comment by enricocid** [comment]
Try this:
https://drive.google.com/open?id=1rCuioDAjrfhqlJlHKzeAImmi0kWFjCXX

To enable dev options 
https://www.samsung.com/uk/support/mobile-devices/how-do-i-turn-on-the-developer-options-menu-on-my-samsung-galaxy-device/

To generate a bug report You can follow this
https://developer.android.com/studio/debug/bug-report

Once finished share the bug report with me sending a email

Unfortunately without a bug report there's not much I can do

**Comment by enricocid** [comment]
In this apk I've reworked music loading mechanism, let me know if it works or not and if possible post a logcat :)

https://drive.google.com/open?id=1sDE7pHprsPjNApfmn34Q57PTULMJcFh4

**Comment by GuinnessX** [comment]
My device is completely locked down by my employer.  I am able to get to developer options, but do not have access to ADB, or to the "Take bug report" option.  Both are grayed out.  Hopefully another Samsung user will respond and have full access to the tools required to log this bug...  That said, I went back to version 3.6.9.2 and it works perfect;y.  I'm sure you changed a lot for v4, but maybe you can think of some change that might cause this problem on Galaxy S devices...?

**Comment by enricocid** [comment]
Seems like LiveData is causing the issue. Sometimes this happens also on my Xiaomi, while on Samsung is frequent. I got rid of live data (keeping loading of music async). 
Let me know if this is working

https://drive.google.com/open?id=1lOXhh2oFwl8NOIfxx6UTGLxBIEbYdX42

**Comment by GuinnessX** [comment]
> https://drive.google.com/open?id=1_8iOCDjy5UV-OZw7xYYm1FC9GDu8_yJJ

I'm sorry it took me so long to respond.  Busy week at work...  This version is no different on my S8 than the others you have provided.  I guess LiveData is not the problem with Galaxy devices...?

**Comment by enricocid** [comment]
No problems. Gonna post apk later :)

**Comment by fwSmit** [comment]
I have the same white screen on my honor 10. It started from when I installed the app. There's nothing I can do to make it go away. I tried the apk you posted last, but I still have the same issue.

**Comment by GuinnessX** [comment]
> 
> 
> I have the same white screen on my honor 10. It started from when I installed the app. There's nothing I can do to make it go away. I tried the apk you posted last, but I still have the same issue.

Maybe you can follow his steps in the request above to provide a log from developer options...?  I don't have access on my phone.

**Comment by enricocid** [comment]
Yes, that would be help me a lot

**Comment by fwSmit** [comment]
I sent you a mail. Not sure if I did it the right way. Let me know if I did it the wrong way

**Comment by enricocid** [comment]
Gonna check it tomorrow (is very long).

I tried to change the UI setup here:

https://drive.google.com/open?id=1iBIihgjgMmkO3f_R36tU4euaLgGf7QcX

**Comment by fwSmit** [comment]
That version doesn't work either

**Comment by enricocid** [comment]
https://drive.google.com/open?id=14BWaUKkLjqVB1LGaD7ek8cIjDApTgIDL

I added some code for debug, if you can please send me bug report. Thanks :)

**Comment by fwSmit** [comment]
Done :)

**Comment by enricocid** [comment]
https://drive.google.com/open?id=1KmL276f_1E_GmisTn_NxnlAwPEFO_zvW

**Comment by fwSmit** [comment]
That's much better! I still have a small white bar at the top
![Screenshot_20200110_140747_com iven musicplayergo](https://user-images.githubusercontent.com/23078054/72155134-b578a780-33b2-11ea-8f0e-5f4924051410.jpg)

**Comment by fwSmit** [comment]
Switching theme fixes it, but it's back when you close and reopen the app

**Comment by enricocid** [comment]
woah, strange XD
What happens if You disable edge-to-edge?

**Comment by fwSmit** [comment]
That works even when you reopen

**Comment by GuinnessX** [comment]
Excellent!  This version works perfectly on my S8...  Thanks!

**Comment by fwSmit** [comment]
Does edge to edge work on other devices?

**Comment by enricocid** [comment]
> Does edge to edge work on other devices?

It works on my Mi A2 lite and Nexus 5, but they are running pure AOSP. Gonna try to use a support library to fix this problem

**Comment by GuinnessX** [comment]
> Does edge to edge work on other devices?

I'm not sure what that is, but my S8 has the "signature" curved edges to the screen, and the app displays all the way to ends of those curves.  There are options in the settings for edge panels (shortcuts) and edge lighting (for notifications), but those don't sound like what you are asking about...?  I don't like either one and have them both disabled.

**Comment by enricocid** [comment]
I reworked edge-to-edge impl using a support library. Wotks better now on my phones, please let me know :)

https://drive.google.com/open?id=1rpzBum63VZc0XyHEG1VZPYvPSjPvWpsK

**Comment by GuinnessX** [comment]
I just realized that I can only see a small portion of the alphabet on the right:
![Screenshot_20200110-154605_Music Player GO](https://user-images.githubusercontent.com/59567846/72185511-f37cc800-33c0-11ea-8137-34d8bc03b863.jpg)

**Comment by fwSmit** [comment]
You only get to see the letters of artists that are in your library. Do
some letters miss?

**Comment by GuinnessX** [comment]
Oops..  Haha, forgot which phone this was.  I guess I only loaded B-D bands on it, and the R-S listed are other items.  I use LMT Launcher for navigation, though, and it appears exactly where those few letter are, so I (personally) can't use them.  They do work if I disable LMT.

**Comment by fwSmit** [comment]
> I reworked edge-to-edge impl using a support library. Wotks better now on my phones, please let me know :)
> 
> https://drive.google.com/open?id=1gQ9jTEx8Rl8KAfQGlOabpb35A_lLQPMT

All the white bars are gone now, but i think this patch introduced another bug. If you click on the name of the currently playing song, the app crashes.

**Comment by fwSmit** [comment]
> Oops.. Haha, forgot which phone this was. I guess I only loaded B-D bands on it, and the R-S listed are other items. I use LMT Launcher for navigation, though, and it appears exactly where those few letter are, so I (personally) can't use them. They do work if I disable LMT.

I think it would be better to just include all the letters, even those that are missing from you library and then just going to the closest one in your list.

**Comment by fwSmit** [comment]
It may be just me but it seems like this version takes longer to start

**Comment by enricocid** [comment]
> > I reworked edge-to-edge impl using a support library. Wotks better now on my phones, please let me know :)
> > https://drive.google.com/open?id=1gQ9jTEx8Rl8KAfQGlOabpb35A_lLQPMT
> 
> All the white bars are gone now, but i think this patch introduced another bug. If you click on the name of the currently playing song, the app crashes.

Could you please send me bug report? Thanks

**Comment by enricocid** [comment]
> It may be just me but it seems like this version takes longer to start

Debug APK is usually slower than release :)

**Comment by fwSmit** [comment]
Do I need to let the app crash while it's making a bug report?

**Comment by enricocid** [comment]
> > Oops.. Haha, forgot which phone this was. I guess I only loaded B-D bands on it, and the R-S listed are other items. I use LMT Launcher for navigation, though, and it appears exactly where those few letter are, so I (personally) can't use them. They do work if I disable LMT.
> 
> I think it would be better to just include all the letters, even those that are missing from you library and then just going to the closest one in your list.

I'm using Reddit's Indicator. I have no control on how the alphabet is generated. I can only reduce its size (for example in land layout the alphabet is halved to fit the screen).

https://github.com/reddit/IndicatorFastScroll

Also, I'm not sure, but I don't think it is a good design practice/choice @DSteve595 (?) to have the whole alphabet on a fast scroller.

**Comment by enricocid** [comment]
> Do I need to let the app crash while it's making a bug report?

Yeah , make it crash :)

**Comment by DSteve595** [comment]
>I don't think it is a good design practice/choice @DSteve595 (?) to have the whole alphabet on a fast scroller

I don't have any hard data or suggestions for 'whole alphabet' vs 'only present items'. I personally prefer only showing the present items. I feel that if the list is small enough that many letters are missing, it's probably small enough to scroll through with your finger. Looking at @GuinnessX's screenshot, though, I suppose it's possible. It seems like kind of an edge case to me (a dozen bands starting with `B`, but none starting with `A`).
Unfortunately since that fast scroller lib is populated by the actual items, I can't think of an easy way to show the whole alphabet.

**Comment by fwSmit** [comment]
Yeah it would not be worth the effort now. But to give you an example, my
built in music app called 'Music' has all letters included.
I also tried to check what my contacts app does, but I can't see because I
have contacts with all letters.

**Comment by enricocid** [comment]
> > I reworked edge-to-edge impl using a support library. Wotks better now on my phones, please let me know :)
> > https://drive.google.com/open?id=1gQ9jTEx8Rl8KAfQGlOabpb35A_lLQPMT
> 
> All the white bars are gone now, but i think this patch introduced another bug. If you click on the name of the currently playing song, the app crashes.

Could You try this?

https://drive.google.com/open?id=14lC4IIa_aHuI1aJqIGVnF-1bQHj0hVlL

The problem is due to the fact that I reviewed [Music](https://github.com/enricocid/Music-Player-GO/blob/master/project/app/src/main/java/com/iven/musicplayergo/music/Music.kt) object's fields to remove full path reference and add id to retrieve content uri for playing.

I did this to be compliant with changes introduced on Android Q and indications to not store full path of files. 

So the problem is caused by the saved song preference that is missing the new fields (display name and id).
Unfortunately had to change preferences keys to avoid issues with the next update so preferred songs and last reproduced song will reset

**Comment by fwSmit** [comment]
It doesn't crash anymore, but isnt the progress bar supposed to show how loud the song is at a certain point. For me the progress bar is just straight. I'm not sure if this has to do with this issue. 
![Screenshot_20200111_131604_com iven musicplayergo](https://user-images.githubusercontent.com/23078054/72204137-f33e0480-3474-11ea-8c5a-95141b8f9007.jpg)

**Comment by enricocid** [comment]
I unfortunately had to remove waveform bar. The library itself needed full path of the music file to build the waveform. It is bad practice to keep reference of files full path for security reasons. Also, devices running Android 10 would crash if trying to access full path. So to make it fully compatible with Android 10 and ready for Android R without any gimmicks (for example opting out scoped storage) I removed it. 
I will add it back as soon as I will find another library/solution. :)

**Comment by fwSmit** [comment]
Allright I understand. I think you can close this issue now

**Comment by enricocid** [comment]
Could you please try this apk?

Wanna be sure this issue is fixed as I did some changes to music loading before release. Thanks

https://drive.google.com/open?id=1x79yAP3fcr1d6tMfhhXiy-13BGR8R3vK

**Comment by enricocid** [comment]
new debug apk link 

https://drive.google.com/open?id=12XI5YyJBWzYObp0d_lEJb_MMyiJ9JQ7_

**Comment by GuinnessX** [comment]
I'm not sure my input has been relevant the last few test builds, but they have all worked well and this one does too.  I haven't had any crashes, but also haven't used it extensively lately...  Are there any specific tests you would like me to try?

**Comment by enricocid** [comment]
> I'm not sure my input has been relevant the last few test builds, but they have all worked well and this one does too. I haven't had any crashes, but also haven't used it extensively lately... Are there any specific tests you would like me to try?

No no, don't worry. Just wanted to be sure it is working good after the latest changes👍

**Comment by fwSmit** [comment]
This one works as far as I can tell. You can go ahead and release that.

Op zo 12 jan. 2020 om 17:55 schreef enricocid <notifications@github.com>:

**Comment by enricocid** [comment]
Hello guys,

Could You please try this

https://drive.google.com/open?id=1YaYlk_MSkhwcTfLz_dSKtkLDsXUj_TOt

This is an attempt to make the loading mechanism smoother. I'd like to know if blank screen is a thing of the past, then I'll release :)

Thanks!

**Comment by fwSmit** [comment]
I still see a blank screen for a short while. After that a rotating circle. I don't think loading has become shorter.

**Comment by enricocid** [comment]
> I still see a blank screen for a short while. After that a rotating circle. I don't think loading has become shorter.

That's because it is a debug APK and the query that depends on the Mediastore database size. With smoother I meant to let the user know something is loading.

The important thing is that blank screen is not a thing anymore :)

**Comment by fwSmit** [comment]
Well I still see a blank screen, but after a short while the circle. It's
better than only blank screen.
But I'm curious how fast the release version loads. And how that compares
to other music apps

**Comment by GuinnessX** [comment]
> I still see a blank screen for a short while. After that a rotating circle. I don't think loading has become shorter.

Ditto.  Looks good to go!

**Comment by enricocid** [comment]
Hello guys.

I've found that there's a issue caused by the MediaStore query at boot. After many accesses the query returns different results producing crashes like this.
So I started adding a db to store music to reduce mediastore accesses.

Could please try this one and let me know if it works good?

This behaviour is not related to this issue, just need someone to test this apk:

https://drive.google.com/open?id=1uP87nBZ4T9O8nEHYIl1P8z0X1mmAdfAn

thanks :)

**Comment by GuinnessX** [comment]
It crashes before fully opening on my S8, but unfortunately I'm the one who can't take logs...

**Comment by enricocid** [comment]
Seems like samsung embraces apple's philosophy when it comes to cook their android versions ... think differently.

Anyway,
here is another apk where the process of db building has been simplified :)

[link](https://drive.google.com/open?id=17TALVLCygtEibt4fmYLJVAptHb-VNbc_)

**Comment by GuinnessX** [comment]
That one crashes too, but as far as I can get in troubleshooting is to uninstall/reinstall, which resets the permissions.  It crashes very soon after I grant file access (which I'm sure is easy to guess)...

**Comment by enricocid** [comment]
> That one crashes too, but as far as I can get in troubleshooting is to uninstall/reinstall, which resets the permissions. It crashes very soon after I grant file access (which I'm sure is easy to guess)...

The release works (4.1.9)? Probably it is related to the db...

**Comment by GuinnessX** [comment]
Yes, v4.1.9 works.

**Comment by enricocid** [comment]
> Yes, v4.1.9 works.

So this one too.

https://drive.google.com/open?id=1oJ5y11LhNUDSjL4EPW7VAjp_Tckv0smF

Really hope it is not related to the new material components theme ...

**Comment by GuinnessX** [comment]
> > Yes, v4.1.9 works.
> 
> So this one too.
> 
> https://drive.google.com/open?id=1oJ5y11LhNUDSjL4EPW7VAjp_Tckv0smF
> 
> Really hope it is not related to the new material components theme ...

This one crashes too, at exactly the same spot (as far as I can tell)...  As soon as I grant file access permission.

**Comment by enricocid** [comment]
> > > Yes, v4.1.9 works.
> > 
> > 
> > So this one too.
> > https://drive.google.com/open?id=1oJ5y11LhNUDSjL4EPW7VAjp_Tckv0smF
> > Really hope it is not related to the new material components theme ...
> 
> This one crashes too, at exactly the same spot (as far as I can tell)... As soon as I grant file access permission.

This one is with appcompat theme and the latest few improvements 

https://drive.google.com/open?id=1Y3skDhFFyZBImp8Wkh15lqBEGwhtJdeF

**Comment by GuinnessX** [comment]
> This one is with appcompat theme and the latest few improvements
> 
> https://drive.google.com/open?id=1Y3skDhFFyZBImp8Wkh15lqBEGwhtJdeF

This one also crashes at the same spot.

**Comment by enricocid** [comment]
> > This one is with appcompat theme and the latest few improvements
> > https://drive.google.com/open?id=1Y3skDhFFyZBImp8Wkh15lqBEGwhtJdeF
> 
> This one also crashes at the same spot.

https://drive.google.com/open?id=1b2lBzps8D7whQONrQMoVbO-Zy8Jg3v8z

**Comment by GuinnessX** [comment]
> https://drive.google.com/open?id=1b2lBzps8D7whQONrQMoVbO-Zy8Jg3v8z

Still the same...

**Comment by enricocid** [comment]
> > https://drive.google.com/open?id=1b2lBzps8D7whQONrQMoVbO-Zy8Jg3v8z
> 
> Still the same...

Weird. These are 4.1.9 that You say are working

https://drive.google.com/open?id=1uuT4hVS3fNPyqQXpaGP-fopk4wZq4e_y

**Comment by GuinnessX** [comment]
There were two apks at that last link.  I tried them both, and both crash the same.  Yes, 4.1.9 from the Play store works just fine...

**Comment by enricocid** [comment]
> There were two apks at that last link. I tried them both, and both crash the same. Yes, 4.1.9 from the Play store works just fine...

Then this is related to build variant. Could You try this release build (ready for playstore)?

https://drive.google.com/open?id=19E-yY7q2Zx3DBBlIFDmrAccdzKezqfAb

**Comment by GuinnessX** [comment]
> > There were two apks at that last link. I tried them both, and both crash the same. Yes, 4.1.9 from the Play store works just fine...
> 
> Then this is related to build variant. Could You try this release build (ready for playstore)?
> 
> https://drive.google.com/open?id=19E-yY7q2Zx3DBBlIFDmrAccdzKezqfAb

This one works.

**Comment by enricocid** [comment]
Ok :) Gonna post some apks with the db the next days . Thanks :)

**Comment by enricocid** [comment]
@GuinnessX 

Hello, could You try this? (hope coroutines && viewmodel will work this time)

https://drive.google.com/file/d/18YwQxQKUE5vd0VeGfYgDxtH_1fSE2GU1/view?usp=sharing

**Comment by GuinnessX** [comment]
I had to request permission to access the file...

**Comment by enricocid** [comment]
> I had to request permission to access the file...

You can access now :)

**Comment by GuinnessX** [comment]
It works!

**Comment by enricocid** [comment]
> It works!

Thanks :-)

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
