### ISSUE TITLE
Issues with MusicBar

### ISSUE THREAD

**Issue by juacq97** [enricocid/Music-Player-GO#106]
Hi!, I love the new version, minimalist, but more usefull imo, but the now playing view has 2 issues. First the progress bar doesn't update fine, sometimes stops 2 or three seconds. Second, the play/pause button looks strange, like chopped:
![Screenshot_20200103-122005](https://user-images.githubusercontent.com/7623047/71759327-d304b900-2e68-11ea-8ed8-2e1b7fb365cc.png)

**Comment by enricocid** [comment]
Wow weird. Device?

**Comment by juacq97** [comment]
A Xiaomi Mi A1, stock rom android 9

**Comment by enricocid** [comment]
I have a Xiaomi Mi A2 lite, almost the same device. I'm not experiencing this issue. Do you have some display or other particular options enabled?

**Comment by juacq97** [comment]
I found it. I have a small screen size (settings>display>display size) If I change to small or big the buttons looks like in the screenshot

**Comment by enricocid** [comment]
Hello,
could You please test this apk to see if icons problem is solved?

https://drive.google.com/open?id=1_ZYdkPnjbeEWcRrYlpVznFeLJh-ylfI0

**Comment by juacq97** [comment]
![Screenshot_20200105-142900](https://user-images.githubusercontent.com/7623047/71786359-ce0a4b80-2fc7-11ea-948d-e4c6d8c6cb26.png)

The icons still looks strange

**Comment by enricocid** [comment]
Could You try this?

**Comment by juacq97** [comment]
![Screenshot_20200106-090941](https://user-images.githubusercontent.com/7623047/71830616-56d6c500-3064-11ea-847c-c3207698b53b.png)
That debug works!

**Comment by enricocid** [comment]
Thanks. Closing :)

**Comment by enricocid** [comment]
MusicBar has been removed for compatibility issues so I'm closing the issue
