### ISSUE TITLE
Sort songs in folder alphabetically

### ISSUE THREAD

**Issue by rubo77** [enricocid/Music-Player-GO#107]
At the moment in most of my folders, the songs seem in any random order.

Add a button to sort by taged track Nr or filename

**Comment by berenddeschouwer** [comment]
For Me:

By artist it appears OK

By album it appears to sort by song name, as opposed to track number or file name.

**Comment by enricocid** [comment]
The songs order is the default order in the MediaStore database.
I don't know if sorting by track makes sense. For example, in my folders I can have multiple songs starting with the same track number. Anyway, I can add it if you want and I can add options to sort by name, if I find some space in the toolbar...

**Comment by rubo77** [comment]
Sorting by track nr is a must, if you want to listen to an album in the correct order

**Comment by enricocid** [comment]
> Sorting by track nr is a must, if you want to listen to an album in the correct order

Songs in albums are already sorted by track.
The problem here are folders :)

**Comment by berenddeschouwer** [comment]
Songs in albums appear under "artist" tab, and choose an album.  The song list is incomplete unless the artist is the same for the whole album.  That isn't true for collaborations or compilations.

Under the "folders" tab, if your album is in a unique folder it will appear with all songs, but unsorted.

Is there another way to list an album?

**Comment by enricocid** [comment]
> The song list is incomplete unless the artist is the same for the whole album. That isn't true for collaborations or compilations.

Songs are organized by artists and then into albums so compilations are actually not supported.

> Under the "folders" tab, if your album is in a unique folder it will appear with all songs, but unsorted.

This is the order in the MediaStore database. I pushed a commit to let the users sort songs on the fly by track or by name :)
