### ISSUE TITLE
Improve shuffling

### ISSUE THREAD

**Issue by BenWestcott** [enricocid/Music-Player-GO#108]
I've been using Vinyl as my music player for a while now, and I'd like to use yours instead as I quite like the new user interface.
I found shuffling my entire library often repeats some songs while almost never playing others, just due to how shuffling works on Android. I get much better variety if I shuffle just the songs I haven't listened to in the past month or so, which was a really nice feature of Vinyl.
This might require keeping a database though, since Android doesn't seem to keep file access timestamps. I haven't written software for Android, so I don't know how difficult that would be.

**Comment by enricocid** [comment]
Yes, I agree, shuffling needs improvements.

**Comment by enricocid** [comment]
Hello,

I tried to improve shuffling [here](https://github.com/enricocid/Music-Player-GO/commit/419dea5ad3cd0abbeecfc1faad2c3c118b296408). It will be available in next release tomorrow. Once you receive the update let me know if it is ok. Thanks :)

**Comment by BenWestcott** [comment]
Yes, this has fixed the issue, thanks.

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
