### ISSUE TITLE
Wrong number of Artist's songs if opened from folder

### ISSUE THREAD

**Issue by keddad** [enricocid/Music-Player-GO#113]
Here is video showing the problem: https://www.youtube.com/watch?v=bJc5-dqmNDg
If you just open the player bar and click on artist name, artist page shows number of his tracks fine. But if you open Folders -> {some_folder} and then open the track and artist's page, number of his tracks is the number of tracks in the folder instead.

**Comment by enricocid** [comment]
Thanks for reporting.
This is the intended behaviour.
Long clicking on playing song will open the selected album. In the future I will implement some logic to show folder (if the song comes from a folder).
