### ISSUE TITLE
Blank UI when opened (only appears after the screen is rotated)

### ISSUE THREAD

**Issue by zmni** [enricocid/Music-Player-GO#116]
Nokia 5, Android One (Pie). Also occurs when activating and deactivating tabs.

![ScreenCam_20200112_215851](https://user-images.githubusercontent.com/841523/72221142-38078f80-358a-11ea-885b-cceb2436403b.gif)

**Comment by enricocid** [comment]
try this

https://drive.google.com/open?id=12XI5YyJBWzYObp0d_lEJb_MMyiJ9JQ7_

**Comment by zmni** [comment]
The link 404, missing last character `_`. The debug apk works, there is a slight delay but the UI is loaded properly. Thank you. :+1:

**Comment by enricocid** [comment]
> The link 404, missing last character `_`. The debug apk works, there is a slight delay but the UI is loaded properly. Thank you. 👍

That's because it is a debug apk :) it should be ok in release build
