### ISSUE TITLE
Wording not matching behaviour when closing the application during play

### ISSUE THREAD

**Issue by fwSmit** [enricocid/Music-Player-GO#122]
When closing the application while a song is playing with the big 'X' in the top left, the app asks if you want to stop the song. The two options you can choose from are 'CANCEL' and 'OK'. I think the wording should be changed a bit here. When you press 'cancel', the app will not cancel the closing of the app. Instead it closes the app and keeps the song playing.
I would suggest to change the options to 'yes' and 'no'.

**Comment by enricocid** [comment]
No problem, gonna fix tomorrow :) thanks for the suggestion

**Comment by enricocid** [comment]
Done https://github.com/enricocid/Music-Player-GO/commit/400b8e4e707a878c9821ec9d55e4aa960eb38007

**Comment by fwSmit** [comment]
Cool, you even did all the languages. Well done
