### ISSUE TITLE
Show an empty fragment when no music is found

### ISSUE THREAD

**Issue by FredHappyface** [enricocid/Music-Player-GO#131]
# Expected 
Open app
Grant storage permission
Application starts up successfully

# Actual
Open app
Grant storage permission
Application crashes with toast notification of "something went wrong :(" - :disappointed:  Indeed

# System Information
Nokia 8 sirocco
Android 9 Pie
December 19 security patch
Google Play/ Fdroid/ GitHub Latest APK

**Comment by enricocid** [comment]
That's not a crash. The app is getting closed if:

1- no music is present on the phone
2 - if something went wrong during the query. In this case I need a logcat to be able to fix any possible bug.

Could you please send me a bug report (reproduce the error while bug report is being registered)?

https://developer.android.com/studio/debug/bug-report

Thanks

**Comment by FredHappyface** [comment]
Ah that could well explain it. To be honest I can't quite remember if I have any music on my device at this time.

In which case it might be more useful for the end user if you either display something like "no music" in an empty activity or change the error message. 

I'll be sure to put some music on my phone if that's the issue as I'd really like to try this app out. Looking at the screenshots it looks really impressive.

Thanks for your time and for getting back to me so soon 😊

**Comment by FredHappyface** [comment]
Just tried it. It turned out that the issue was because I had no music.

**Comment by enricocid** [comment]
Ok, no problem. I will add a fragment with a message like "no music" or something like this instead of killing the app :) Thanks :))

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
