### ISSUE TITLE
No Audio Focus on Lineage OS 14.1

### ISSUE THREAD

**Issue by abirke** [enricocid/Music-Player-GO#137]
Hi there,

on my phone it appears the app never catches audio focus as other players can play simultaneously and AVRCP commands from headphones start a different player even with Music Player GO playing and in the foreground.

I am running Lineage OS 14.1 (Android 7.1.2) and installed a self-built Music Player GO 4.1.7. Can I take any particular logs to help debugging this or can you point me to some parts of the code (even though I am a total newbie to Kotlin)? This is most probably related to #111 but the only thing I could find so far is that _playerService.registerReceiver_ is indeed called, but I couldn't find any calls to _NotificationReceiver.onReceive_ while playing around.

Anyway, thanks for a great app and for your support!

**Comment by enricocid** [comment]
Thanks for reporting. Yes, it is related to this issue.

I was able to reproduce the issue on my mother's redmi3 running lineage os 14.1.
The problem is I missed one line of code to set the session active. 
The default music player started because it is probably listed in Android's mediabrowser as the latest active media session so its priority was higher.

Let me know if this apk works good so I'm gonna post the changes :)
https://drive.google.com/open?id=10MOUf8womczQExFZYtHfaKj4mLGsDjY_

**Comment by enricocid** [comment]
(ignore this message, I'm posting this message to complete a report to GitHub)

https://drive.google.com/open?id=10MOUf8womczQExFZYtHfaKj4mLGsDjY_

**Comment by abirke** [comment]
Wow, that was quick! Thank you, the controls work perfectly fine now. Only fast-forward and rewind are missing, but they might not have been implemented before, anyway?

**Comment by enricocid** [comment]
> Wow, that was quick! Thank you, the controls work perfectly fine now. Only fast-forward and rewind are missing, but they might not have been implemented before, anyway?

Thanks :) Fast-forward is still not supported but rewind (KeyEvent.KEYCODE_MEDIA_REWIND) yes. This is the [method](https://github.com/enricocid/Music-Player-GO/blob/42acfbe7f1215d1bd434dfd13df62e8708ea795e/project/app/src/main/java/com/iven/musicplayergo/player/PlayerService.kt#L105) that handles media buttons intent. 
Anyway, I probably missed a keyEvent for the particular button as I implemented this feature almost blindly (don't have this kind of headsets... )

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
