### ISSUE TITLE
Repeat ONE repeats ONCE

### ISSUE THREAD

**Issue by PhoenixIV** [enricocid/Music-Player-GO#142]
I chose a file via folder view and enabled repeat [1].

Observed behaviour: After the song finished, it skipped to the beginning AND DISABLED the repeat option. It, thereby, repeated the song once and then played the next one.

Expected behaviour: The current song should repeat over and over again, unless using the skip option.

**Comment by enricocid** [comment]
This is exactly the normal behaviour. 1x means repeat once then skip next.
Anyway I can implement it in next updates...

**Comment by enricocid** [comment]
Loop has been implemented, it will be available in next update :) Closing

**Comment by shom13** [comment]
Loop has been implemented, just got the update today. Thanks for the feature, really appreciate your work.
