### ISSUE TITLE
Add folders to app

### ISSUE THREAD

**Issue by samkpo** [enricocid/Music-Player-GO#145]
I've installed the app but I've  unable to explore folders. How is it done?

**Comment by samkpo** [comment]
Closing it. It was my phone that didn't started the media, a reboot and it was ready to go.

**Comment by enricocid** [comment]
> Closing it. It was my phone that didn't started the media, a reboot and it was ready to go.

Yeah, that's a known issue with MediaStore that is not ready to be queried in certain situations (it affects phonograph and shuttle too) . For example: occasionally, when You lock/unlock the device the sdcard is unmounted/mounted back again, forcing the mediastore to rebuild its records. So when You open the app during this process the app won't be able to scan for music.
Some patience and reboot usually fixes the issue.
I will inform users in next updates :)

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
