### ISSUE TITLE
The music stops when you start a game

### ISSUE THREAD

**Issue by Reek0** [enricocid/Music-Player-GO#158]
It is normal for the music to stop when you start a game, but the application disappears from the notification bar when you start the game (Minecraft Bedrock Edition 1.14.30.2). Which does not make it possible to expand the notification bar to continue playing the music.

I have a Samsung J260M. Android Go 8.1.0

**Comment by enricocid** [comment]
Try to disable audio focus management in options :)

**Comment by enricocid** [comment]
This one is related to focus. Just disable it before playing any game 😉
Closing.
