### ISSUE TITLE
Missing Album Art

### ISSUE THREAD

**Issue by moriel5** [enricocid/Music-Player-GO#16]
The album art is not shown.
I am guessing that this feature has not yet been implemented?

In any case, great job!
I am planning on moving over to Music Player GO, now that there finally is a sub-1MB music player at this level.

**Comment by moriel5** [comment]
Ah, well I am a little disappointed, since with small screens, seeing the album art is really invaluable.

I'm guessing that relying on the OS for the rendering won't help in this situation?

**Comment by moriel5** [comment]
Understood then, I am sorry about pushing you.

**Comment by pwd-github** [comment]
This is a shame as this is a deal-breaker for me, but I do wish this project the best of luck.

**Comment by enricocid** [comment]
The real shame is the fact You don't read the app's description/philosophy and the commits/changes history (that I'm writing simply to update everyone).

The feature has been added few days ago,and it will be limited to embedded covers to keep the project minimal
👍🏻
https://github.com/enricocid/Music-Player-GO/commit/0d5ca8667ef8089c6b130fc964878b2e3d46c684

It will be available once all the issues will be solved
