### ISSUE TITLE
Long  audio files won't play entirely

### ISSUE THREAD

**Issue by Wilker-a** [enricocid/Music-Player-GO#161]
whenever you play a long audio file, surpassing or manually placing the timestamp at around 96 minutes will cause the file to stop and be skipped. that makes it unable to play audio files lasting two hours or more. \^\^

**Comment by enricocid** [comment]
Thanks for reporting. Could you compress the file and share it with me so I can try to reproduce the issue?
Don't really know where to get a long audio file 🤡
Thanks

**Comment by enricocid** [comment]
I was able to reproduce it. I'm working on the fix, gonna update You soon

**Comment by Wilker-a** [comment]
i'll be sure to do it, and return with an answer when i'm done. thank you \^\^

**Comment by Wilker-a** [comment]
took a while to get the chance to test it, considering that it was also possible that the file wasn't downloaded entirely (not corrupted but incomplete). turns out it was, so this isn't an issue with the program. \^\^

i'm closing the issue. :3
