### ISSUE TITLE
Music file incompatible

### ISSUE THREAD

**Issue by Giovaneafagundes** [enricocid/Music-Player-GO#167]
M4a and ogg can't be detected on the player

**Comment by enricocid** [comment]
MediaPlayer does not support certain formats unfortunately, but you can change the extension in some cases
https://github.com/enricocid/Music-Player-GO/blob/master/FORMATS.MD

Could you post two files so I can try?

**Comment by atticor** [comment]
I don't know about ogg, but i downloaded some YTstuff as .m4a using Newpipe and they didn't appear. 
A .m4a file is just an audio-only-mp4 file though(as I've read) so it worked just fine by changing the end to that. So either a manual rewriting of every file downloaded using that ending, or the app learns to treat m4a as mp4.

**Comment by enricocid** [comment]
> I don't know about ogg, but i downloaded some YTstuff as .m4a using Newpipe and they didn't appear.
> or the app learns to treat m4a as mp4.

The problem is that these files are not even being listed when the app queries for music files.
The container is not supported in android media player API.
