### ISSUE TITLE
[Feature request] Setting for default sorting method in albums

### ISSUE THREAD

**Issue by Trevonn** [enricocid/Music-Player-GO#172]

**Comment by enricocid** [comment]
Thanks for the suggestion. Gonna add it in the Future 😉

**Comment by enricocid** [comment]
This one has been solved

https://github.com/enricocid/Music-Player-GO/commit/ff670931dd3d259d1d3ee3a5c76ccdb197b4b762

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
