### ISSUE TITLE
music player go cant find equalizer and the action stops song timer.

### ISSUE THREAD

**Issue by cckole** [enricocid/Music-Player-GO#18]
when music is played, click the settings button and click on equalizer, it will display """No equalizer is found'''' and this at the same time will stop the timer as the music keeps playing on ANDROID 7.0

check the video link below

https://youtu.be/ZwGwyuZvvdU

**Comment by enricocid** [comment]
Thanks for the report, gonna investigate the issue

**Comment by enricocid** [comment]
I checked my implementation, and it seems that this problem is device related (no eq with ACTION_DISPLAY_AUDIO_EFFECT_CONTROL_PANEL is present). Try to see if it is disabled in Settings/All apps (see also system apps)
There's nothing I can do unfortunately.
