### ISSUE TITLE
Swipe to add to Queue

### ISSUE THREAD

**Issue by lab-at-nohl** [enricocid/Music-Player-GO#180]
Feature request. 

Nice Player!!

**Comment by mathieu-aubin** [comment]
@lab-at-nohl please change the title to 'swipe' instead of 'swype' - thanks

**Comment by enricocid** [comment]
added

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
