### ISSUE TITLE
GIF optimization suggestion

### ISSUE THREAD

**Issue by mathieu-aubin** [enricocid/Music-Player-GO#183]
i propose some optimization on the readme file gif in order to reduce the size of it.

I took the liberty of doing some tests ising gifsicle and here are some of the results

https://github.com/mathieu-aubin/tempgif

i believe 64 colors, scaled to 80percent if a good compromise

**Comment by mathieu-aubin** [comment]
ive also added some webp and apng, because i could

**Comment by enricocid** [comment]
Thanks, really appreciated. Gonna add it to the repo as soon as I'll get a computer! :)

**Comment by enricocid** [comment]
@mathieu-aubin I decided to go for webp (55) as it is a really good compromise and it is only 500KB. The art now loads faster (I have a slow internet connection and that's a real improvement for me) on the previews. Thanks :)

**Comment by mathieu-aubin** [comment]
@enricocid that was the idea behind making the artwork smaller. I am lucky to have a decent connection but even with that, i can see that 5MB artwork is very undesirable. I have been around since the first days of the internet and remember all too well how important optimization of ressources is, even in the changing times where milliseconds matter, alot.
