### ISSUE TITLE
Audio focus issues when other app plays music

### ISSUE THREAD

**Issue by BlackEdder** [enricocid/Music-Player-GO#184]
Musicplayergo seems to forcibly "grab" audio output on start, stopping other apps that are already playing in the background. If I start the other app again, musicplayergo crashes.

**Comment by enricocid** [comment]
Thanks for reporting. Could please send me a bug report?

**Comment by enricocid** [comment]
@BlackEdder
I've been able to reproduce an issue where focus is requested as soon as mpgo is opened making the other player app to stop playback.
I was not able to reproduce any crash

 Could You please try this one?
https://drive.google.com/open?id=1aJk53a1-3w80rF83X2-g1GyivlRHdwmV

It's a debug apk so You have to uninstall the previous mpgo version 

Thanks

**Comment by BlackEdder** [comment]
Sorry I was mistaken. The app doesn't crash, it just closes, presumably because it loses hold of the audio device.

Would be nice if the audio device is only "grabbed" when mpgo actually plays back audio. And instead of closing would just stop playing when losing focus.

**Comment by enricocid** [comment]
> Sorry I was mistaken. The app doesn't crash, it just closes, presumably because it loses hold of the audio device.
> 
> Would be nice if the audio device is only "grabbed" when mpgo actually plays back audio. And instead of closing would just stop playing when losing focus.

- I made changes so that MPGO requests focus when it starts playing and not as soon as it is opened

- The loss of focus means pause, the app is not closed but [paused](https://github.com/enricocid/Music-Player-GO/blob/0eab9fc05d7b6318f4eedb4736988a40c347a81a/project/app/src/main/java/com/iven/musicplayergo/player/MediaPlayerHolder.kt#L569)

- I've found an issue where the current track is lost when the app is paused. This is due to the Android memory management that forces the app to reinstatiate.
To bypass this issue I can save the song played before the loss of focus/it is paused. This way, when going back to MPGO You will be able to restore the latest played song

**Comment by enricocid** [comment]
@BlackEdder 

Could you try this apk?

https://drive.google.com/open?id=1Rr07nFNtH3K9ovmAskgm2HuQXKCl7doy

**Comment by BlackEdder** [comment]
I tried that. That does work, the only issue now is that it doesn't interact with the other audio stream at all, so I ended up playing two things at the same time. I'd expect it to pause all other audio instead.

**Comment by enricocid** [comment]
> I tried that. That does work, the only issue now is that it doesn't interact with the other audio stream at all, so I ended up playing two things at the same time. I'd expect it to pause all other audio instead.

Strange, it is working great with Phonograph music player.
What players are You using?
Android version?

**Comment by BlackEdder** [comment]
I've mostly tested it with newpipe. My android version is 7.0.

**Comment by enricocid** [comment]
I've tried using newpipe and it is working also on my mother's redmi3 that is running a nougat rom. Try to enable/disable the focus option to see if it fixes the issue.

**Comment by BlackEdder** [comment]
Did you try to do it with NewPipe in the background. Currently, it does work if I start newpipe when mpgo is playing, but if I then start mpgo again (from the notification area) then newpipe keeps playing.

I have confirmed that the same test works correctly for me with another musc player: https://github.com/SimpleMobileTools/Simple-Music-Player

**Comment by BlackEdder** [comment]
I just got an updated version through fdroid. That one seems to work. Thank you and closing this now.

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
