### ISSUE TITLE
On Always On Display, "No Title" is displayed

### ISSUE THREAD

**Issue by hybras** [enricocid/Music-Player-GO#185]
The problem seems to be the same one specified [on this StackOverflow Thread](https://stackoverflow.com/questions/59144878/media-session-has-no-title-on-aod-always-on-display). I will open a PR fixing this (if i even know what im doing).

**Comment by hybras** [comment]
I have no idea what I'm doing. It seems `mNotificationBuilder.setContentTitle(String)` 
Needs to be called somewhere in `MusicNotificationManager`. But where exactly? It is already called in `updateNotificationText.` The notification text is updated when creating/updating a notification (both in `MediaPlayerHolder.startForeground()`. Does it have something to do with the string being HTML?

Anyways for reference, here is the [Android Notification Overview](https://developer.android.com/guide/topics/ui/notifiers/notifications).

**Comment by enricocid** [comment]
Thanks for reporting. The solution proposed on the stackoverflow thread You posted is applicable only on ExoPlayer.
Anyway, as for the SeekBar into the status bar (Android 10), I think that we need to put that information into the MediaSessionCompat not the notification itself that is ok.

If You can test (I can't unfortunately) You can try this:

Change [updateSessionMetaData()](https://github.com/enricocid/Music-Player-GO/blob/9b2fc8e4013a444c2a12feb40a6bdfc47fef0108/project/app/src/main/java/com/iven/musicplayergo/player/MediaPlayerHolder.kt#L187) to this:

```
private fun updateMediaSessionMetaData() {
        val mediaMediaPlayerCompat = MediaMetadataCompat.Builder().apply {
            if (VersioningHelper.isQ()) putLong(MediaMetadataCompat.METADATA_KEY_DURATION, currentSong.first?.duration!!)
            putString(MediaMetadataCompat.METADATA_KEY_ARTIST, currentSong.first?.artist)
            putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_SUBTITLE, currentSong.first?.album)
        }
        playerService.getMediaSession().setMetadata(mediaMediaPlayerCompat.build())
    }
```

And [this line](https://github.com/enricocid/Music-Player-GO/blob/9b2fc8e4013a444c2a12feb40a6bdfc47fef0108/project/app/src/main/java/com/iven/musicplayergo/player/MediaPlayerHolder.kt#L458) to this:

`updateMediaSessionMetaData()
`

**Comment by Drhaal** [comment]
I just tried your fix, it seems to work with and added line for the title. But i can only test title and album display since my device doesn't handle more than that.
I will create a pull request with the fix.

**Comment by enricocid** [comment]
Thanks. This issue appears to be fixed so I'm closing for now :)

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
