### ISSUE TITLE
[Feature request] swipe away items from awaiting list / favorites

### ISSUE THREAD

**Issue by Drhaal** [enricocid/Music-Player-GO#187]
Items in the awaiting list and favorites should have the possibility to be swiped away to remove them from the list.
This should be easier than long pressing the item then confirming the deletion in the pop-up.

**Comment by Drhaal** [comment]
I can implement it if you want.

**Comment by Drhaal** [comment]
added a pull request for this in: #190

**Comment by enricocid** [comment]
added
