### ISSUE TITLE
The order of tracks should not completely alphanumerical

### ISSUE THREAD

**Issue by devdan** [enricocid/Music-Player-GO#194]
When files start with track numbers, then the ordering is messed up. 10 comes after 1 instead of after 9 and so on.

**Comment by devdan** [comment]
At least in the folder view

**Comment by enricocid** [comment]
That's the default songs order in the database. Use the overflow menu to change the sorting to numerical.
I will later add an option to persist the choice in folders

**Comment by devdan** [comment]
Thanks!

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
