### ISSUE TITLE
Issue on the ProgressBar in main_activity.xml

### ISSUE THREAD

**Issue by john2020star** [enricocid/Music-Player-GO#196]
Hello,

I have tried your app and found there is an issue in main_activity.xml.

`        <ProgressBar
             android:id="@+id/loading_progress_bar"
             android:layout_width="@android:dimen/app_icon_size"
             android:layout_height="@android:dimen/app_icon_size"
             android:layout_gravity="center"
             android:clickable="false"
             android:indeterminateTint="?attr/colorPrimary"
             android:visibility="gone" />
`
This ProgressBar will shown when I start the app. But actually it does not work in API <= 22, because you did not set android:indeterminateTintMode="src_in". 
Simply set it can avoid the issue.

**Comment by enricocid** [comment]
Thanks for letting me know. I'm gonna fix this issue asap :)

**Comment by enricocid** [comment]
Hi, could You try this one?

https://drive.google.com/file/d/1CkEnlAckYMENeSmTNhbov2e64PJFTl10/view?usp=sharing
