### ISSUE TITLE
Edge-to-edge option toggle colors status bar with accent color

### ISSUE THREAD

**Issue by vatonbero** [enricocid/Music-Player-GO#199]
`Version: 4.2.7`

Toggling "Edge-to-edge" option changes status bar color to accent. If Edge-to-edge is toggled on, status bar will honor system theme without accent color.

Here are the images:

With edge to edge enabled (no accent in status bar):
<img alt="music-player-go - enabled edge-to-edge" src="https://user-images.githubusercontent.com/59034981/82140977-04d45600-9833-11ea-824c-55b6a8bae77a.jpg" width="40%"/>

With edge to edge disabled (status bar changes to accent color):
<img alt="music-player-go - disabled edge-to-edge" src="https://user-images.githubusercontent.com/59034981/82140975-03a32900-9833-11ea-97fd-525c0eb1b832.jpg" width="40%"/>

**Comment by enricocid** [comment]
Thanks, that is the expected behaviour. Gonna add an option to disable status bar colouring later :)

**Comment by vatonbero** [comment]
Hi,

> Thanks, that is the expected behaviour. Gonna add an option to disable status bar colouring later :)

Can this be noted somewhere then? Edge-to-edge sounds like an option where this status bar change should not occur.
