### ISSUE TITLE
App can not found my music file on my phone

### ISSUE THREAD

**Issue by Icramss** [enricocid/Music-Player-GO#20]

**Comment by Icramss** [comment]
Looking with other music player apps, I can get my music files 

Android 6.0.1

**Comment by enricocid** [comment]
Send me at least a music file so I can try to reproduce. Thanks

**Comment by Icramss** [comment]
https://drive.google.com/file/d/1PdEiQ9sFV3j43c0eYPnNVecJhdXpJQVz/view?usp=drivesdk

This is one of my music . You get it in my drive

**Comment by enricocid** [comment]
Thanks,
The problem is that I added a filter to remove songs tagged with <unknown>. I will correct this issue in next update and you will be able to see your songs
