### ISSUE TITLE
Only swiches to next song when woken up

### ISSUE THREAD

**Issue by UltraBlackLinux** [enricocid/Music-Player-GO#203]
Is this intended? Its quite annoying.

**Comment by enricocid** [comment]
Device? 
The same is happening on my mi A2 lite running Android 10.
I will try to solve this issue as soon as possible (just ordered a new pc and I will start working on mpgo by the mid of June)

**Comment by UltraBlackLinux** [comment]
yes. android 10 (lineageos) on a razer phone. Ty for the Help!

**Comment by enricocid** [comment]
Hi,

I tried to use partial wakelock when a song is completed to fix the problems with playback when the screen is off.
It is working in my test.

This change will be available in the upcoming update (hopefully this weekend).

If You still have problems please don't hesitate to re-open the issue :)
