### ISSUE TITLE
[New feature] embedded covers support is coming

### ISSUE THREAD

**Issue by enricocid** [enricocid/Music-Player-GO#209]
Hi,

For those who asked (@harisont :P) for this feature these months: **embedded** covers support is coming. 

It will be available in the next update which will probably feature a UI design overhaul and equalizer.

![Screenshot_20200628-223620](https://user-images.githubusercontent.com/7274841/85957741-398a1000-b990-11ea-8fc4-41fcca62add8.png)

![Screenshot_20200628-223522](https://user-images.githubusercontent.com/7274841/85957737-342cc580-b990-11ea-8722-5de476b3db6b.png)

**Comment by mathieu-aubin** [comment]
using musicbrainz db? (sorry cant check code atm, or even view much more than some characters!)

**Comment by enricocid** [comment]
> using musicbrainz db? (sorry cant check code atm, or even view much more than some characters!)

No, only the embedded picture (if available) from the file's tags for now ;)

**Comment by harisont** [comment]
Great!
How is it that UI things in Android don't drive you insane? How did you actually learn? haha

**Comment by enricocid** [comment]
> Great!
> How is it that UI things in Android don't drive you insane? How did you actually learn? haha

I'm a Materials Scientist ... I'm used to material design 😂😜

**Comment by enricocid** [comment]
added, it will available the next release

**Comment by mathieu-aubin** [comment]
> using musicbrainz db? (sorry cant check code atm, or even view much more than some characters!)

Did this spark some sort of ... anything? I guess that it probably wouldnt be too hard to grab tags and a quick api to musicbrainz in order to retrieve some art. Maybe not as a 'always on by default'... as an option maybe. with caching support or, even better, direct embedding of fetched media into file (again, optional..) for further and permanent use while growing a better music colection.

just saying :)

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
