### ISSUE TITLE
Enhance play queue capabilities

### ISSUE THREAD

**Issue by fredx100** [enricocid/Music-Player-GO#210]
It would be useful to be able to add whole albums or folders or shuffled songs to the play queue. Of course, you'd then likely want to be able to clear/edit the queue too.

**Comment by paintaneight** [comment]
This is much needed!

**Comment by enricocid** [comment]
You can already remove items from the queue and clear it (just long press the queue button).

I will add the remaining feature in the future but consider that it will not happen very fast (December/January) (as soon as I will be able to buy a good notebook for development).
👍🏻

**Comment by enricocid** [comment]
These features has been added 👍🏻  closing :)
