### ISSUE TITLE
Full Audio File Name and Thumbnail pics features

### ISSUE THREAD

**Issue by Pranab009** [enricocid/Music-Player-GO#211]
![Uploading Screenshot_20200721-144621.png

Hello sir, 
please add full audio file name and thumbnail pics features in music player.
Like this pics.

**Comment by enricocid** [comment]
Added ;)

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
