### ISSUE TITLE
Chinese translate can't display

### ISSUE THREAD

**Issue by aimerneige** [enricocid/Music-Player-GO#217]
When I set my system default language into Chinese, I found the app's language still English. After checking the source code, I find the Chinese translation doesn't have Chinese-Simplify and Chinese-Traditional support. I will fix this later. Please check for my Pull Request.

**Comment by aimerneige** [comment]
I have posted a pull request. #128 
I am a programming beginner, If there is any problem, I am sorry.

**Comment by enricocid** [comment]
Merged
