### ISSUE TITLE
Use GPLv3 or later as translation license

### ISSUE THREAD

**Issue by comradekingu** [enricocid/Music-Player-GO#219]
The translation component on https://hosted.weblate.org/projects/music-player-go/strings/#information is GPLv3 only, when I think it should have been GPLv3+ :)

**Comment by enricocid** [comment]
Changed, thanks 👍🏻 :)

**Comment by comradekingu** [comment]
@enricocid Actually you changed it to LGPL.
https://hosted.weblate.org/changes/?project=music-player-go&lang=&action=55&user=
I can fix it and add fastlane translations if you add https://hosted.weblate.org/user/kingu/ as an admin :)
It is easy to do, but it is many steps to explain the settings for.

**Comment by enricocid** [comment]
> @enricocid Actually you changed it to LGPL.
> https://hosted.weblate.org/changes/?project=music-player-go&lang=&action=55&user=
> I can fix it and add fastlane translations if you add https://hosted.weblate.org/user/kingu/ as an admin :)
> It is easy to do, but it is many steps to explain the settings for.

Done, thanks :)
