### ISSUE TITLE
1 single song in an album is automatically repeated even the repeating option is off

### ISSUE THREAD

**Issue by rockstar96969696** [enricocid/Music-Player-GO#22]
Song automatically repeated if we have only one song in a single album and then play this song. My device is samsung galaxy s7 Android Nougat 7.0. App Version 2.4.1.5

**Comment by enricocid** [comment]
It is because when the playback is finished the algorithm automatically search for the next song in the album and if there is no song in the next posioon the first song is played

**Comment by rockstar96969696** [comment]
Then change the algo please

**Comment by enricocid** [comment]
What would you like it to do?
