### ISSUE TITLE
[FR] A lot of requests

### ISSUE THREAD

**Issue by RickyM7** [enricocid/Music-Player-GO#220]
<h2 align="center">Requests in progress</h2>

- [x] 1. `[Feature] Sleep timer:` This feature stops the songs that is playing when the time has elapsed.  It would be good if it was like in the MX Player or [Pulsar](https://play.google.com/store/apps/details?id=com.rhmsoft.pulsar) (in screenshots) that we determine the time that the songs will be playing and if it is to let the last song play completely, even after the sleep timer has ended.
[This project](https://github.com/AndreyPavlenko/Fermata) might help with something because it has the timer feature. It also has other features that can help with other points covered in this issue.

| Sleep Timer Settings | Sleep Timer On |
| :---: | :---: |
| ![sleep timer](https://user-images.githubusercontent.com/24703825/103410717-5542be80-4b4b-11eb-93bc-dc6a07dea8b9.jpg) | ![sleep timer on](https://user-images.githubusercontent.com/24703825/103410721-58d64580-4b4b-11eb-822f-ae49fb67456f.jpg) |

- [ ] 2. `[Bug/Feature] Remember the settings of player/queue and fix loop buttons:` When you exit and enter the app the queue is cleared and only the last song played remains and it is looping, this should not occur, the queue should remain unchanged regardless of whether you exit the app. In addition to the queue remaining unchanged, the volume and loop settings should also be remembered, even if you exit the app.

About the loop buttons, there is currently an option that defines what occurs after a queue ends, but if the loop buttons work as expected, this option will no longer be required.

Expected behavior:
  - `Single repetition/Repeat 1x (🔂) [Correct title: Repeat this song]:` If enabled it should make the current song (alone or in a queue) play infinitely. If disabled it should simply make the current song stop when finishing (if alone) or (if in a queue) make the queue stop playing after the last song plays completely.

  - `Endless repetition/Repeat ∞ (🔁) [Correct title: Repeat all songs]:` If enabled it should make the current sound (if alone) play infinitely and if disabled should cause the current sound to stop playing. In a queue, if enabled it should make the queue play infinitely. If disabled the queue should stop playing when the last song plays completely.

  - `If none of these options are enabled:` If the song is alone it should stop after playing completely and if it is a queue, it should stop after the last song plays completely.

- [ ] 3. `[Feature] Change the shuffle songs limit in the queue:` Modify the limit freely. This option would have a message somewhere recommending the use of a value ≤100 to avoid problems.

<p>
<em>These below requests are based on <a href="https://play.google.com/store/apps/details?id=com.rhmsoft.pulsar">Pulsar</a>. This was the player I used because it is lightweight, simple and efficient but I switched to MPGO because in addition to lightweight, simple and efficient it is open source and free of useless trackers and permissions. Pulsar has some things that, if implemented in MPGO will make it even better.</em>
</p><br />

- [ ] 4. `[Feature] "Previous, Play/Pause and Next" buttons on the song in progress and drag to open more options:`

![control buttons](https://user-images.githubusercontent.com/24703825/102715805-818e4d80-42b6-11eb-9ece-81da5491e09a.gif)

- [ ] 5. `[Feature] New sorting options:` (#231, maybe #233 and #251)

![sort by](https://user-images.githubusercontent.com/24703825/102716001-b18a2080-42b7-11eb-990e-c1afe7bf72c0.jpg)

- [ ] 6. `[Feature] Playlists:` Creating playlists, option to turn a queue into a playlist, back up playlist, etc. (#132)

| Playlist | Playlists menu (float menu opened) | Queue to playlist |
| :---: | :---: | :---: |
| ![playlist](https://user-images.githubusercontent.com/24703825/102716163-cfa45080-42b8-11eb-9a3e-39f26e8b8eea.jpg) | ![playlists](https://user-images.githubusercontent.com/24703825/102716165-d337d780-42b8-11eb-93fb-b9f93eb9aa7b.jpg) | ![queue to playlist](https://user-images.githubusercontent.com/24703825/102716168-d632c800-42b8-11eb-909c-1990e25173b4.jpg) |

- [ ] 7. `[Feature] Shuffle queue:` Basically an option (button) to shuffle the queue itself.

- [x] 8. `[Feature] Indicating the song playing in the queue:` It would be great if some detail was added to show which song is currently playing in the queue (maybe a background with a different color or some icon, etc.).
Showing the song playing when opening the queue (the queue would scroll directly to the song that is currently playing) would also be a great feature.
These features would help a lot when dealing with large queues.

- [ ] 9. `[Feature] Improvements in the description of some options:` Some descriptions of some options may trust some people, and a small change can resolve this. The change would be to put a fixed description Instead of one that changes according to the state of the option.

| Option | Recommended fixed description |
| --- | --- |
| Precise volume control | Turn on/off precise volume control |
| Audio focus | Turn on/off audio focus management |
| Headset plug | Turn on/off headset plug management |
| Embedded album covers | Show/hide album covers |

<h2 align="center">Completed requests</h2>

- [x] 1. ~~`[Feature] Show file name instead of tags:` This would cause the files to be displayed with the name of the file, instead of what is in the tag, but the ideal would be to have an option to see the tags as well, and perhaps even an option to select how you prefer the songs to be shown.~~

- [x] 2. **[Added in 83dc830]** ~~`[Feature] Organize the tabs:` This would make it possible to change the positions of the tabs and perhaps even have an option to add a new tab.~~

- [x] 3. ~~`[Feature] Add all other songs in the folder or album to the queue automatically:` It would simply add all the songs in the folder or album that the song that was put to play at the moment belongs to the queue.~~

- [x] 4. ~~`[Feature] Show the album and music covers both in the player and in the notification bar and lock screen:` Basically you would have an option to show or not the covers of the songs that have covers available.~~

- [x] 5. **[Fixed in 2047360]** ~~`[Bug] Hidden songs, albums, etc:` The albums, songs, and everything else from the folders we hide should no longer appear, but they still appear in the tabs of artists and songs.~~

- [x] 6. ~~`Music progress bar improvement:` The bar is very close to the edge of the screen, this makes it impossible to drag the music to the minute 00:00 or to the end. I think just compressing the bar a little so that it gets a little away from the edge of the screen already solves the problem.~~

| Progress Bar |
| :---: |
| ![IMG_20201106_103937](https://user-images.githubusercontent.com/24703825/98372381-6cb66d00-201c-11eb-914d-f49760bd7faa.jpg) |

- [x] 7. ~~`[Bug/Feature] File name everywhere:` The "Song visualization" feature with the "filename" option selected causes file names to be shown only within folders and albums, the correct one would show the file name everywhere (as in the list of all songs, queue, etc.).~~
~~Another thing would be to have an option to show/hide the file extension.~~

- [x] 8. **[There is no option to turn this on/off but shuffle songs are now queued]** ~~`[Feature] Add shuffle songs to queue:` An option to add or not the shuffle sounds to the queue. This option would have a message somewhere warning you not to use this if you have many songs (more than 200).~~

- [x] 9. **[Partially fixed with the removal of duplicates. Queue improvements will be made later]** ~~`[Bug] Duplicate songs in queue:` In my opinion it is very useful to have how to duplicate songs in the queue, but doing this in MPGO currently causes some bugs.~~
  - ~~If duplicate song are in sequence: This song will be playing in loop.~~
  - ~~If the duplicate song is alternated: The duplicate song and the one between the duplicates will be playing in loop.~~

- [x] 10. **[528ea10 adds the option to move songs in the queue]** ~~`[Feature] Move the songs freely in the queue and playlists (if added):` Maybe this [repo](https://github.com/ernestoyaquello/DragDropSwipeRecyclerview) will help.~~

![move songs](https://user-images.githubusercontent.com/24703825/102716406-7a693e80-42ba-11eb-9e2e-f52c5262b476.gif)

- [x] 11. **[Added in v4.4.1]** ~~`[Feature] Improvement in the way of moving the tabs:` Maybe this [repo](https://github.com/ernestoyaquello/DragDropSwipeRecyclerview) will help.~~

![Move tabs](https://user-images.githubusercontent.com/24703825/102716690-38d99300-42bc-11eb-8291-9f2c13847a2b.gif)

**Comment by enricocid** [comment]
Thanks for the comprehensive post.

5 is already present in the source code, it just needs some adjustments.

Icon must be adaptive, can't use those ones :)

Unfortunately I'm not able to work on MPGO. I will work on these features very soon (as soon as I will be able to buy a good notebook).

Thanks again :)

**Comment by RickyM7** [comment]
@enricocid Thanks for the reply, and thanks for your work!

**Comment by RickyM7** [comment]
@enricocid Points 7 and 8 added. Apparently point 7 has already been added to the app but I'm not sure

**Comment by enricocid** [comment]
> @enricocid Points 7 and 8 added. Apparently the point 7 has already been added to the app but I'm not sure.

7 & 8 no. 
n.2 has been added. 
Folders anyway will show file names always (I think it is more consistent this way).

**Comment by RickyM7** [comment]
> 7 & 8 no.

Did not quite understand this part, you will not add or has already been added?
***Note***: If you do not want to add any of the points, no problem, the decision is obviously always yours and the app will continue great anyway.

> n.2 has been added.
Folders anyway will show file names always (I think it is more consistent this way).

Nice, thank you.

**Comment by enricocid** [comment]
> > 7 & 8 no.
> 
> Did not quite understand this part, you will not add or has already been added?
> _**Note**_: If you do not want to add any of the points, no problem, the decision is obviously always yours and the app will continue great anyway.
> 

No, I meant I still have to tackle these issues. I'm going to tackle all the points in the list, don't worry.

**Comment by RickyM7** [comment]
Got it, I'm sorry, it's just that English isn't my main language, so I have trouble understanding some things.

**Comment by enricocid** [comment]
> Got it, I'm sorry, it's just that English isn't my main language, so I have trouble understanding some things.

No problem :)

**Comment by enricocid** [comment]
8 solved 👍🏻  :)

**Comment by RickyM7** [comment]
@enricocid It has nothing to do with this issue, but could you put the file google_play.xml on weblate? It would be nice to have this there so that the description and changelog of the app in the play store is dynamically translated with each update.

**Comment by enricocid** [comment]
> @enricocid It has nothing to do with this issue, but could you put the file google_play.xml on weblate? It would be nice to have this there so that the description and changelog of the app in the play store is dynamically translated with each update.

Thanks for the suggestion.

Anyway, I don't if it is possible with the current plan (i'm using the one for open source apps)

**Comment by RickyM7** [comment]
@enricocid About the topics of this issue after update to v4.3.0:

- 2.: The songs are not shown by the file name in the music progress bar and in the tab of all songs and I think the file extension (.mp3, .m4a, etc) could be hidden.

- 4.: This is in the app, but I think having an option to add more than one folder in the queue at the same time would be cool.
Note: The queue I'm talking about is not the one that appears in the music progress bar but when we put a song from a folder or album to play and the other songs play next. I don't quite understand what that queue in music progress bar option is for.

- 5.: The On/Off Covers option is inverted and apparently you can not hide the covers in notifications, at least on my Redmi Note 4 (Miui 11 - Android 7.0) always appears, even if it is turned off.

6. and 7. still continue.

**Comment by enricocid** [comment]
> I think having an option to add more than one folder in the queue at the same time would be cool.

I'm working on this. I'm going to push this change in the repo within today. Folders and albums can be added to the queue.
Loved songs too will be added to the queue once a song is played.

**Comment by enricocid** [comment]
Here is a test apk :)

https://drive.google.com/file/d/1WM87SL3NOGTPJp5alYiTMhl3TfCCRZXV/view?usp=sharing

**Comment by RickyM7** [comment]
@enricocid As soon as the songs in the "queue" or the "loved songs" finish the other songs begin to play, this is expected, but if you put the same song twice in the queue it keeps playing in loop. Another thing is that if you have a song playing and you click on some loved song will appear "Loved songs enqueued! enqueued!". The add full albums to the queue feature works well. I'm not sure what I can test anymore.

**Comment by enricocid** [comment]
@RickyM7 

![MNML-December3-071456PM](https://user-images.githubusercontent.com/7274841/101071285-a9826f00-359c-11eb-8c4a-3c2a8ec820ed.GIF)

**Comment by RickyM7** [comment]
@enricocid This is perfect in my opinion. Thank you.

**Comment by RickyM7** [comment]
About v4.3.4 update:

Only 2 and 3 still continue.

**Comment by enricocid** [comment]
> About v4.3.4 update:
> 
> Only 2 and 3 still continue.

I will solve as soon as possible :) Consider I'm the only developer working on this ... :P

**Comment by RickyM7** [comment]
@enricocid I completely understand, you don't have to rush.
I comment on each update because this may be of some help. Btw, I added some information to the second point.
Thank you.

**Comment by enricocid** [comment]
> @enricocid I completely understand, you don't have to rush.
> I comment on each update because this may be of some help. Btw, I added some information to the second point.
> Thank you.

Don't worry, You're welcome. You are extremely helpful :)

**Comment by enricocid** [comment]
Hi, 3 should be solved now 

https://github.com/enricocid/Music-Player-GO/commit/4270b0bafffbf2534584470a51ef0d9cf06faef3

Let me know once You have received the update :)

**Comment by enricocid** [comment]
@RickyM7 

Here is a test
https://drive.google.com/file/d/1OfncVZja16VBC_jeNg5i0SXYNUhiMJIo/view?usp=sharing 

(covers option could be buggy, i'm testing a new way to retrieve them)

**Comment by RickyM7** [comment]
@enricocid It seems that everything is working fine in relation to hiding songs, albums and folders.
Just like you said, the option to show covers is not working.
Another bug is that when the "Song visualization" option is in "filename", the file name is only shown inside folders and albums, anywhere else (such as the list of all songs or the queue) is shown the tags of the file.
Another thing worth mentioning is that when we click play randomly, all the songs that will play should go to the queue.
I'll add these last two items to the issue so that it's more organized.

**Comment by enricocid** [comment]
> @enricocid It seems that everything is working fine in relation to hiding songs, albums and folders.
> Just like you said, the option to show covers is not working.
> Another bug is that when the "Song visualization" option is in "filename", the file name is only shown inside folders and albums, anywhere else (such as the list of all songs or the queue) is shown the tags of the file.
> Another thing worth mentioning is that when we click play randomly, all the songs that will play should go to the queue.
> I'll add these last two items and other bug to the issue so that it's more organized.

Thanks, I'm gonna fix visualization issues.

About shuffle: this is intentional. It would be very difficult to handle a list with thousand of items. 
For example I have 4000+ songs. A queue with 4000 shuffled songs ...

I can extend this limit If you want. It is actually 30. I can extend it to 50 or 75 or 100.

**Comment by RickyM7** [comment]
> About shuffle: this is intentional. It would be very difficult to handle a list with thousand of items.
For example I have 4000+ songs. A queue with 4000 shuffled songs ...

Wow, 4000 is an unusually amount. But for these limit things, it's always good to have options for that rather than something predefined. For example, it would be useful to have options for:
- Modify the limit freely and this option would have a message somewhere recommending the use of a value ≤100 to avoid problems.
- An option to add or not the shuffle sounds to the queue. This option would also have a message somewhere warning you not to use this if you have many songs (more than 200).

**Comment by enricocid** [comment]
> > About shuffle: this is intentional. It would be very difficult to handle a list with thousand of items.
> > For example I have 4000+ songs. A queue with 4000 shuffled songs ...
> 
> Wow, 4000 is an Insane amount.
> 
> > I can extend this limit If you want. It is actually 30. I can extend it to 50 or 75 or 100.
> 
> For these limit things, it's always good to have options for that rather than something predefined.
> For example, it would be useful to have options for:
> 
> * Modify the limit freely and this option would have a message somewhere recommending the use of a value ≤100 to avoid problems.
> * An option to add or not the shuffle sounds to the queue. This option would also have a message somewhere warning you not to use this if you have many songs (more than 200).

About covers: can You tr this?

https://drive.google.com/file/d/1QxzpPFdpeXxk1SBv1Gxckv6MDNH7wdQ1/view?usp=sharing

:)

**Comment by RickyM7** [comment]
>About covers: can You tr this?
>
>https://drive.google.com/file/d/1QxzpPFdpeXxk1SBv1Gxckv6MDNH7wdQ1/view?usp=sharing

@enricocid The covers are working perfectly on my phone with this apk.

**Comment by enricocid** [comment]
3 is solved, but no option to show/hide file's extension will be added :)

**Comment by enricocid** [comment]
5 I decided to not add duplicates to queue since it is causing issues at the moment when it comes to skip. :) Gonna improve queue later

**Comment by RickyM7** [comment]
> 3 is solved
Thank you.

 >...no option to show/hide file's extension will be added

That's a shame, but no problem.

**Comment by RickyM7** [comment]
> -Modify the limit freely and this option would have a message somewhere recommending the use of a value ≤100 to avoid problems.

> -An option to add or not the shuffle sounds to the queue. This option would also have a message somewhere warning you not to use this if you have many songs (more than 200).

@enricocid Any chances for these options to be added? If the answer is yes I'll add them to the issue.

**Comment by enricocid** [comment]
> > -Modify the limit freely and this option would have a message somewhere recommending the use of a value ≤100 to avoid problems.
> 
> > -An option to add or not the shuffle sounds to the queue. This option would also have a message somewhere warning you not to use this if you have many songs (more than 200).
> 
> @enricocid Any chances for these options to be added? If the answer is yes I'll add them to the issue.

Next versions for sure :)

**Comment by RickyM7** [comment]
@enricocid Point "10." added.

**Comment by enricocid** [comment]
Queue is now saved and restored 😉

**Comment by repparw** [comment]
+1 to Point 8, especially showing currently playing song when pressing queue button instead of showing start.
It's hard to implement it? It would really help with big queues

**Comment by enricocid** [comment]
"Showing the song playing when opening the queue (the queue would scroll directly to the song that is currently playing)"

This one has already been added

**Comment by repparw** [comment]
Is it a setting? At last release on F-Droid it doesnt seem to do it. It's marked with the accent color but if it's down on the queue I have to scroll until I see it

**Comment by enricocid** [comment]
Try this
https://drive.google.com/file/d/1gZw1gwJn8MaW-hXoxuFWdfRpu1Lta1xO/view?usp=sharing

This is the best I can do. Layout manager/scrollToPosition is a bitc... :)

**Comment by repparw** [comment]
![output](https://user-images.githubusercontent.com/45952970/144929865-be2c7918-89a1-4435-b2d0-cddaeaa36017.gif)
Doesn't seem to change anything, when I press queue button it shows start, then I scroll manually to find currently playing

**Comment by enricocid** [comment]
Weird, Android version?

**Comment by enricocid** [comment]
@repparw 
try this
https://drive.google.com/file/d/1gvpskeoIHOliyHBInBq0w604H_hB8vKP/view?usp=sharing

**Comment by repparw** [comment]
Sorry I was asleep
That works!!
(Android 11)

**Comment by enricocid** [comment]
No problem 
Thanks 😊👍🏻

**Comment by enricocid** [comment]
Closing as the thread does not adhere to currently used template (i.e. one feature per issue)
