### ISSUE TITLE
[Feature request] Add buttons to step forward and backward within a song for 10 or 30 seconds

### ISSUE THREAD

**Issue by pippolia** [enricocid/Music-Player-GO#224]
Hello,
very nice app, now I use it daily, but only for listening to music.
For listening to downloaded podcast, I use Google podcasts only because it has a nice feature: you can go forward or backward within a file for 10/30 seconds which is very useful when I miss a part of the conversation or want to skip parts.
If you have time, please add this feature!
Cheers!

**Comment by enricocid** [comment]
I added this feature 2 days ago 😉

You will be able to fast seek by long tapping the skip buttons. The seeking step is customizable from the options (you will be able to choose @ value between 5-60s)
https://github.com/enricocid/Music-Player-GO/commit/45edf7697581d854bea329207887804c8c333ea9

It will be available in the upcoming update 👍🏻

Closing.

**Comment by pippolia** [comment]
Will it work in the notification controls too?

**Comment by enricocid** [comment]
> Will it work in the notification controls too?
> 

Unfortunately not.
There's no more room for actions. All I can do is to add an option to edit available actions. If you think this is a good deal I can work on it for the next update 👍🏻😉

**Comment by RickyM7** [comment]
@enricocid Sorry for the intrusion, but I think this would be an interesting alternative and would make the app more customizable, which is great.

**Comment by enricocid** [comment]
> @enricocid Sorry for the intrusion, but I think this would be an interesting alternative and would make the app more customizable, which is great.

You're welcome :)
I'm already working on this option :)

![image](https://user-images.githubusercontent.com/7274841/97988395-30e19480-1ddd-11eb-86d7-b38e08300d53.png)

**Comment by RickyM7** [comment]
Nice. I can't wait for the next update. One more thing, I saw that because of the new functions the app has new strings, so before posting the new update, please update the strings on weblate and wait about 2 or 3 days, I think this is enough time for at least some translators to translate the new strings to their respective languages.

**Comment by enricocid** [comment]
Absolutely :)

**Comment by enricocid** [comment]
@pippolia @RickyM7 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/7274841/97993540-7ce40780-1de4-11eb-8cb4-a6735c4d2533.gif)

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks

**Comment by pippolia** [comment]
Happy to donate some money, but please send me his paypal account, because as I know gofundme takes 5% or more as a service fee, no?

**Comment by enricocid** [comment]
> Happy to donate some money, but please send me his paypal account, because as I know gofundme takes 5% or more as a service fee, no?


https://www.paypal.com/donate?hosted_button_id=T77AR6TDFCJQW&source=url

I don't know as I used PayPal to donate to him 

😉
