### ISSUE TITLE
why do i get error when i change the package name?

### ISSUE THREAD

**Issue by freedomshare** [enricocid/Music-Player-GO#228]
why do i get error when i change the package name?

when i change package name fragments gets all messed up with error why?

**Comment by Amanthrai** [comment]
> why do i get error when i change the package name?
> 
> when i change package name fragments gets all messed up with error why?

what error u exactly getting?

**Comment by freedomshare** [comment]
I fixed it I just had to click import on the lines that had errors,


But I have two more questions 
1.on light mode where can I change the text color from black?
2.where can I change text size to bold for song list? 
If you dont mine what file and line for these would be great nice code.

**Comment by Amanthrai** [comment]
> I fixed it I just had to click import on the lines that had errors,
> 
> But I have two more questions
> 1.on light mode where can I change the text color from black?
> 2.where can I change text size to bold for song list?
> If you dont mine what file and line for these would be great nice code.

for color u may need to look out in  `values` folders and know which styles and themes are applied and for making text size bold for song list u may need to checkout `res/layout/music_item.xml` file.

**Comment by enricocid** [comment]
> why do i get error when i change the package name?
> 
> when i change package name fragments gets all messed up with error why?

View binding. You need to update build.gradle (app) too and fix the imports.
For text color just check the layouts (?android:attr/textColorPrimary is applied)
To change the RecyclerView items appearance just check all the layouts ending with _item

**Comment by freedomshare** [comment]
Ok thank you
