### ISSUE TITLE
Can't switch tab if DetailsFragment is open

### ISSUE THREAD

**Issue by Drhaal** [enricocid/Music-Player-GO#229]
When I open a music folder, like albums lists, in the artist tab i can't switch tab anymore. 
Ex: if I'm seeing all the albums for an artist and want to move to the "all songs tab". I must manually pres the back button to return to the main "album tab". And then I can click on the "all songs" tab icon.
Before i was able to switch by clicking on the tab icon.
This happen on whenever i select anything on:
- artists tab 
- album tab
- folder tab

I think it's a problem with the DetailsFragment

**Comment by Drhaal** [comment]
The same problem seems also present when opening the equalizer

**Comment by enricocid** [comment]
Closing. Thanks :)
