### ISSUE TITLE
Audio focus 

### ISSUE THREAD

**Issue by neekless** [enricocid/Music-Player-GO#232]
When using the play/pause button at the bottom controls, audio focus management works, i.e. When I press the play button at the bottom, my Spotify pauses.

However when I play a song directly from the list (artists, albums, or songs), it doesn't pause my Spotify, so both sources will be playing together.

Android 11, pixel 2xl
MPG 4.3.2 f-droid version

**Comment by enricocid** [comment]
Thanks for reporting! 👍🏻

**Comment by enricocid** [comment]
This one has been fixed. Reopen the issue if You still have problems with the next update ;)
