### ISSUE TITLE
[FR] choosing global sorting method and multiple discs albums

### ISSUE THREAD

**Issue by CaseOf** [enricocid/Music-Player-GO#233]
Hello,
Is it possible to get an option to set sorting method globally in the app?
Also sorting by track numbers does not hanble albums that contains multiple discs (with each disc track starting by 1). Is it possible to support them?
Thanks for the great work you already did!

**Comment by enricocid** [comment]
Fixed by 40a2a04f3deb568578dcedbc1eee3ebd902026e7
