### ISSUE TITLE
Reset default volume when preciseVolume is disabled

### ISSUE THREAD

**Issue by Drhaal** [enricocid/Music-Player-GO#235]
When the preciseVolume is disabled from the setting menu we keep the user set volume.

The user could forget that it lowered  the volume before disabling preciseVolume and get stuck with a low volume.

**Comment by Drhaal** [comment]
If you think this feature is useful i can start implementing it

**Comment by enricocid** [comment]
Nice, it would be great :)

**Comment by enricocid** [comment]
Closing ... thanks :)
