### ISSUE TITLE
Crashes on Android 10

### ISSUE THREAD

**Issue by aikencz** [enricocid/Music-Player-GO#236]
### Steps to reproduce
1. Install Music Player Go via F-Droid.
2. Run the program.

### Expected behavior
The program successfully starts and works.

### Actual behavior
The program crashes after start.

### Affected versions
4.3.x (up to 4.3.3 which is currently the newest available)

### Environment
Device: Samsung Galaxy A40
System: Android 10, build QP1A.190711.020.A405FNXXS3BTI3
Kernel: 4.4.177-18598463

**Comment by enricocid** [comment]
I'm currently not able to reproduce as I only have devices running vanilla Android (android one, nexus ...).

I need a logcat

To register a logcat just enable the developer options on your device and adb debugging

Download platform tools

https://developer.android.com/studio/releases/platform-tools

Extract it and open a terminal inside the resulting folder

Then type

adb logcat -v long > mpgo.txt

and reproduce the issue. Once finished press ctrl+c and send me the mpgo.txt file you find in the folder.


Alternatively you can capture a bug report using this method

https://developer.android.com/studio/debug/bug-report#bugreportdevice
Once finished just share the result with me via email together with the android version and the phone model (to see if it is a device specific issue online).

Thanks

**Comment by enricocid** [comment]
Hi

Could You try this one?

https://drive.google.com/file/d/1yB8StzqM23X5h-tZh8kdd6VWjl1JHudb/view?usp=sharing

**Comment by enricocid** [comment]
Hi, I have updated the apk visibility on gdrive

please let me know

https://drive.google.com/file/d/1yB8StzqM23X5h-tZh8kdd6VWjl1JHudb/view?usp=sharing

**Comment by aikencz** [comment]
Hi, this one works well, thanks.

**Comment by enricocid** [comment]
Hi,
could You please try this one?

It's a release build. It can differ from the debug one. Thanks

https://drive.google.com/file/d/1FzuCfi-Y6UJgvu3qJlxVmobxKwR6kGMt/view?usp=sharing

**Comment by aikencz** [comment]
Hi, it works too.

**Comment by enricocid** [comment]
Hi,
I've release 4.3.4 version.
https://github.com/enricocid/Music-Player-GO/releases/tag/v4.3.4

Let me know if the issues are solved. If yes, You can close this issue :)

**Comment by aikencz** [comment]
Hi, it works well, good work, thank you. I'm closing the issue.
