### ISSUE TITLE
[FR] Un po' di suggerimenti 

### ISSUE THREAD

**Issue by Giulio1123** [enricocid/Music-Player-GO#237]
Ciao, innanzitutto volevo congratularmi per l'ottimo lavoro svolto, l'applicazione è fantastica e minimale al punto giusto, ma avrei alcuni suggerimenti per possibili miglioramenti futuri:

- [x] Poter aggiungere un intero album in coda senza dover aggiungere singolarmente ogni canzone.
- [ ] Ho visto già un commento che parlava di questo, ma apprezzerei molto la possibilità di cambiare canzone dalle cuffie e volevo sapere se era possibile aggiungerla o no.
- [ ] Far funzionare la lista dei preferiti come lista di canzoni a se stante: quanto riproduco una canzone dai preferiti non mi riproduce la successiva canzone preferita ma la canzone successiva nell'album della prima (spero di essermi spiegato bene).
- [x] Aggiungere più colori per l'accento, includendo i colori pastello nella modalità chiara e quelli non pastello nella modalità scura.

**Comment by enricocid** [comment]
Ciao, grazie.

1. Si, pensavo di metterla nel prossimo update
2. Indagherò (purtroppo non ho tanti dispositivi ed è un po' come andare alla cieca)
3. Ok, penso ce la potrei fare per il prossimo update
4. In realtà non sono colori pastello, ma gli stessi colori del tema chiaro però desaturati per l'accessibilità 💯

**Comment by Giulio1123** [comment]
Fantastico, grazie mille per la veloce risposta! Per caso hai già un'idea di quando uscirà l'aggiornamento?

**Comment by enricocid** [comment]
> Fantastico, grazie mille per la veloce risposta! Per caso hai già un'idea di quando uscirà l'aggiornamento?

Non saprei, questa settimana sono abbastanza impegnato. Spero per il fine settimana :)

**Comment by Giulio1123** [comment]
Ottimo, grazie ancora!

**Comment by enricocid** [comment]
Ciao, ti confermo che ho implementato la 1 e la 3. Qualche ritocco e lo invio a questo repository e sarà disponibile nel prossimo update.
Potrei anche postare un apk qui per chiederti di testarlo, se non ti dispiace :)
La 3 funziona cosi: quando riproduci una canzone dalla lista delle canzoni preferite, l'intera lista verrà aggiunta alla coda (è più facile cosi che implementare da zero un gestore della lista delle canzoni preferite :) )

**Comment by Giulio1123** [comment]
Volentieri, posta pure l'apk, poi ti faccio sapere. La lista aggiunta alla coda è un'ottima idea👍🏻

**Comment by enricocid** [comment]
Eccolo qui, grazie :)

https://drive.google.com/file/d/1WM87SL3NOGTPJp5alYiTMhl3TfCCRZXV/view?usp=sharing

E' un apk debug quindi devi prima togliere quella messa dallo store :)

**Comment by Giulio1123** [comment]
Ciao, ho provato l'apk negli scorsi due giorni e devo dire che funziona alla grande, soprattutto la funzione che permette di inserire gli interi album in coda. Per quanto riguarda la lista dei preferiti: funziona bene, ma sarebbe bello poterla riprodurre casualmente. In ogni caso ottimo lavoro per ora!

**Comment by enricocid** [comment]
Ho aggiunto più colori, saranno disponibili nella prossima versione. :)

**Comment by enricocid** [comment]
Closing as the thread does not adhere to currently used template (i.e. one feature per issue)
