### ISSUE TITLE
Unresolved reference: isR

### ISSUE THREAD

**Issue by LossyDragon** [enricocid/Music-Player-GO#239]
Hi, 

I saw some updates today and thought to try it out. 

It looks like isR() was never pushed in VersioningHelper when [this](https://github.com/enricocid/Music-Player-GO/commit/4411f4b90c1d64ba33ab1fc81ac3759943f89b2d#diff-d292a0947cd5f142f749ce1b10947e756c85c24354db1877a7cbf6afae7a4b86R98) was added. :)

**Comment by enricocid** [comment]
Thanks!
