### ISSUE TITLE
Saving/restore progress

### ISSUE THREAD

**Issue by ghost** [enricocid/Music-Player-GO#24]
After i close the app in the background using the recent apps, when i open it again there's no song selected for me to resume playing. I need to start again and remember where i was.

This is useful when listening to long podcasts in short commutes.

PS: Wonderful player. Android needs more clean and minimal apps like yours. Thanks!

**Comment by enricocid** [comment]
Thanks!
Can You please share info about android version and device? thanks

**Comment by h0ttentot** [comment]
It's a Moto G3 (2015) with Lineage OS 14.1 (Android 7.1.2).

**Comment by enricocid** [comment]
Ok. This happens when you pause playing and you remove the app from recents. This is the normal behaviour of the player since actually there's no method to save last played song/progress. I will mark this issue as a feature request

**Comment by h0ttentot** [comment]
Yes. So, for it to not happen i just need to keep it in recent apps?

Just a question because i'm new to github. When you mark it as feature request it means you'll implement it or it's just a reminder?

**Comment by sign-out** [comment]
Up vote

**Comment by enricocid** [comment]
This one has been implemented. Song and its last position will be restored. Actually under test, it will be available as soon as possible.

**Comment by enricocid** [comment]
Just to confirm that this feature will be available in 4.0.0 I'm about to release within these days. Moreover you can bookmark song and a particular progress to loved songs.
