### ISSUE TITLE
Use audio compat classes in MediaPlayerHolder

### ISSUE THREAD

**Issue by TacoTheDank** [enricocid/Music-Player-GO#247]
In MediaPlayerHolder, you don't have to do an SDK version check for [this](https://github.com/enricocid/Music-Player-GO/blob/main/project/app/src/main/java/com/iven/musicplayergo/player/MediaPlayerHolder.kt#L348) or [this](https://github.com/enricocid/Music-Player-GO/blob/main/project/app/src/main/java/com/iven/musicplayergo/player/MediaPlayerHolder.kt#L371). You can use AudioFocusRequestCompat, AudioManagerCompat, and AudioAttributesCompat, which will do the SDK version checks internally.
(The only thing is that setAcceptsDelayedFocusGain doesn't exist in the compat class, but that won't matter as it's also set automatically.)

Also, I may be wrong about how it's currently working, but I think the audiofocusrequest should be moved to the initMediaPlayer method (or whatever the running method is). Here is an example of what I mean: https://github.com/AntennaPod/AntennaPod/pull/4592

**Comment by enricocid** [comment]
Thanks for letting me know, that would be a great improvement 👍🏻😎

**Comment by enricocid** [comment]
Hi,

please check this change. In my tests it works great (android 10 and android 7.1)

https://github.com/enricocid/Music-Player-GO/commit/63c009c50d23d1a05e95b4f46f13b05c45222e05

Let me know if it is ok

**Comment by enricocid** [comment]
This one has been added. Closing :)

**Comment by TacoTheDank** [comment]
@enricocid Think it's good!

**Comment by TacoTheDank** [comment]
@enricocid What I'm seeing though in a lot of the recent commits though is a lot of noise from changed spacing. I will make a pull request to fix this issue.

**Comment by enricocid** [comment]
> @enricocid What I'm seeing though in a lot of the recent commits though is a lot of noise from changed spacing. I will make a pull request to fix this issue.

Yeah, this is because I'm using Android Studio refactoring... I don't know why every time it changes spacing (in 3.x I have never experienced this issue) :)
