### ISSUE TITLE
Queue bug?

### ISSUE THREAD

**Issue by MGislv** [enricocid/Music-Player-GO#249]
After I listened to the 7th track from an album, instead of playing the remaining tracks in order it played the first

**Comment by enricocid** [comment]
Yes, this is probably a bug in the skip function. Gonna investigate and fix asap!
Thanks for the report :)

**Comment by enricocid** [comment]
Hi, I'm investigating this issue right now.
Could you please share details on how to reproduce? Thanks :)

**Comment by MGislv** [comment]
I've tried for half an hour but still can't reproduce, if It happens again I'll report back as soon as I can

**Comment by MGislv** [comment]
Btw if it helps I remember having my screen turned off with energy saving enabled. (Redmi 7a, Android 10)

**Comment by enricocid** [comment]
> Btw if it helps I remember having my screen turned off with energy saving enabled. (Redmi 7a, Android 10)

Xiaomi and other manufacturers are very aggressive when it comes to battery management. Services might be affected. Thanks for the info :)

**Comment by MGislv** [comment]
It happened again, this time I played the album by pressing the cover from the artist view, and listened to half of it (then closed the app). Afterwards I resumed where I had left, in the middle of a track, it played all the remaining songs but instead of saying

**Comment by MGislv** [comment]
Sorry I'm from mobile and I pressed the wrong button.. Btw here's what appened:
I resumed playing an album I left hours ago, once I pressed play after opening the app it rightfully resumed from the exact point where I stopped it. After finishing the tracklist, instead of saying "list ended" it played the fifth track again (which is the one I was listening to when I first closed the app)

**Comment by enricocid** [comment]
> Sorry I'm from mobile and I pressed the wrong button.. Btw here's what appened:
> I resumed playing an album I left hours ago, once I pressed play after opening the app it rightfully resumed from the exact point where I stopped it. After finishing the tracklist, instead of saying "list ended" it played the fifth track again (which is the one I was listening to when I first closed the app)

No problem :) 

There were bugs in the latest releases. I'm releasing a new version within the next hour. Let me know if the problem persist :)

If You want You can download debug versions here

https://github.com/enricocid/Music-Player-GO/actions

Just click on the latest build and get the apk. You can install it without removing the stores version :)

**Comment by enricocid** [comment]
I have changed the way next/prev songs are being retrieved. Let me know if the problem persists once the new version will be online. :)

**Comment by MGislv** [comment]
So I downloaded the last build from Actions and tested it, unfortunately it's not really fixed. To reproduce the bug: play a song from a random album (anything but the last track) and kill the app from the settings to replicate what MIUI does, at witch point, when pressing play on the track again and letting it finish it's going to start from the beginning of the album rather than going on with the list. Hope it'll be possible to reproduce

**Comment by enricocid** [comment]
This issue should be fixed in latest release (4.4.7). Closing.

If the problem still persists please reopen the issue 😉

**Comment by MGislv** [comment]
Works great!
