### ISSUE TITLE
GitHub Actions/Enable CI

### ISSUE THREAD

**Issue by RickyM7** [enricocid/Music-Player-GO#254]
It would be amazing if you used GitHub Actions to create debug builds. This would make it much easier to test a new feature and report bugs (of each commit and PR) before the final releases.
PR to use as a reference:

[Florisboard#92](https://github.com/florisboard/florisboard/pull/92)

[NewPipe#5132](https://github.com/TeamNewPipe/NewPipe/pull/5132)

**Comment by enricocid** [comment]
Added 👍🏻

**Comment by RickyM7** [comment]
@enricocid Thank you very much, this will help a lot to test new features and report bugs.
Just one detail, can you change the package name of the debug versions? This will be useful for testing these versions without having to uninstall the normal version.

**Comment by enricocid** [comment]
@RickyM7 I've changed package nane and id. Let me know if it is now ok :)

**Comment by RickyM7** [comment]
@enricocid Everything working perfectly. Thank you again.

**Comment by enricocid** [comment]
@RickyM7 could you try the latest debug apk once built?
There's a bug in the current release with shuffling artist songs. It shuffles only the selected album

I'm pretty sure it is now fixed, please let me know :)

**Comment by RickyM7** [comment]
@enricocid I tested and everything worked perfectly, regardless of whether the artist has many or few albums.

**Comment by RickyM7** [comment]
@enricocid I forgot to mention it but you can call me whenever you need to test something in the app. I'll test whenever I can and as soon as I can.

**Comment by enricocid** [comment]
> @enricocid I forgot to mention it but you can call me whenever you need to test something in the app. I'll test whenever I can and as soon as I can.

Thanks :) I need to know if focus works well and if the app does not crash when removed from recents (you can try to play something, pause and then remove the app from recents) :)

**Comment by RickyM7** [comment]
> I need to know if focus works well and if the app does not crash when removed from recents (you can try to play something, pause and then remove the app from recents) :)

@enricocid Sorry for the delay, it happened that my internet simply stopped for a while. What did you want to know, "focus" would be "audio focus"? If so, then this is working perfectly on the last debug version. And no crash occurs when removing the app from recents.

**Comment by enricocid** [comment]
> > I need to know if focus works well and if the app does not crash when removed from recents (you can try to play something, pause and then remove the app from recents) :)
> 
> @enricocid Sorry for the delay, it happened that my internet simply stopped for a while. What did you want to know, "focus" would be "audio focus"? If so, then this is working perfectly on the last debug version. And no crash occurs when removing the app from recents.

Yes, there was a bug with audio focus 👍🏻 thanks 😎
