### ISSUE TITLE
gotta reboot to add new song

### ISSUE THREAD

**Issue by disdaogitacc** [enricocid/Music-Player-GO#255]
my device: lg g4 with non-rooted nougat(7.0) 

cheers

**Comment by enricocid** [comment]
Unfortunately it does not depend on me. :) 

I'm following the official guidelines

https://developer.android.com/training/data-storage/shared/media

I'm experiencing the same issue sometimes.

It depends on Android's MediaStore and the time needed to update its entries. 

I can only query this database.

The same problem happens with other Music Players querying MediaStore to get songs list (like Phonograph for example)
