### ISSUE TITLE
[FR] Playback speed control

### ISSUE THREAD

**Issue by Fraifrai** [enricocid/Music-Player-GO#261]
Hello,

I'm french, sorry for my poor english :)

I migrated from VLC Mobile to Music Player Go because VLC often sets my device unstable.

Music Player GO but lacks a key feature : The playback speed control

Do you plan to implement this ?

Thx in advance

**Comment by enricocid** [comment]
I think it should be easy to implement, anyway I'm looking at the MediaPlayer docs and it seems that playback speed works only from Android M and above.
What are the options You would like to see?

**Comment by Fraifrai** [comment]
Hi,

Here's a page that describe this power-feature of VLC Mobile : https://www.vlchelp.com/android-app-play-video-audio-slow-fast/

**Comment by enricocid** [comment]
Hi, 

just added the feature.
You can test it if You want

Just download the apk from here when then build is finished :)
https://github.com/enricocid/Music-Player-GO/actions/runs/538353919

**Comment by Fraifrai** [comment]
Excellent it works better tha, the VLC implémentation !!! You can proudly merge the corresponding branch !!!!

**Comment by Fraifrai** [comment]
Great job. When will this feature available in the F-droid repository ?

**Comment by enricocid** [comment]
> Great job. When will this feature available in the F-droid repository ?

I will release a new version probably the next week. I'm not sure anyway when it will be built by F-droid system.. maybe one or two weeks since the release 😆

**Comment by Fraifrai** [comment]
YEAH !!!! it's available in F-DROID !!!! THX again !!!
