### ISSUE TITLE
[FR] Bigger nav buttons, grid view, better artist card and choose player buttons with other "time" bar

### ISSUE THREAD

**Issue by dev1anceONE** [enricocid/Music-Player-GO#264]
Hello. Would it be possible to

- [x] Make navigation buttons bigger? 
- [ ] Grid view, an artist card with a photo or an album art you listened recently (same with Album card)? 
- [ ] Add a selection of play buttons 
- [x] Another time bar (more like Apple Music)?

**Comment by enricocid** [comment]
How is Apple music seekbar? :)

**Comment by dev1anceONE** [comment]
Here u have Photo of seekbar https://i.imgur.com/XW1HgoD.jpg

**Comment by TheOtherDoctor** [comment]
So you mean to have a horizontal time scroller which is bigger and can be used to slide song position directly in the default view? Oh yes please.
 
As I understand the current thin one in the default view in not interactive at all and acts just as a progress indicator - as long it is visible at all - for me it disappears entirely in landscape mode.

The larger progress bar in the song focus window (coming after tapping on the now-playing song) is IMHO fine for control of song position, but always takes that extra tap onto the song. Would be fine for me to have that one in the top level view.

**Comment by TheOtherDoctor** [comment]
About the original comment on navigation buttons - you mean the fwd/rev buttons in the song focus view, left and right of the pause button?
In that currently-playview view I generally wonder why it uses only about half of the screen height. It cannot be dragged further up, and no interaction with the remaining view on the greyed-out list view underneath is possible.
Thus, to support this feature suggestion, I'd dare to go further and propose to change this whole view into a full-screen one with car-audio-capable fat buttons. ;-)

**Comment by enricocid** [comment]
Closing as the thread does not adhere to currently used template (i.e. one feature per issue)
