### ISSUE TITLE
[BUG] fdroid download fails since version 4.3.7 on old system (stock android 6)

### ISSUE THREAD

**Issue by TheOtherDoctor** [enricocid/Music-Player-GO#268]
I am aware that you likely cannot do much about this, but I just wanted to make it transparent which OS versions are supported as fDroid might be handling this suboptimal.

Reproduce:
When I tap the "update" button in fdroid (v1.10), I get like (reverse translation) "The requested file could not be found. https://f-droid.org/repo/com.iven.musicplayergo_159.apk"
This is not a temporary issue, I tried several time over some days.

This happens for me for older Android 6.0 (stock ROM) , while the download is fine on a AOSP 10 based Lineage OS (got to 4.4.0), and it works also fine on AOSP based Lineage Device.

Is the app expected to still compile/build for something as old as Android 6? 
Understandable if that is actually no longer supported, but then it would be better if fdroid would not announce it, get stuck and fail.

As I expect this to be at least partially an fDroid issue, I added similar info in their tracker also, hopefully not bothering too many with my old-device-problems.

**Comment by enricocid** [comment]
Exactly, I can't do much @IzzySoft @Poussinou 

Anyway, You can still download older versions from [**releases**](https://github.com/enricocid/Music-Player-GO/releases); since they have a different signature You can't install them on top of f-droid ones.

Closing ...

**Comment by IzzySoft** [comment]
> When I tap the "update" button in fdroid (v1.10), I get like (reverse translation) "The requested file could not be found. https://f-droid.org/repo/com.iven.musicplayergo_159.apk"  
> This is not a temporary issue, I tried several time over some days.

That is because older versions get archived. Simply enable the "archive" repo in your F-Droid client's settings if you need them, @TheOtherDoctor.

**Comment by TheOtherDoctor** [comment]
Ok, I understand what fDroid does there, they also [mentioned](https://gitlab.com/fdroid/fdroiddata/-/issues/2292) that only 3 versions are kept, and how to activate temporarily to get out of the locked situation. 

What I did not yet understand is why on that device I do not just get the newest version offered for update, but instead it tries to point me to that one which is archived and thus no longer available without extra action by user. Yet I was not aware I always have to go through all version steps - which consequently would mean that when I miss to many upgrades for an app, I will always run into the neccessity to go throug the archives to get back to current.

**Comment by IzzySoft** [comment]
@TheOtherDoctor because your index was not updated? Check in *Settings › Repositories › F-Droid* – what date does it give for "Last Update"? More than a week ago? Then your index is out-of-date. Go back to the "Tasks" tab, and pull-to-refresh. Once updating the index was completed, check again: it should no longer offer you the old version.
