### ISSUE TITLE
[FR] do not reset/delete queue when directly starting song playback

### ISSUE THREAD

**Issue by TheOtherDoctor** [enricocid/Music-Player-GO#269]
I like to use the queue to setup the next songs to play, this is a great feature which supports my preferred usage a lot.

But often I hold the tap too short to get to the context menu from the song list, then the tapped song gets directly played, the queue is emptied and lost. Tapping on queue icon then only says "no songs queued". This is quite annoying.

Observed in v4.2.7 on Android 6 (cannot upgrade as fDroid upgrade is broken there - see respective issue https://github.com/enricocid/Music-Player-GO/issues/268) - so sorry if this is already fixed in newer version. :-(

This happens so often to me as it is somewhat an inconsistency in my usage flow, especially when running through the artist list: short tap to get into artist's songs list, long tap for menu + queue, short tap to get back to list, short tap to get into other artist, etc.
Would not happen that much if the songs list had an appropriate scroller to get down a long list quickly. ;-)

Thus I propose to just keep the queue untouched when directly starting a song. 
Would be also fine to put the direct-started new song also put into the queue, if the previous app state has been "playing from queue".

**Comment by TheOtherDoctor** [comment]
This is somewhat related to FR no.2 in the feature list given in https://github.com/enricocid/Music-Player-GO/issues/220

**Comment by enricocid** [comment]
Queue is not cleared anymore since 4.4.7 update 😉
Closing. 👍🏻
