### ISSUE TITLE
Bluetooth problems

### ISSUE THREAD

**Issue by beli3ver** [enricocid/Music-Player-GO#27]
Hello,

first of all, thank you for that amazing app.
But I find two issues, maybe you could fix it.

1.) Bluetooth controls
I connect my phone to a headset for running or to my car, when I want to switch I use the controls of my headset or my car, but it didn't work, neither switching or stopping the song

2.) Bluetooth disconnect
When I disconnect my phone from the headset or my car, the music didn't stop, it is still running and cames from my phone speakers now.

Thanks for your work.

**Comment by enricocid** [comment]
Thanks for the report.
I will try to fix once I'll get some bluetooth headset

**Comment by stonerl** [comment]
I'll have a similar problem. 

When I disconnect my BT-Headphones, the music stops playing, so fa so good. But The player doesn't  toggle the playback button.

When I press pause on the BT-Remote, the music stops playing for a second but then continues. Here the same  phenomenon; when the music stops the playback button does not toggle its state.

**Comment by stonerl** [comment]
You added help needed to this issue. How can I help here?

**Comment by enricocid** [comment]
"Help needed" is referred to Android devs who can test the app against Bluetooth devices that I don't have😆
It is very difficult for me to solve issues like this and Android auto related issues so I need help.

**Comment by stonerl** [comment]
I'm no android developer. But as far as I understand you need to add this to your manifest to signal the system that your app handles media button events:

 [MediaButtonReceiver](https://developer.android.com/reference/android/support/v4-media-session/MediaButtonReceiver)

**Comment by WesleySykes** [comment]
I love this app but have been coming across this same issue. I have a bluetooth headset and would love to take a crack at this sometime soon if that would be helpful.

**Comment by enricocid** [comment]
It would be awesome

**Comment by enricocid** [comment]
I'm about to deal with this problem. I'm gonna post test apk later.

**Comment by enricocid** [comment]
I implement MediaButtonReceiver in mpgo, but can't test. 

Test apk:

https://drive.google.com/open?id=19eJfkyYDSkvD_920b9-DE0PJOyjAcJ4P

**Comment by enricocid** [comment]
Hello,

as suggested by @stonerl I implemented media buttons receiver in MPGO 4.0.0. As I can't buy new devices to test, I wrote this small utility that simulates broadcasts MPGO should receive and handle.

https://github.com/enricocid/android-media-buttons-test

I'm about to release MPGO 4.0.0 and gonna close this issue as MPGO is now ready to handle these events.
You can reopen the issue if the problem persists. Thanks
