### ISSUE TITLE
[FR] have fast side scroller in songlist as it is already in artist list 

### ISSUE THREAD

**Issue by TheOtherDoctor** [enricocid/Music-Player-GO#271]
In the artist view, there is that nice alphabetical side scroller for fast navigation, that really contributes a lot to usability for nowadays music archive sizes.

There is not such thing in the songs list, which does not make sense for my, as the song list is always significantly longer as the list of artists, rendering this (otherwise preferred) view unusable for me - scrolling via screen-wise swipe through more than 1000 songs is just not an option from my point of view.

Please "simply" add the same alphabetical side scrolling feature in all lists.

Observed with MPGO versions including 4.4.0 (via fDroid) on AOSP 10 (LineageOS 17).

**Comment by qw123wh** [comment]
@TheOtherDoctor This function is already present, just go to the desired section (album, song ....), click the button at the top right next to the search button, select A-Z or Z-A and the scroller will appear.  You can close this issue.
