### ISSUE TITLE
[BUG] rotating device orientation resets the view tab to top of artists list

### ISSUE THREAD

**Issue by TheOtherDoctor** [enricocid/Music-Player-GO#273]
When having a view tab other than the artist view (leftmost icon/tab) open, when changing device orientation between portrait and landscape, the view jumps back to artist list, focussing at its very top.

This is especially annoying in combination of the missing fast-scroll option in the non-artist views (see FR https://github.com/enricocid/Music-Player-GO/issues/271): when I just swiped down hundreds of screen heights to get to an item in the song list and accidentially the rotation gets triggered, I find myself kicked out.

As a possible workaround, maybe (optionally) disable adapting to orientation entirely for this app.
Disable autorotation system wide is not really a workaround as long as you have other apps for which landscape is a must, as on some OSs disabled autorotation implies forced portrait.   

Observed in MPGO 4.4.0 on AOSP 10 based system (Lineage 17).

**Comment by enricocid** [comment]
Fixed :)

**Comment by landry314** [comment]
absolutely. i want to disable any orientation switch and keep it in portrait mode all the time. otherwise it does weird stuff. and i am lying on my side using it a lot.
