### ISSUE TITLE
[BUG] multi-artist folders/album: artist name is missing in by-album and by-folder list view. wrong association to albums.

### ISSUE THREAD

**Issue by TheOtherDoctor** [enricocid/Music-Player-GO#274]
In the song lists in the by-folder and by-album tabs, the song entries are given as  [track#] - [title] in the first line - the artist is not mentioned.   

I guess the artist name is omitted in the album view because it is assumed that albums have only one artist (which is not the case for compilations), and further assuming each folder contains one album (which I see no reason to assume).
Putting the track number at the start of each entry seems to support that assumption.

Especially folder navigation should have support for multiple artists; 
Having the folder view come as closest as possible to by-filename view might be rated high in the wishlist of users having just a flat directory with 1000s of songfiles (like me).

Consequently I'd suggest to replace the track number in these lists by the artist name, or making the song item display just same as in by-song list view (title - artist - album).  
Sorting in the folder view probably should be by-artist as 1st and by-title as 2nd key. 
For the folder view, just listing the file names (and sorting by filename) might be just as good. 

In the by-album list, the artist seems to be taken from the song item in the list which is first in a by-title sorting. 
For songs with different artists in the album, this information is wrong for this album, and something like "various" should be written below the album name instead.  
In each album's list, maybe sorting by-track 1st (and then by-artist and by-title) makes sense.      

Referring to MPGO 4.4.0 on LineageOS 17 (based on AOSP 10) on a Nexus 6P.

**Comment by enricocid** [comment]
Hi, I have reviewed the way folders work.

Anyway, albums are categorized by artist.
Actually multi-artist is not supported.

Since there are already other issues referencing this issue I'm gonna close this one. Thanks :)
