### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by zuuritaly** [enricocid/Music-Player-GO#28]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Zuur

Graphic Designer**

**Comment by enricocid** [comment]
Thanks, but I'm ok with actual icon. I think Julian did a great work.
Thank You anyway;

**Comment by dharmapoudel** [comment]
I'm not really fan of current logo. So I would suggest in favor of changing it.
