### ISSUE TITLE
[FR] Hide volume slider when PVM disabled

### ISSUE THREAD

**Issue by Drhaal** [enricocid/Music-Player-GO#280]
I think hiding the precise volume slider when the option to control it is disabled would be a good idea. 
It would de-clutter the interface a little bit, since when PVM is disabled the volume is always at 100% it does not provide any useful information

**Comment by Drhaal** [comment]
thanks :)

**Comment by Drhaal** [comment]
Following on this I think you should also remove the button to open the current song from the NowPlaying dialog and replace it with a click listener on the song title + illustration. 
Most players also do this so it should not disrupt the user and it would help the user focus

**Comment by enricocid** [comment]
> Following on this I think you should also remove the button to open the current song from the NowPlaying dialog and replace it with a click listener on the song title + illustration.
> Most players also do this so it should not disrupt the user and it would help the user focus

I'll do that :) Thanks :)
