### ISSUE TITLE
[FR] Visual indicator when opening song's album

### ISSUE THREAD

**Issue by Drhaal** [enricocid/Music-Player-GO#282]
When pressing on the open button from the nowPlaying dialog we are only take to the song location. 
Focusing the list on the playing song + adding a little animation to the song would make it easier to find if the album has a lot of song (and really useful on the all music tab).

I can start preparing a merge request for this if you want

**Comment by enricocid** [comment]
> I can start preparing a merge request for this if you want

Ok, I will wait Your PR then :)

**Comment by Drhaal** [comment]
Nice to know, I got a lot of things going on right now so I'm not sure when I will be able to to do this.
But I'll try to work on it when I have some time off

**Comment by enricocid** [comment]
This one is aready fixed. Closing. :)
