### ISSUE TITLE
Library folder selection

### ISSUE THREAD

**Issue by vishvjeet79** [enricocid/Music-Player-GO#285]
Add an option to exclude folders in the library for music scan.

**Comment by jolle22** [comment]
I would love this feature as well.
Currently some voice notes from messangers are played when I randomly play all tracks with 
Music-Player-GO on my smartphone 😓

**Comment by Psyhackological** [comment]
This feature is the only feature I miss in this app. Absolutely gorgeous work. 🖤

**Comment by enricocid** [comment]
You can hide them from folders tab.

**Comment by thibaultmol** [comment]
had to find this issue to figure it out (was searching to see if anyone had made a FR about this).
Maybe it's just me, but this isn't very UX friendly, just letting you know

**Comment by enricocid** [comment]
I'm focusing on a new music player that will replace mpgo in the near future. It will feature a new & modern architecture and it will be easier to maintain and add new features. 

I'm gonna address most of the issues/suggestions (playlists, folder selection, etc.) collected here. 😉

![Screenshot_2024-07-25-08-49-10-404_com.pino.myapplication.jpg](https://github.com/user-attachments/assets/2c112c95-b875-4b05-9436-6abcb24fea1c)

**Comment by Psyhackological** [comment]
@enricocid that's great to hear! Maybe add a small hint about this, like [NewPipe did](https://github.com/TeamNewPipe/NewPipe?tab=readme-ov-file#we-are-planning-to-rewrite-large-chunks-of-the-codebase-to-bring-about-a-new-modern-and-stable-newpipe).

> We are planning to rewrite large chunks of the codebase, to bring about https://github.com/TeamNewPipe/NewPipe/discussions/10118!
Please do not open pull requests for new features now, only bugfix PRs will be accepted.

**Comment by enricocid** [comment]
Absolutely. Gonna post an announcement+ roadmap very soon. 😉
