### ISSUE TITLE
Implement landscape layout

### ISSUE THREAD

**Issue by phuyuk** [enricocid/Music-Player-GO#29]
Ok, I'll be the one to ask: Is landscape mode in the cards? I love this app, but it hurts my neck to use it ;-)

**Comment by enricocid** [comment]
Yes, I will implement it asap!

**Comment by Wilker-a** [comment]
hi :3

i think it would be good to make it so all the controls can be done with one hand, just like in portrait. that said, it would be good to make left-handed controls an option, i.e an option to choose which side to put the controls on.

thank you for reading \^-\^

**Comment by enricocid** [comment]
That's a build with landscape mode enabled. I  don't have a tablet so i'm "blind"
https://drive.google.com/open?id=1VRDE2CXjTa6359OUFM5jYjAKQSwhvS5Q

**Comment by enricocid** [comment]
[Music-Player-GO-master source with land](https://github.com/enricocid/Music-Player-GO/files/3530002/Music-Player-GO-master-land.zip)

**Comment by Wilker-a** [comment]
i looked at the one with the Google Drive link. i believe that i have a better idea for the landscape layout, so i tried to make a sketch of it.

![a sketch image of a possible landscape layout](https://user-images.githubusercontent.com/10854855/63513765-9b5b2d00-c4d6-11e9-883f-8c88cd1f35cf.png)
the idea is that the layout should be operational for all functions with one hand, and the side where all the controls sit should be an option for the user to choose.

**Comment by enricocid** [comment]
Nice, gonna try to impl this

**Comment by enricocid** [comment]
Land layout has been added (the suggested solution was not possible and required too much changes, tho). It will be release with the upcoming version and improved following users suggestions (unfortunately my device has a small screen and can't emulate with my pc) in next updates. You can open a new issue (once 4.0.0 has been released) if You have any suggestion.
