### ISSUE TITLE
Add opus file support

### ISSUE THREAD

**Issue by LoveChocoCat** [enricocid/Music-Player-GO#292]
1) **Describe the solution you'd like**
- i want this app to be able to play opus file

2) **Describe alternatives you've considered**
If integrating the codec for opus is difficult, you can make addon like what MiX explorer do.

**Comment by OxygenCobalt** [comment]
I don't think the android media player supports Opus [Yet]. You might want to try another player that uses ExoPlayer or something similar.

**Comment by LoveChocoCat** [comment]
Yeah, there is something else going on. It might be something that involved mime type thingy on Android.
