### ISSUE TITLE
[FR] Feature to create and add to playlists

### ISSUE THREAD

**Issue by CymBIOseD** [enricocid/Music-Player-GO#293]
It'd be handy to create playlists and add songs to them.

**Comment by enricocid** [comment]
I will add playlists in next updates 👍🏻😉

**Comment by CymBIOseD** [comment]
awesome thanks a lot 😁 love the app btw keep up the great work 🤘

Op zo 2 mei 2021 09:21 schreef enricocid ***@***.***>:

**Comment by enricocid** [comment]
Closed as there's already an issue opened #132
