### ISSUE TITLE
[BUG] Wireless earphones button commands don't work on the player

### ISSUE THREAD

**Issue by Adityap2307** [enricocid/Music-Player-GO#294]
1) [BUG] Wireless earphones button commands don't work on the player

I have wireless earphones from corssbeats.
according to the headphones 2 button click plays next song
1 button pauses/plays

But none of them work on this player
it works fine on YouTube, Spotify and other platforms. so I guess it's the problem with this app only.
Hope you can fix it

And one of the best apps I have used.
Keep it up.
Surely would fund it, once I get my credit card🤪

- Download [platform-tools](https://developer.android.com/studio/releases/platform-tools) for Your OS 
- Enable [developer options](https://developer.android.com/studio/debug/dev-options) and adb debug
- Open a terminal inside platform-tools folder
- Type the following and start recording

`adb logcat -v long > name_of_problem.txt`

- Reproduce the issue/crash. Stop the recording using ctrl + c

**Alternatively** Capture and share a [bug report](https://developer.android.com/studio/debug/bug-report)

5) **Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mi A2 lite]
 - OS: [e.g. Android 9.0]
 - ROM or mods: [please specify any ROM or mods applied that could affect the normal functioning of the app]

6) **Screenshots**

**Additional context**

**Comment by enricocid** [comment]
Yes, I have to implement two buttons click :)

I will try to add this one in the next updates :)

**Comment by enricocid** [comment]
This one is fixed
