### ISSUE TITLE
[BUG] Weird behavior for single repetition mode compared to other app

### ISSUE THREAD

**Issue by LoveChocoCat** [enricocid/Music-Player-GO#295]
1) **Describe the bug**
Ummm, the bug is that single repetition is just repeat the particular music once more instead of repeating that single music forever. Is this by design or just a bug?

2) **To Reproduce the behaviour**
1. Go to the app
2. Click on any music
3. Click the now playing card
4. Click the repetition mode until single repetition mode is on
5. Wait until music playing finished for the first time
6. The repetition mode will just switch off after the music played once
7. Then the music will just play like there is no repetition, playback will stop after the music finished

3) **Expected behavior**
My expectations with single repetition mode is the app will repeat one particular music forever until I stop it. You know, like what VLC's loop one setting behaves.

4) **Provided log**
[single_repetition.zip](https://github.com/enricocid/Music-Player-GO/files/6448665/single_repetition.zip)

5) **Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi note 5
 - OS: Android 9.0 with MIUI 11
 - ROM or mods: MIUI 11, no mods here, just plain MIUI from the factory

6) **Screenshots**
![Screenshot_2021-05-10-05-38-12-406_com iven musicplayergo](https://user-images.githubusercontent.com/37618453/117591773-1e675f80-b160-11eb-8b5d-eb272e0c62b1.jpg)
This is the first time the music played. Seems no problem.
![Screenshot_2021-05-10-05-38-29-551_com iven musicplayergo](https://user-images.githubusercontent.com/37618453/117591720-dea07800-b15f-11eb-9789-003e080fd00c.jpg)
This is the second time this music played, then suddenly the repetition mode just switch off

**Additional context**
https://user-images.githubusercontent.com/37618453/117592370-71daad00-b162-11eb-8bd6-5662ac83ea6b.mp4
I hope this screen capture will explain it better than my words.

**Comment by enricocid** [comment]
You have to choose the infinite mode

![Screenshot_20210510-115950_Music_Player_GO_2](https://user-images.githubusercontent.com/7274841/117642279-6352bc80-b187-11eb-955a-42f566759098.png)

**Comment by LoveChocoCat** [comment]
Ok, so it's by design. Now I'll not complain about this again. Thank you.
