### ISSUE TITLE
[FR] Manual folder selection

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [enricocid/Music-Player-GO#301]
I did see #45, but this is different. Because the app automatically searches /storage/emulated/0 by default, it'd be cool if we could manually select the folder in which we store our music; some of us have folder nests so deep that the app would never ever find them :p

It could have a textbox where we paste the absolute folder path, and/or a handy "Browse" button using the [Android Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider) (SAF).

For _me_ the app is unusable without this, since it can't find any of my songs :/

**Comment by enricocid** [comment]
Duplicate issue :) Closing.
