### ISSUE TITLE
[FR] Custom folder-depth search

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [enricocid/Music-Player-GO#302]
KindOf related to #301; It would be nice to be able to select how many folders deep MusicPlayerGO should look for songs, because of how some store their music, the default depth-search will never find their songs.

(In the settings menu) Maybe a slider with up to 6 levels, or a textbox to input an arbitrary (positive) number.

**Comment by enricocid** [comment]
Hi,
the fact is that songs are retrieved via the [mediastore database](https://developer.android.com/training/data-storage/shared/media) not folder by folder by direct access to the storage. 
It doesn't matter how nested they are.

If a song is not found then it means that there's some problem with MediaStore not being readily updated  by the system. 

Closing...
