### ISSUE TITLE
[FR] Support Wavelet EQ

### ISSUE THREAD

**Issue by auanasgheps** [enricocid/Music-Player-GO#305]
1) **Describe the solution you'd like**
Ciao from Italy
I've just discovered this player and I really like it, but it's missing a key feature for me: support Wavelet EQ app.
To support it, your app should notify the OS using a broadcast. 

2) **Describe alternatives you've considered**
N/A

3) **Additional context**
https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet&hl=it&gl=US
https://pittvandewitt.github.io/Wavelet/

**Comment by Nottijay** [comment]
Can I use the frequency preset for gaming like pubg mobile

**Comment by enricocid** [comment]
> Can I use the frequency preset for gaming like pubg mobile

Presets are provided by the system.
All I can do is to add the possibility to save custom presets 👍🏻

**Comment by auanasgheps** [comment]
Added in the release 4.4.42
