### ISSUE TITLE
[FR] Add option to pause when track is finished

### ISSUE THREAD

**Issue by Glitchy-Tozier** [enricocid/Music-Player-GO#306]
**Is your feature request related to a problem? Please describe.**
Sometimes people don't want to binge through their music, but instead only listen to one track and then have the playing stop until they want to listen to the next track. It can be annoying to immediately be bombarded with a different song.

I haven't found any option that could result in the desired pausing-behaviour.

**Describe the solution you'd like**
In the spot where the user can select whether the song should loop or not, add a fourth option: pause.
This option should pause and the current song when it's done playing.

**Additional context**
Unfortunately, most open-source music players lack this feature.
![Screenshot_20210706-145514_Music Player GO.jpg](https://user-images.githubusercontent.com/59611881/124603431-37dc0d80-de6a-11eb-88cf-007626ace621.jpg)

**Comment by enricocid** [comment]
Added, it will be available in the upcoming version (4.9.10). Thanks :)

**Comment by Glitchy-Tozier** [comment]
Great to hear, thank you! :)
