### ISSUE TITLE
[BUG] Notification with white background in Android 5.0

### ISSUE THREAD

**Issue by proideo** [enricocid/Music-Player-GO#309]
From version 4.4.4 the notification has white background and makes white text unreadable. Changing the app theme does not affect. Before, the notification had dark background (I was using the dark theme).

 - Device: LG L90
 - OS: Android 5.0.2
 
![Notification](https://user-images.githubusercontent.com/50172751/130112071-d894ea34-29d0-44c6-8259-9c1f65770b64.png)

**Comment by enricocid** [comment]
Hi, Thanks for the report 

Please let me know if this debug apk works :)

https://drive.google.com/file/d/1I2V36ZprMe2cjvA82i7gbkt93TOzOPHP/view?usp=sharing

**Comment by enricocid** [comment]
Tested with emu :) 
Closing

**Comment by proideo** [comment]
Yes, in debug version the issue is fixed. Thanks.
