### ISSUE TITLE
[BUG] Headphone/Earbud button to pause not working

### ISSUE THREAD

**Issue by Themightyhook** [enricocid/Music-Player-GO#311]
1) Headphone/Earbud button to pause stopped working out of nowhere it stops it for a split sec but then starts going again. skipping and backing up still work tho. the button works in other players and in YouTube.

2) unsure. it just happen out of nowhere 
[bugreport-kiev_t-QZK30.Q4-40-95-music_go_button_bug.zip](https://github.com/enricocid/Music-Player-GO/files/7073172/bugreport-kiev_t-QZK30.Q4-40-95-music_go_button_bug.zip)

3) taping/ pressing the button once should make it pause 

 - Device: motorola one 5g ace
 - OS: Android 10.0
no mods or anything

**Additional context**
am not sure how much the report shows but it happen before i got a new player to test and see if button works with other things
i have tried deleting cache and uninstall the app and it did not fix, the one in the report a fresh install

**Comment by enricocid** [comment]
Thanks for the report. Gonna post a test APK tomorrow 😃

**Comment by Themightyhook** [comment]
> Thanks for the report. Gonna post a test APK tomorrow 😃

so i have to op into beta testing to test it out?

**Comment by enricocid** [comment]
No, will post a drive link here 😉👍🏻

**Comment by Themightyhook** [comment]
i would need help with that then i only downloaded it form the app store

**Comment by enricocid** [comment]
> i would need help with that then i only downloaded it form the app store

Hi,
could you try this debug apk?

https://drive.google.com/file/d/1p_tSzo2Cr4g08e-pY8BKMdjRjfp79UTE/view?usp=sharing

Thanks

**Comment by Themightyhook** [comment]
Testing it out right now and seems to have fixed it. I keep testing and let you know if it breaks

**Comment by Themightyhook** [comment]
Sometimes it seems to not register my hitting it or hangs for a sec

**Comment by Themightyhook** [comment]
It's seems to be rare tho.

**Comment by enricocid** [comment]
Thanks :)

Yes, I'm aware of it. Tried different ways to register the media buttons receiver but still no luck. I think it depends by the media session itself which is handled by the system 😵🤷‍♂️

**Comment by Themightyhook** [comment]
Alright I take it be added to the main app now I take it?

**Comment by enricocid** [comment]
👍🏻

**Comment by enricocid** [comment]
Hi,

could you try the latest build apk once available?

https://github.com/enricocid/Music-Player-GO/actions/runs/1198150919

Thanks :)

**Comment by Themightyhook** [comment]
sure? am not sure how to do that tho
