### ISSUE TITLE
Continuous translation integration

### ISSUE THREAD

**Issue by comradekingu** [enricocid/Music-Player-GO#321]
I added pushing to "main" from the strings component.
Adding the Weblate user to the project/org and
https://docs.weblate.org/en/latest/admin/continuous.html?highlight=continuous%20integration#automatically-receiving-changes-from-github
is needed. Not sure if both, but does work then.

Edit: Also ran into https://github.com/WeblateOrg/weblate/issues/6682
Are all the files UTF-8, and/or is there some character that fails?

**Comment by enricocid** [comment]
Thanks! 
I'm stuck here:

"For the payload URL, append /hooks/github/ to your Weblate URL, for example for the Hosted Weblate service, this is https://hosted.weblate.org/hooks/github/."

**Comment by comradekingu** [comment]
Closing tentatively :)
