### ISSUE TITLE
The requested file was not found

### ISSUE THREAD

**Issue by MKrabs** [enricocid/Music-Player-GO#326]
Just tried to download via fdroid and the latest version 169 was not found. Later versions also don't seem to work.

Is it my phone, fdroid or your servers having issues?

![Screenshot_20211022-160524_F-Droid](https://user-images.githubusercontent.com/71791731/138467951-aa011d87-f50b-4cd5-840f-b7e3b1b8c8ed.jpg)

**Comment by enricocid** [comment]
Closing...
If the problem persists please ask to the f-droid community.
Thanks :)
