### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by ureber** [enricocid/Music-Player-GO#33]
First of all, many thanks for this nice and slim music player. I like it a lot.

Nevertheless I have a wish: Is it possible to implement a slider that allows to control the volume linearly (i.e. not via the equalizer). The reason is that the volume levels given by Android are too coarse. I would very much appreciate the opportunity to fine-tune the volume in the app.

Thank you!

**Comment by enricocid** [comment]
Fixed
