### ISSUE TITLE
[FR] [Request for Comments] Implement standard Intent based play/pause feature

### ISSUE THREAD

**Issue by gaycodegal** [enricocid/Music-Player-GO#331]
Please note I intend to implement this feature request, I'm just stating my intentions beforehand in case there's a different way to do this.

# Desired solution
Implement the ability to handle the intents for "com.android.music.musicservicecommand"
- This means responding to all the commands [(listed here)](https://android.googlesource.com/platform/packages/apps/Music/+/278aaed1eb37763f7dcb2364523db591014a9210/src/com/android/music/MediaPlaybackService.java):
    1. "togglepause"
    2. "stop" 
    3. "pause"
    4. "previous"
    5. "next"

## Reason
I'm implementing an open source assistant for android, and I want my music to stop when I say "stop" and play when i say "play", and allow for additional commands like "previous" and "next". The Intent "com.android.music.musicservicecommand" is meant for handling this, but most apps don't implement it.

# Describe alternatives you've considered
I can stop all apps from playing sound with "AudioManager.AUDIOFOCUS_GAIN" in audioManager.requestAudioFocus, but I am unable to start apps playing music again with this api (the transient API seems to work, but if i kill my AI, music resumes). This requestAudioFocus API is also not set up to allow for next and previous song plays. 

I tried pressing buttons on screen programmatically but I'm not allowed to do that without root. Thus, using the intended API for this is really my only option. I'd love an option that is global, but since i'm mostly making the AI for me (and others can use it if they choose), I can just implement the correct API in my music app of choice and move on. I'll still fall back to AUDIOFOCUS_GAIN if music isn't paused by intent, but I want music to work correctly.

If your app has a different intended API that doesn't involve pressing buttons for this, do let me know, otherwise I'll submit a pull request with the implementation at some point in the future. Thanks!

**Comment by gaycodegal** [comment]
I'm just noting that I do understand your app supports "android.intent.action.MUSIC_PLAYER", and this is useful, but I think supporting both types of music intents is good

**Comment by gaycodegal** [comment]
Oh i'm reading further you do have a custom version of what i'm intending to do, so it may be simple to make GO also obey the standard API (your custom constant for refererence:)

```kotlin
const val PLAY_PAUSE_ACTION = "PLAY_PAUSE_GO"
```

**Comment by gaycodegal** [comment]
Also possible I need to do further research, I'm seeing you do have a media session at least, which is required for the google assistant https://developer.android.com/guide/topics/media-apps/interacting-with-assistant

**Comment by gaycodegal** [comment]
yeah definitely the BroadcastReceiver should get hooked up. It looks like NotificationReceiver needs to be exposed and accessed statically in order to be listed in the android manifest, which will then connect fully

**Comment by gaycodegal** [comment]
I've been testing using the following, which should at least engage the receiver when this is all hooked up properly

```shell
adb shell 'am broadcast -a android.intent.action.MEDIA_BUTTON'
```

**Comment by enricocid** [comment]
PR has been merged. Closing. :)
