### ISSUE TITLE
Stop playback when a song ends

### ISSUE THREAD

**Issue by Niilavarnam** [enricocid/Music-Player-GO#334]
Hello,
I have been testing the app and I like it a lot, it also has the possibility to run the player with another app with android.intent.action which is very good for me. 
The problem is that when you start to play a song the player does not stop at the end of that song and continues with other files. 
Is there any possibility to make it stop after playing the whole song?
Thanks
Regards

**Comment by enricocid** [comment]
No, gonna add an option for that ;)

**Comment by enricocid** [comment]
Duplicate issue #306 
Closing...

PS gonna add this option in the next update

**Comment by enricocid** [comment]
Added, it will be available in the upcoming version (4.9.10). Thanks :)
