### ISSUE TITLE
[FR] Reconsider #00000 Dark theme for OLED screens

### ISSUE THREAD

**Issue by repparw** [enricocid/Music-Player-GO#335]
1) **Describe the solution you'd like**
A manually selected option for black background, so you can pick between light, dark (the current ones), and black.
It would be battery-saving for devices with OLED screens, and it would still adhere to Material guidelines.

**Comment by linusrg1** [comment]
+1 for this feature

**Comment by enricocid** [comment]
The problem is there are only 3 modes: light, night and auto.
So you can't define another dark theme.

Anyway I can replace the current background color to black or try another approach.

👍🏻

**Comment by repparw** [comment]
Another toggle for what colour does night mode applies would be okay, I guess, if it doesn't disrupt with the app too much

**Comment by enricocid** [comment]
It can be shown when night mode is enabled 👍🏻

**Comment by enricocid** [comment]
For simplicity (and for the high load of requests in the past), I decided to switch to black.

Let me know if it is ok now (I don't have a oled device)

https://drive.google.com/file/d/11vsEaK1njq87bMcmMF7cr9JhV6mR1fyB/view?usp=sharing

**Comment by repparw** [comment]
At first glance it looks okay! Waiting for the update on release, thank you!
