### ISSUE TITLE
[BUG] Hard to see shuffle button on new dark theme

### ISSUE THREAD

**Issue by repparw** [enricocid/Music-Player-GO#350]
1) **Describe the bug**
Depending on brightness level it can be difficult to see the shuffle button on songs tab.

6) **Screenshots**
![Screenshot_20211223-191705_Music_Player_GO~2](https://user-images.githubusercontent.com/45952970/147296018-fd30a839-4516-463a-b09b-3c6059f48817.png)

Maybe make the icon grab same color as text?

**Comment by enricocid** [comment]
Thanks. Gonna fix asap 😁

**Comment by enricocid** [comment]
Fixed :)

You can download a test apk from this job once finished (scroll to the bottom)

https://github.com/enricocid/Music-Player-GO/actions/runs/1667971159
