### ISSUE TITLE
[FR] Remember pause after finish

### ISSUE THREAD

**Issue by Glitchy-Tozier** [enricocid/Music-Player-GO#352]
(This isn't quite a feature request but more of a fix for a preexisting feature)

 **Describe the solution you'd like**

Currently, the option to pause after finish resets every time a song is finished. Thus, for every song, you'd need to re-enable it separately.

In my opinion, options like this should stick until they're manually changed. Otherwise, It's not much of a help at all, unfortunately.

**Comment by enricocid** [comment]
Next update:)

**Comment by Glitchy-Tozier** [comment]
Looking forward to that update! :)

**Comment by enricocid** [comment]
Hi,

do you want this option to stick even after rebooting the app?

**Comment by Glitchy-Tozier** [comment]
I'd prefer it. That functionality would make the most sense to me. :)

Am 7. Jänner 2022 14:48:31 UTC schrieb enricocid ***@***.***>:
>Hi,
>
>do you want this option to stick even after rebooting the app?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/enricocid/Music-Player-GO/issues/352#issuecomment-1007464760
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Mit freundlichen Grüßen,
Florian Thaler

**Comment by enricocid** [comment]
Added.
You can try the debug apk once the build process is finished to test the new behaviour

(scroll to the bottom)
https://github.com/enricocid/Music-Player-GO/actions/runs/1669032870

**Comment by Glitchy-Tozier** [comment]
I'm a little hesitant to try out apps that weren't downloaded from some store; I'll happily try it out as soon as the update gets released though! :)

**Comment by Glitchy-Tozier** [comment]
Works great, by the way!
Due to this feature being added and the fact that the app has minimal permissions (no network access!), it now is my audio-player of choice. Thank you :)
