### ISSUE TITLE
[FR] Translatable fastlane files

### ISSUE THREAD

**Issue by comradekingu** [enricocid/Music-Player-GO#359]
I got through trying to set up https://hosted.weblate.org/settings/music-player-go/colours/#files which didn't work so well, when I sort of remembered you didn't want a fastlane component added.
Hmmm

**Comment by enricocid** [comment]
Color resources can't be translated :)

**Comment by enricocid** [comment]
Add new strings for colors! Closing... :)

**Comment by enricocid** [comment]
You're welcome @comradekingu :)
