### ISSUE TITLE
Direct delete song thought the player playlist

### ISSUE THREAD

**Issue by nhsolanki** [enricocid/Music-Player-GO#369]
1) **Describe the solution you'd like**
p.s. only **ONE** feature

2) **Describe alternatives you've considered**

3) **Additional context**
Add any other context or screenshots about the feature request here. To add screenshots please use markdown formatting, like the following:

`<img height="450" src="[link_to_the_screenshot here].file_extension">`

**Comment by enricocid** [comment]
Just added an option in settings :)
It will be available in next update
