### ISSUE TITLE
Wrong grouping of artists.

### ISSUE THREAD

**Issue by dankan1890** [enricocid/Music-Player-GO#37]
I found an error in grouping artists who do not have the populated album field, they are all grouped under the first artist found.
![error](https://user-images.githubusercontent.com/7107228/43372820-57b0a868-93a5-11e8-801a-83c847c3ad99.PNG)

**Comment by dankan1890** [comment]
np :-)
In the meantime I'm trying to integrate the headphone controls :-)

**Comment by enricocid** [comment]
closing as the query implementation will change on kotlin releases, so it needs to be tested
