### ISSUE TITLE
Changing language 

### ISSUE THREAD

**Issue by CYAXXX** [enricocid/Music-Player-GO#380]
Actually it's no a bug, I finished translation process for this app into kurdish on weblate a while ago maybe 1 month ago, I don't remember correctly, but I can't figure a way to switch the language, any help?

**Comment by enricocid** [comment]
Weird. 
Have you selected Kurdish in system settings?

@comradekingu any idea? Do you know if android actually supports Kurdish?

**Comment by enricocid** [comment]
@CYAXXX do you have problems with other apps ? Could you point me to a working (open source) app. Thanks 🙏🏻

**Comment by CYAXXX** [comment]
Thanks for quick response, well I was wonder if this app have a language switcher inside it's self, seems no. It doesn't have. And no Kurdish language isn't supported on many platforms such as android/ iOS/window, etc.. I've translated 14 application into kurdish and unfortunately this is the second app (after Kiwi browser) which doesn't have integrated switcher.

**Comment by enricocid** [comment]
Ok, then I will investigate the possibility to add the switcher 😊

**Comment by CYAXXX** [comment]
Thank you

**Comment by enricocid** [comment]
Gonna leave it opene 😉

**Comment by CYAXXX** [comment]
> Gonna leave it opene 😉

Oh ok no problem with that😁

**Comment by comradekingu** [comment]
@CYAXXX You can ask Google to have it added. I have done so before.

**Comment by CYAXXX** [comment]
> @CYAXXX You can ask Google to have it added. I have done so before.

Many organization have asked google before many times, I'm not sure it's gonna work

**Comment by enricocid** [comment]
@CYAXXX 
Could You try this? :)

https://drive.google.com/file/d/1WuFo3rIiWHNgt9Ed-03uKUtS5lgMWcBi/view?usp=sharing

**Comment by CYAXXX** [comment]
> @CYAXXX Could You try this? :)
> 
> https://drive.google.com/file/d/1WuFo3rIiWHNgt9Ed-03uKUtS5lgMWcBi/view?usp=sharing

Thank you some much, it's working 😄

**Comment by enricocid** [comment]
Added :)

**Comment by CYAXXX** [comment]
> Added :)
Thanks alot, I fixed some wrong strings on weblate too.
