### ISSUE TITLE
Would Music-Player-GO require a privacy policy?

### ISSUE THREAD

**Issue by HarryHeights** [enricocid/Music-Player-GO#39]
Hello, I'm Harry. I'm a content creator and a copywriter. Most app especially in the open source community here on Github don't have a privacy policy document and it's quite essential so prospective users and current users can know how you deal with data that's collected while Music-Player-GO is utilized. If you think it's okay to have the document, I'd create it.

Hope to hear from you.

**Comment by enricocid** [comment]
Hello,

Music Player GO doesn't need privacy policy as there's no data collection and no access to sensitive/dangerous permissions (e.g. contacts, microphone, camera etc...). The only permission required is the storage access to list the music on the device. If you want explain how this permission is used and that there's no data collection I'm OK.
Thanks 😁

**Comment by HarryHeights** [comment]
Thanks for replying. I've used the app to know a little about how it deals with these things. However, privacy policy don't necessarily apply to only projects that collect data. It's also a means to tell your audience that you actually don't collect any information when your software is utilized. This will even bring a sense of security to them even more while they use your software. I think I've done a job for a project that the developer don't collect personal information. Can't seem to place my head on which project it was.

**Comment by enricocid** [comment]
Ok, then I'm ok if you create a privacy policy 😁

**Comment by HarryHeights** [comment]
Thanks for your reply. I'll make a PR for the document very soon. However it is subjected to your review to check out things in the doc you may want to express or not. Thanks again.

**Comment by HarryHeights** [comment]
Hello. I've made a pill request for the privacy policy. 
Thanks.

**Comment by enricocid** [comment]
Many thanks. I just got off work, I will look into it tomorrow morning 😉

**Comment by HarryHeights** [comment]
Alright. No qualms. I never knew developers had real day jobs though. I thought they sat all day at home writing codes and things I'm not sure I'll ever understand.
