### ISSUE TITLE
Language Switcher

### ISSUE THREAD

**Issue by taboov** [enricocid/Music-Player-GO#406]
First of all, thanks for this great FOSS music player app. 

The issue #380 seems that, it's closed by adding a language switcher in the app, but I don't know if I'm missing something or the switcher isn't integrated in the app yet!?

**Comment by enricocid** [comment]
Next release 😉

**Comment by enricocid** [comment]
Closing.
Feature is already integrated in the app. It will be available in the next release.
You can try it by installing the latest debug APK.

https://github.com/enricocid/Music-Player-GO/suites/6192614118/artifacts/218146890

**Comment by taboov** [comment]
Works just fine.
 Thanks  :star_struck:
