### ISSUE TITLE
[FR] Add to favorite in notification

### ISSUE THREAD

**Issue by ayoubelmhamdi** [enricocid/Music-Player-GO#414]
- are there any plan to add ❤️ to setting in notification like that  
- because it's very useful for me  
  

![IMG_20220511_105339](https://user-images.githubusercontent.com/34358145/167823243-09e733f5-a219-46cf-bd6c-5056a64d4f1d.jpg)

**Comment by enricocid** [comment]
Hi, unfortunately there's no more room for actions in notifications (max=5).
I can add an option to let the user choose combo of the two additional actions in future updates 😊

**Comment by enricocid** [comment]
Just added an option :) It will available in next release. :)
