### ISSUE TITLE
Add an option to display and index music files by their filename

### ISSUE THREAD

**Issue by CodeCubeNeo** [enricocid/Music-Player-GO#439]
I think it would help users who have local music files that have weird metadata titles, that they can see and search those music files in the app by their filename (filename in the filesystem). There could be an option in the setting to display and index songs by filename instead of the title. An example app that has this feature is the simple music player from simple mobile tools

**Comment by enricocid** [comment]
I'm pretty sure I already added this feature a while ago 😆😊

![Uploading Screenshot_20220714-113741_MPGO_debug.png…]()

**Comment by enricocid** [comment]
Ok, understood :)
Gonna check simple mp too, thanks :)

**Comment by CodeCubeNeo** [comment]
I saw that simple mp also doesnt fully solve that problem. It doesnt show the filename always

**Comment by enricocid** [comment]
Just fixed songs filtering. Now it filters by file name instead of title when the option is selected. That was a bug.
Let me know if I can improve the option further.

**Comment by CodeCubeNeo** [comment]
I think that is exatly what i meant. Really awesome and thank you many times. Now we wait for the new release ;).

**Comment by CodeCubeNeo** [comment]
This is now fixed and now I can finally search by the filename ;). But now i cant search for the song by its metadata filename (idk if that is intended). Also there is one other weird thing, when i click the song to play the playing screen is displaying the metadata title, not the filename even with song visualisation: filename option selected.

**Comment by enricocid** [comment]
1. I can show both results (filename + metadata title) if you want
2. Yeah, that is intended. I can change it too in next update.
Let me know 😉

**Comment by CodeCubeNeo** [comment]
Well i guess if the option "song visualisation" is set to filename it should display it in the playing now screen with the filename right?

**Comment by enricocid** [comment]
This issue should be fixed now. You can try the debug apk that will be available here (at the bottom) once the build process has finished :)

**Comment by enricocid** [comment]
This one should be fixes now. Closing.
