### ISSUE TITLE
[Bug]: The toast message about repeat mode is not translated

### ISSUE THREAD

**Issue by lgjint** [enricocid/Music-Player-GO#447]
### What happened?

Hello! Thank you for developing such a good music player!

But I notice the toast message about repeat mode is not translated. it's displayed in English. Could you please fix this bug?

### Version

4.4.19

### Device and Android version

Xiaomi Poco F4/Android 12

### More info

![IMG_20220801_142744](https://user-images.githubusercontent.com/78463565/182087728-f7230e49-c902-49ac-9a28-b21b83b792af.jpg)
![IMG_20220801_142704](https://user-images.githubusercontent.com/78463565/182087736-83b3ff3e-10bf-471a-a72d-b8554fb9f53c.jpg)
![IMG_20220801_142716](https://user-images.githubusercontent.com/78463565/182087741-27d70195-f5ea-478a-96be-550294840eb0.jpg)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
What language?

**Comment by lgjint** [comment]
> What language?
Chinese simplified. i saw it was 100% translated in W
weblate

**Comment by lgjint** [comment]
Chinese simplified. i saw it was 100% translated in W
weblate

**Comment by enricocid** [comment]
Ok, will try to fix within the next few days. Thanks 😎

**Comment by enricocid** [comment]
This issue should be fixed now. You can try the debug apk that will be available here (at the bottom) once the build process has finished :)

**Comment by lgjint** [comment]
It works! Thanks
