### ISSUE TITLE
Folder-by-folder navigation

### ISSUE THREAD

**Issue by hugoncosta** [enricocid/Music-Player-GO#45]
Hey, I'd like to request a folder by folder navigation to facilitate finding the songs I want if possible! :)

**Comment by enricocid** [comment]
Tried right now some flacs and an aac files and I can play them ...
mediaplayer already supports these formats
https://developer.android.com/guide/topics/media/media-formats

Maybe they're not tagged properly so you find them in the unknowns

**Comment by hugoncosta** [comment]
You're right, I missed that! The way I was using app was by clicking and the logo and thinking that I was opening the folders, but I was browsing the "unknown" ones. Speaking of, would that be something you'd be willing to introduce? I have a lot of clips from youtube that would take forever to organise properly, I'd prefer it on a folder by folder basis.

**Comment by enricocid** [comment]
Maybe I should let the user to choose between folders & artists navigation system. I was thinking about it and it is already in my to-do list

**Comment by hugoncosta** [comment]
That would be amazing, I'll be waiting to hear from you! If I could also suggest, you could make use of a left/right menu, activated by a swipe, in order to activate the sort functions

**Comment by enricocid** [comment]
Thanks, can You change the issue's title with an explanatory one so I can keep better track of these request. Thanks

**Comment by enwokoma** [comment]
This is 5 months into this request. What's the status please?
This is needed. 

Not just the listing of songs by folder. But also listing as Albums, Artists, All Songs too

**Comment by enricocid** [comment]
I actually have some familiar problems. Moreover, I'm going to relocate abroad in the next months so I'm not in the mood to focus on Music Player GO.
Once all my issues will be solved, I will finish the implementation and release it for public.

Sorry for the inconvenience, but life happens.

Hope You understand

**Comment by enwokoma** [comment]
Oh. Okay!
Take your time

**Comment by rubo77** [comment]
Hope you relocated fine by now. Will you have time for this feature?

It is really hard to navigate, if your MP3 tags are not well

**Comment by enricocid** [comment]
I already have a working implementation , but need to review a little and test. It will be available for the next release (4.0.0) for sure ;)

**Comment by enricocid** [comment]
So I added this feature. The folders fragment will show a list of the folders containing songs. There will be fast scroller and search to filter folders.
One can also exclude artists and songs fragment leaving folders one (the layout is now tabbed).
I won't anyway implement the full folders tree navigation as it is very complicated (it is like having a second app) and clashes with MPGO philosophy. This is very simple implementation and works good at least for me.
Gonna close the issue. Once the app is released You will post Your feedback, if any 👌😁
