### ISSUE TITLE
[Bug]: Buggy precise volume management

### ISSUE THREAD

**Issue by CodeCubeNeo** [enricocid/Music-Player-GO#453]
### What happened?

The volume control is not visible and when i swipe down a bit it is shown, but i cant control it (see the video). If you need anything else you can ask.

https://user-images.githubusercontent.com/61159092/183052298-ed588365-5333-4a83-9e8e-881106072b58.mp4

### Version

4.4.20

### Device and Android version

Huawei Mate 9, Android 9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
Thanks 🙏🏻😎

**Comment by enricocid** [comment]
try this once built

https://github.com/enricocid/Music-Player-GO/actions/runs/2803712802
