### ISSUE TITLE
[FR]: Folder view should show folder structure

### ISSUE THREAD

**Issue by sojusnik** [enricocid/Music-Player-GO#457]
### What feature would you like to see?

When using the folder view, I would like to see my folder structure, as usually done in file browsers. At the moment you only see folders containing music files without a hierarchy, which doesn't allow you to navigate through them using a folder structure, that is already present.

It would also help, if you could specify which folders you want to see in this folder mode, by having f.i. a whitelist, where you can add folders like `/storage/emulated/0/Music` and `/storage/emulated/0/Audiobooks`.

### What kind of level is this feature request?

Hmm, probably intermediate, can't know!

### More info

The folder view could look like this, but more in alignment with the current Android design guidelines: 
![grafik](https://user-images.githubusercontent.com/1245718/183843413-4341cbe4-d041-485a-a363-70e10db36765.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
The fact is that since android 10 you can't access due to security reasons.

More info here:

 https://github.com/enricocid/Music-Player-GO/issues/415

**Comment by sojusnik** [comment]
If I understood you correctly, indexing only `/storage/emulated/0/Music` wouldn't help as well in this situation, to have a structured folder view?

So the other apps with a hierarchical folder view use a somewhat hackish approach and achieving this easily isn't really an option at the moment for your app?

**Comment by enricocid** [comment]
Moved this issue to the appropriate thread #415 closing
