### ISSUE TITLE
[Bug]: Notification Disappeared frequently

### ISSUE THREAD

**Issue by Pranab009** [enricocid/Music-Player-GO#458]
### What happened?

If you play any music through file manager it's playing well but notifications are disappeared after some time.

If you play any music through this music player ,then it's notification work well.

### Version

4.4.20

### Device and Android version

Micromax in 1 Android 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
Probably related to 81b2af31a78c93bd4eb1f0840c3d02e25431a317
That's the only bug I was able to find.
Closing for now.

**Comment by enricocid** [comment]
Probably related to 81b2af31a78c93bd4eb1f0840c3d02e25431a317
That's the only bug I was able to find.
Closing for now.
