### ISSUE TITLE
[Q&A]: Songs sorted alphabetically by default instead of song order

### ISSUE THREAD

**Issue by seratym** [enricocid/Music-Player-GO#460]
### What are You thinking?

All albums have their songs sorted alphabetically. This is in both the artist view and the album view. In album view sorting on "By track no" is greyed out. Other apps (Metro and Phonograph) are able to order the songs correctly. The song format are mp3 or flac. Strangely enough, I couldn't find any similar questions online.

Thanks for the great app!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
Hi, try to change song visualization option to "title". 😁

**Comment by seratym** [comment]
That worked, thanks you enricocid!
