### ISSUE TITLE
[Bug]: sleep timer buggy

### ISSUE THREAD

**Issue by abelbabel** [enricocid/Music-Player-GO#469]
### What happened?

Hi,

when I open the program and I try to activate the sleep timer it says "Play a song first". When I play a song then and try to activate the sleep timer, it seems to work. I can view the remaining time in the sleep timer sub-window. But then the buggy parts begin: When I press "Stop" it says "Play a song first", opening up the sleep timer sub-window afterwards does not show the remaining time anymore and also no possibility to choose a time. 

"Cancel" works as expected.

Could you fix it?

Regards,
abelbabel

### Version

4.4.21

### Device and Android version

Sony Xperia ?, Android 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
Yeah, that's a bug. I can actually reproduce it.
Gonna fix asap.
Thanks. 😉

**Comment by enricocid** [comment]
It is fixed now.

Debug apk, if you want to test the changes, will be appended here once the build is finished 
https://github.com/enricocid/Music-Player-GO/actions/runs/3031186384

Thanks :)
