### ISSUE TITLE
[Q&A]: How can I build MPGO in Android Studio?

### ISSUE THREAD

**Issue by libregeek** [enricocid/Music-Player-GO#471]
### What are You thinking?

I am a newbie in Android Development and trying to understand how Music Player Go works under the hood. I cloned the repository on Android Studio and tried to build the application without any changes to the source code. Could you please help me to build and run the app on an emulator?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
You have to select project folder :)

![Senza nome](https://user-images.githubusercontent.com/7274841/189841585-6fd2be3e-c857-4290-b200-6d2e71c40d47.png)

**Comment by libregeek** [comment]
Thanks a lot. It worked. 

I am curious how you implemented reading metadata from files. Is there any document which describes the approach you have implemented?

**Comment by libregeek** [comment]
Thanks for the quick reply. These are really helpful.

**Comment by enricocid** [comment]
Closing for now.
If you have any questions don't hesitate to add a comment 😉
