### ISSUE TITLE
[FR]: .nomedia & dot folder index.

### ISSUE THREAD

**Issue by AdityaMishra135** [enricocid/Music-Player-GO#476]
### What feature would you like to see?

.nomedia and dot folder music not indexing. 

### What kind of level is this feature request?

Hmm, probably intermediate, can't know!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
MediaStore, the API that MPGO relies on, ignores hidden folders or folders containing .nomedia (probably to enforce security).
