### ISSUE TITLE
Scan specific folders for music

### ISSUE THREAD

**Issue by angryseptagon** [enricocid/Music-Player-GO#48]
Hello, I am using syncthing for android and I can only do two way sync in its application folder. is there any way to force this music player to scan inside a specific folder?

**Comment by enricocid** [comment]
Nope at the moment. But I can add this feature to my to-do list😉

**Comment by xnegra80** [comment]
I would like to contribute 👍  are there any contribution guidelines?

**Comment by enricocid** [comment]
You're welcome. 

No (not a pro dev, don't even know how to write guidelines), just keep it simple :)

**Comment by xnegra80** [comment]
@enricocid how would you like the user to choose the path? Also are you using android studio i cant seem to get intellij working

**Comment by enricocid** [comment]
A multi-select dialog? Really don't know 

Yes I'm using Android studio. 

Just for completion: work on this branch which will be the new MPGO (it has an options tab)

https://github.com/enricocid/Music-Player-GO/tree/master-mpgo-ex

Don't want you to waste time :)

**Comment by xnegra80** [comment]
I'm still new to this and trying my best to help :) @enricocid  would you like something like this [https://github.com/hedzr/android-file-chooser](url) just to clarify i should be working on the `MusicUtils.getMusicCursor()` if i have not mistaken.
Cheers

**Comment by enricocid** [comment]
Exactly!! :)

**Comment by xnegra80** [comment]
The current implementation is grouping both artists and folders as "Hidden items" I think if we can separate artists and folders, then I can loop through all the hidden folders and exclude them. I tried doing so but it fails :(

**Comment by enricocid** [comment]
You are right. I also don't like the actual implementation.
In fact, I'm actually merging most of the changes to release them to public escluding folders for now. I will separate it for sure and rework hidden items too.

**Comment by StarFscker** [comment]
Hey this feature is really important because I don't know how to get the music in my Music folder to show up, thank you guys for working on this feature. I really appreciate it and hope it's included soon.

**Comment by enricocid** [comment]
I can actually add an option to select folders we want to show.
So I can use this output as filter. I could also let the user filter the music by artist.
This is a quick way I can handle this issue.
Anyway, it will require some days as I'm actually using an emu as my test device is broken, so I have to ask to other contacts/devs to test the app on their test devices.

I can't provide a dialog listing the whole memory tree as it is a very complex and would not be compatible with Android 10 + (it is not possible anymore to access raw paths, and it is not suggested even in older Android versions ... ). Also, docs about storage access framework is not that good. I'm not sure I want saf in my app. It would make it more error prone.
That's the problem. Memory management is changing a lot unfortunately and I have to make sure to keep the code clean and compatible with newer versions without any gimmicks.
Many other devs are experiencing issues in this direction.

I could use a 3rd party library but its output (raw paths) can't be used in Android 10+.

**Comment by Baldomo** [comment]
Retro Music Player (also FOSS) uses a kind of blacklist for song selection using Android's MediaStore, it may be useful as an example: [code](https://github.com/h4h13/RetroMusicPlayer/blob/master/app/src/main/java/code/name/monkey/retromusic/loaders/SongLoader.kt#L106)

**Comment by enricocid** [comment]
> Retro Music Player (also FOSS) uses a kind of blacklist for song selection using Android's MediaStore, it may be useful as an example: [code](https://github.com/h4h13/RetroMusicPlayer/blob/master/app/src/main/java/code/name/monkey/retromusic/loaders/SongLoader.kt#L106)

Thanks but this code is not compatible with scoped storage changes introduced in Android 10.

They are querying data column that returns the raw path of a music file.
In fact, they are using this attribute in the manifest

```android:requestLegacyExternalStorage="true"```

to opt out scoped storage. These changes will become mandatory in August 2020 and Android 11.

I already added the ability to hide artists and folders.
I can review this feature adding a dialog listing all folders letting the users to build a filter.
But again, I can't show the full tree as it is not possible to access the raw path but only the folder name.

**Comment by joaopmatos** [comment]
@enricocid These errors happen when I try to sync project folder.
![erro](https://user-images.githubusercontent.com/89925580/139961301-00717f61-10c6-4403-9f81-f63eb8ca2d66.png)

**Comment by enricocid** [comment]
> @enricocid These errors happen when I try to sync project folder.
> ![erro](https://user-images.githubusercontent.com/89925580/139961301-00717f61-10c6-4403-9f81-f63eb8ca2d66.png)
> 
> 
 AndroidStudio comes with Android 12 support, but mpgo still does not support it.
So you have to the SDK manager and install android 11 sdk 30 and rebuild 👍🏻

https://developer.android.com/about/versions/11/setup-sdk

**Comment by joaopmatos** [comment]
> > @enricocid These errors happen when I try to sync project folder.
> > ![erro](https://user-images.githubusercontent.com/89925580/139961301-00717f61-10c6-4403-9f81-f63eb8ca2d66.png)
> 
> AndroidStudio comes with Android 12 support, but mpgo still does not support it. So you have to setup android 11 sdk 30 from the SDK manager and rebuild 👍🏻
> 
> https://developer.android.com/about/versions/11/setup-sdk

Thanks for the help with such a newbie question! Now I'm all set up.

**Comment by joaopmatos** [comment]
I've managed to make it possible for there to be a specific folder selected. Now, if the user selects a specific folder, it will read all music files in that folder and ones inside it.
However, this was only done in the code itself, e.g here:

![codeFolder](https://user-images.githubusercontent.com/89925580/140652277-9570b231-80d9-4e43-abb4-31bdd34c79a7.png)

If you have any suggestions to the code please tell me!
Do you want me to change UI elements in the settings for the user to select the folder as well or should I leave that to you?
Sorry if it's got an obvious answer but I'm new to contributing, I don't want to upset anyone!

**Comment by enricocid** [comment]
> @enricocid I've managed to make it possible for there to be a specific folder selected. Now, if the user selects a specific folder, it will read all music files in that folder and ones inside it. However, this was only done in the code itself, e.g here:
> 
> ![codeFolder](https://user-images.githubusercontent.com/89925580/140652277-9570b231-80d9-4e43-abb4-31bdd34c79a7.png)
> 
> If you have any suggestions to the code please tell me! Do you want me to change UI elements in the settings for the user to select the folder as well or should I leave that to you? Sorry if it's got an obvious answer but I'm new to contributing, I don't want to upset anyone!

Do you have a build so I can try? 😃

**Comment by enricocid** [comment]
#301

**Comment by enricocid** [comment]
Added merged storage related issues into #415
