### ISSUE TITLE
[Bug]: Music plays automatically when headphones are plugged in

### ISSUE THREAD

**Issue by sinoory** [enricocid/Music-Player-GO#481]
### What happened?

step：
1. play music with speaker
2. pause music play
3. plug in a headphone
expect not play music after plug in a headphone， but actually does

when headphone plug in ，onPrepared function in com/iven/musicplayergo/player/MediaPlayerHolder.kt called，
maybe the isPlay flag is wrong after pause music。
    override fun onPrepared(mp: MediaPlayer) {
        if (isPlay) {
            play()

### Version

4.4.20

### Device and Android version

android12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
There's an option to disable headset management 😉

**Comment by sinoory** [comment]
> There's an option to disable headset management wink
ok close it
