### ISSUE TITLE
[Bug]: the notification play status is different with music play status when the alarm clock rings

### ISSUE THREAD

**Issue by sinoory** [enricocid/Music-Player-GO#485]
### What happened?

steps：
1. play a music
2. setup an alarm ，and the alarm rings，music will be paused automatically
3. stop the alarm，music will be resumed automatically
4. pull down the notification bar，watch the music play status
expect ： the music play status is playing，
actually：the music play status is stopped

### Version

4.4.20

### Device and Android version

android12.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
This problem has already been fixed
😉
https://github.com/enricocid/Music-Player-GO/commit/4e9e77cf0a578aa95d3ab5ffbe3001fae0b5acb1
