### ISSUE TITLE
[Bug]: Some preferred titles and the cancel button of alert dialog are not translated

### ISSUE THREAD

**Issue by lgjint** [enricocid/Music-Player-GO#487]
### What happened?

Thank you for developing such a good music player!

But I found that the strings category_ui and category_audio are located in the donottranslate.xml file, could you please provide the translation portal in Hosted Weblate like category_general?

Besides the cancel button of alert dialog is not translated by the @string/cancel, Could you please fix this bug?

### Version

4.4.20

### Device and Android version

Xiaomi Poco F4/Android 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
Which language?

**Comment by lgjint** [comment]
> Which language?

Simplified Chinese (but I think it should be the same for other languages)

**Comment by enricocid** [comment]
Weird. Simplified Chinese is working for me.

Have you tried the latest version.

Try the output apk once the build process has finished :)

https://github.com/enricocid/Music-Player-GO/actions/runs/3321200056

If it does not work try to apply Your language using the locale switcher You find in settings :)

**Comment by lgjint** [comment]
> 
I have been using the latest version apk of F-droid, then I tested the github action build apk, same result.

Thanks for your help!

![photo_2022-10-25_21-25-11](https://user-images.githubusercontent.com/78463565/197786230-d4d8212e-b4fb-44b0-8534-15d900accefb.jpg)
![photo_2022-10-25_21-25-08](https://user-images.githubusercontent.com/78463565/197786237-2fdcf858-cad8-4309-b1b0-9bc839d4773c.jpg)
![photo_2022-10-25_21-24-55](https://user-images.githubusercontent.com/78463565/197786242-3365caf4-4b68-4964-80a9-b69194e648cf.jpg)

**Comment by enricocid** [comment]
Preference categories are now available on weblate :)

Have you tried using the in-app locale switcher?

**Comment by lgjint** [comment]
I tried using the in-app locale switcher, there is no problem switching the dialog box to any language except Simplified Chinese, so it may be a problem with my system.

Thank you very much for your help again!

**Comment by lgjint** [comment]
> Preference categories are now available on weblate :)
> 
> Have you tried using the in-app locale switcher?
> 
> Ah, ok, that's a preference dialog not an alert dialog :)

I've submitted a Simplified Chinese translation on Hosted Weblate, the app is awesome and I hope you'll continue to maintain it!

**Comment by enricocid** [comment]
Preference dialogs negative button is now translated :)

https://github.com/enricocid/Music-Player-GO/commit/52622f9f029bc08a5fb125eb67eb06f789a918ec

Here You will find an apk:

https://github.com/enricocid/Music-Player-GO/actions/runs/3321482677

Thank You :)

**Comment by lgjint** [comment]
> Preference dialogs negative button is now translated :)
> 
> [52622f9](https://github.com/enricocid/Music-Player-GO/commit/52622f9f029bc08a5fb125eb67eb06f789a918ec)
> 
> Here You will find an apk:
> 
> https://github.com/enricocid/Music-Player-GO/actions/runs/3321482677
> 
> Thank You :)

It works！

Thank You :)
