### ISSUE TITLE
Changing Orientation Changes Folder in Folder View

### ISSUE THREAD

**Issue by landry314** [enricocid/Music-Player-GO#495]
If you are in folder mode and inside a subfolder then when you tilt the phone enough to change its orientation you are magically transported up one folder higher in the directory. Well, actually, this is the root folder in the folder view so maybe that is where it is going; i have never tested it 2 levels deep. It goes to the root folder maybe.

Anyway, this is really annoying because I am lying in my bed a lot and the phone tilts too much and I lose my place as I am picking a song.

In fact, I want to just disable orientation change in general within this app. I want it always in portrait mode. I'd love this setting added.

I believe this is related to issue #273.

**Comment by enricocid** [comment]
Ok, gonna try to add an option to lock orientation 😄

**Comment by enricocid** [comment]
@landry314 

Try this:

https://drive.google.com/file/d/12b3FQ5oVsevxymlnYyktkKCTO6fyR06Y/view?usp=share_link

I added an option to lock orientation :)
