### ISSUE TITLE
[Q&A]: How does MPG choose the album art picture for an audio file ?

### ISSUE THREAD

**Issue by blockx** [enricocid/Music-Player-GO#499]
### What are You thinking?

Hi,

I have a music collection which includes 5 albums that are each ripped as a single .m4a audio file.  I have 5 individual album art files in .jpg and .png format, one for each audio file, but MPG currently only displays one of these for all of the audio files.  The album art files have names the same as the .m4a audio files but with the appropriate extension (.jpg or .png) instead of .m4a.  The 5 off .m4a files and the corresponding .jpg/.png album art files are all contained in a single directory.

My question is : how can I ensure that these audio files are displayed with the appropriate album art file in the MPG albums list ?  The .m4a files play fine...

Thanks,

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
MPGO picks the embedded picture (tags) :)

**Comment by blockx** [comment]
> MPGO picks the embedded picture (tags) :)

OK, but I discovered that it also puts an image file if it finds one in the containing directory and there are none embedded into the audio files.

Thanks for your reply,
