### ISSUE TITLE
if u join in the settings, can't go back anymore.

### ISSUE THREAD

**Issue by shirou-jeff** [enricocid/Music-Player-GO#5]
#### Expected behavior
The user expects to be able to enter the settings menu, and be able to go backwards if you don't want to modify something in the player.

#### Actual behavior
The user cannot enter the settings menu, and can go backwards if you do not want to modify something in the player. Because once inside the menu of options, there is no way to go backwards, leaving all the functions of the player disabled.

#### How to reproduce
- Download the [application](https://play.google.com/store/apps/details?id=com.iven.musicplayergo&hl=es-419&ah=HqyYSw2DG6vWMhAZpaB6xhREJnM). 
- Install. 
- Enter the Options menu and try to go backwards. 
- The option of going backwards is disabled whit the other functions of the player, like, pause, next or previous.

* Browser: Music Player GO V 2.3
* Operating system: Android 5.1.1

#### Recording Of The Bug
https://youtu.be/llpo_zbXpGA

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@shirou-jeff/if-u-join-in-the-settings-can-t-go-back-anymore">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by enricocid** [comment]
I added a close button and the possibility to close the popup using back button. Unfortunately popup behaviour is different on OEM interfaces, as usual... xd
