### ISSUE TITLE
[FR]: Remember sort preference between sessions.

### ISSUE THREAD

**Issue by S-Sajith** [enricocid/Music-Player-GO#501]
### What feature would you like to see?

I play music from my folders and I like the folders to be sorted by added first ( beacause I want the newly added songs to be on top ) . But everytime I sort it by added first and then close the app the folder reverts back to default sorting option. So please implement an option where I can change the default sort option or make the app remember sort preferences between sessions.

### What kind of level is this feature request?

Hmm, probably intermediate, can't know!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
I already have a partial implementation. Gonna try to add an option to select the default sorting for folders and albums too.
