### ISSUE TITLE
[FR]: Filename on Everywhere

### ISSUE THREAD

**Issue by RickyM7** [enricocid/Music-Player-GO#503]
### What feature would you like to see?

It would be great if the option to show the filename instead of the title working on everywhere. Now this option don't show the filename on the Notification Drawer and on popup warnings (when we are deleting the song from the queue, etc).

### What kind of level is this feature request?

Yo, it's simple!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enricocid** [comment]
This is already fixed. It will be available within the next few days.

**Comment by RickyM7** [comment]
> This is already fixed. It will be available within the next few days.

Thank you very much!
