### ISSUE TITLE
Fetch Latest Translations from the Weblate

### ISSUE THREAD

**Issue by ShareASmile** [enricocid/Music-Player-GO#513]
As the Title says, as i have done new transactions in "hi" Hindi

**Comment by enricocid** [comment]
Next release 😉

**Comment by ShareASmile** [comment]
I will try to do Indian Punjabi "pa" translations also on the weekends .

Hold on to that till , Thanks

**Comment by enricocid** [comment]
Next release will bring #132 (playlists) feature which will require time to be implemented.
So, take your time (there will be new strings for sure).
I usually warn users before pushing new release to give them the time to update translations (7 or more days) so don't worry 😉

**Comment by ShareASmile** [comment]
Translations Done 100% of "hi" Hindi & "pa" Punjabi(Indian).

@enricocid would you please fetch latest from weblate? 
Thank You.

**Comment by enricocid** [comment]
Done 🌝
