### ISSUE TITLE
random on one album ?

### ISSUE THREAD

**Issue by raph-tr** [enricocid/Music-Player-GO#52]
hi there
nice work done !
i found how to randomly play any songs on the device, any songs from one artist, but can not play songs from only one album of a given artist...
am i missing something or is not possible ?
if not possible, could it be implemented ?
regards
raf.

**Comment by enricocid** [comment]
It is not possible at the moment, but I can simply add this feature. Anyway, you have to wait a little as I'm still finishing the app rewriting in kotlin language😉

**Comment by enricocid** [comment]
**Added**. It will be available in next release
