### ISSUE TITLE
[Bug]: Playback speed resets after audio is over. 

### ISSUE THREAD

**Issue by HACKER097** [enricocid/Music-Player-GO#528]
### What happened?

I was trying to listen to an audiobook at 1.5x speed, but every time a chapter (or the file) ends, and it moves on to the next file in the playlist, the speed resets to 1x. It's a bit annoying to pick up my phone and change the speed again every 10 min.
 
I can see how this 'bug' might be useful to some, so maybe we can have a setting to toggle this on or off. 

### Version

4.4.23

### Device and Android version

Android 12

### Nice things

- [x] We can have

**Comment by enricocid** [comment]
I'm gonna make it persistent in the next release 😉

**Comment by HACKER097** [comment]
Aah, sorry. I'll close this issue. Thanks!
