### ISSUE TITLE
Open music from outside the app (Intents)

### ISSUE THREAD

**Issue by contrapunctus-1** [enricocid/Music-Player-GO#55]
It'd be nice if Music Player GO was offered for opening audio and video files e.g. from file managers (in the latter case it could just play the audio stream.)

**Comment by enricocid** [comment]
I already implemented this feature, and I will release as soon as but I will be able to improve the implementation😉

**Comment by gsrathoreniks** [comment]
Just wondering wether this issue has been resolved or not, as you said you already implemented but the issue is still OPEN.

**Comment by enricocid** [comment]
the feature is coming soon :) just need to fix some things

**Comment by enricocid** [comment]
Fixed. It will be included in next release

**Comment by contrapunctus-1** [comment]
Thanks! Re: videos, can't it just play the audio stream?

**Comment by enricocid** [comment]
I don't know, gonna investigate🕵️‍♂️
