### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hosseinabaspanah** [enricocid/Music-Player-GO#559]
### What happened?

Hello
Luri Bakhtiari's language is registered in Weblate as an LTR language, and for this reason, I have translated it for you with a left-to-right line especially for this language...

But I have now noticed that this language is mistakenly recognized as an RTL language in the program...

Please fix this problem...

### Version

4.4.24

### Device and Android version

Android 14

### Nice things

- [X] We can have

**Comment by enricocid** [comment]
MPGO already supports RTL languages. I can try to set it as RTL on weblate

**Comment by hosseinabaspanah** [comment]
> MPGO already supports RTL languages. I can try to set it as RTL on weblate

Hello
I am really sorry for the delay in replying to you

Please do not change the writing direction of this language in weblate because I have translated the project from left to right for you...

To solve this problem, it is enough to consider this language as an LTR language in the program...

**Comment by hosseinabaspanah** [comment]
Hi, this is a problem with weblate and I will report it to them...
