### ISSUE TITLE
Random playback / shuffle can not be disabled

### ISSUE THREAD

**Issue by bretzel15** [enricocid/Music-Player-GO#57]
First, thank you for this really nice audio player!

I just have a small problem: How do I disable the random playback? Everytime I select an album and start playback by clicking on the first song, it randomly chooses another one after the first. I would expect the player to consecutively play the album from track 1 over 2, 3, 4,... to the end.

Maybe I am just too stupid, but help is highly appreciated :)

**Comment by enricocid** [comment]
Hmmm, don't know, I'm abroad right now. I will investigate the issue as soon as I return home ;)

**Comment by enricocid** [comment]
I have the intention to implement this solution:

Actually, everytime you click shuffle button you will shuffle the songs according to navigation (when you're on homescreen you will shuffle all device song, when on artist's album the songs from it).
On 2nd click I want to disable shuffle and, at the same time, return to the previously played album, song + position.
Do you think it would be ok?

**Comment by enricocid** [comment]
I will close the issue and merge with #67 ;) discussion will move to there
