### ISSUE TITLE
Now Playing

### ISSUE THREAD

**Issue by gigabytedevelopersinc** [enricocid/Music-Player-GO#58]
First of all, nice project...
But, I would like to see a `Now Playing` layout as this
![screenshot_20190209-102408](https://user-images.githubusercontent.com/26210471/52520437-81f54080-2c6a-11e9-950f-1b981514d56f.png)
I happen to understand that you are not going to be pulling individual artwork image(s) for songs because you want Music Player GO to be as lightweight as possible and I totally understand. So, instead of having a fullscreen `Now Playing` layout as the one above, you could just get rid of the image (artwork) area and make the  `Now Playing` layout a bottomsheet that looks as if it's docked when it pops up. Something like this
![img_20190209_125517](https://user-images.githubusercontent.com/26210471/52520626-bddcd580-2c6b-11e9-9ca0-967cb20c45c4.jpg)
Well, point is we need a layout like that, something that provides the use of all the player controllers needed (Pause/Play, Forward, Next, Backward, Previous, Repeat-on/off, Shuffle-on/off), the `Now Playing` layout should also show the Song Name, Artiste Name and Album Name...

PS: The current `player_controls_panel` can still be the way it is. Just providing the ability to show the `Now Playing` layout when the `player_info` **LinearLayout** on the  `player_controls_panel` is clicked on...

**Comment by enwokoma** [comment]
Wow! This is essential. 
Something I would really love to see implemented

**Comment by enricocid** [comment]
The feature has been implemented. It will be available in MPGO 4.0 EX. Closing.

**Comment by enricocid** [comment]
![Screenshot_20190930-121002](https://user-images.githubusercontent.com/7274841/65869856-6c5c9480-e37b-11e9-9ecc-e1afdc411ec8.png)
