### ISSUE TITLE
Improve Navigation

### ISSUE THREAD

**Issue by gigabytedevelopersinc** [enricocid/Music-Player-GO#59]
Please, it would also be nice if you can provide us with the ability to change the way songs are listed on Music Player GO. The current way is by default listed and grouped/sorted by Artistes and I must say, this is not so fun at all...
I would suggest some kind of viewpager navigation that lets us navigate/switch between showing All Songs, Albums, Artistes (you can simply use the same current logic), Folders and if possible Genres too. This way someone who wishes to play all his songs at once (one at a time) can just toggle to the All Songs fragment from the tabbed layout and start playing.
You can make it look somewhat like this.
![screenshot_20190209-102357](https://user-images.githubusercontent.com/26210471/52520818-4eb4b080-2c6e-11e9-8869-0dedd9e09b68.png)
Something simple looking yet minimalistic.
In all honesty, this should really be implemented soonest!

**Comment by gigabytedevelopersinc** [comment]
Someone already request for something that relates to what am saying.. See here #45 
But, the person only requested for navigation by Folders... It would be really nice to have the options to navigate between All Songs, Albums, Artistes, as well as the Folders and if possible Genres too.

This would make the usability of Music Player GO to be much more simple, easy and very much straightforward too.

**Comment by enwokoma** [comment]
Interesting. I was about to make this request too. But anyways, it's something that is really needed on this app. Makes navigation easier.
A tabbed layout should do the job perfectly!

**Comment by enricocid** [comment]
Navigation improvement is a good request. Anyway, I won't reproduce that layout as I don't want my app to copy others. :)

**Comment by enricocid** [comment]
This one has been added (genres tab anyway won't be available). It will be available on 4.0.0 soon.
