### ISSUE TITLE
The player does not stop playing, even if you start a different player.

### ISSUE THREAD

**Issue by shirou-jeff** [enricocid/Music-Player-GO#6]
#### Expected behavior
It is expected that when you start another media player, the current song is paused.
#### Actual behavior
The media Player does not stop, even when other players start a song.

#### How to reproduce
- Download the [application](https://play.google.com/store/apps/details?id=com.iven.musicplayergo&hl=es-419&ah=HqyYSw2DG6vWMhAZpaB6xhREJnM). 
- Install. 
- Play a song of your liking. 
- Exit and start another playback with a different player. 
- The previous should stop, but it does not, it still sounds, distorting both audios.

* Browser: music player go V 2.3
* Operating system: Android 5.1.1

#### Recording Of The Bug
https://youtu.be/Jx9vEN3NDsM
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@shirou-jeff/the-player-does-not-stop-playing-even-if-you-start-a-different-player">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by enricocid** [comment]
Thanks, there is a problem with audio focus. It will be fixed in the next update :)
