### ISSUE TITLE
Bug on shuffle button. ( It does not shuffle songs)

### ISSUE THREAD

**Issue by darewealth** [enricocid/Music-Player-GO#64]
### Describe the Bug:
When I click on the shuffle icon on the app, it plays music and when I click again it will next the music.

### To Reproduce:

* Launch the app

* Slide the screen from where the play icon is to up

* Click the shuffle icon 

### Expected Behavior:
I expected that the shuffle button should work to enable playing a random song, and I should be able to disable when I want to.

### Recording Of The Bug
https://youtu.be/doEzbCkqsmY

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [3.5.2.5]

**Comment by darewealth** [comment]
@enricocid were you able to reproduce the bug? And when are you intending to work on it?

**Comment by enricocid** [comment]
Everytime you click the shuffle button, you will shuffle the music list (it's totally random, the fact that it switched to the next song is purely a case). I will let user disable the shuffle on 2nd click.

As stated here

https://github.com/enricocid/Music-Player-GO/issues/66

I will address all issues/requests once my familiar situation will get better or I'll have some rest from them. I'm experiencing some bigger problems right now I have to absolutely address and focus on.
I'm sorry, but You have to be patient.

**Comment by darewealth** [comment]
Thank you for the lengthy explanation, and I understand everything, I hope it gets fixed as soon as you can work on it. :+1:

**Comment by enricocid** [comment]
I'm gonna close this issue as there is already a thread. 
The discussion will continue here #67
