### ISSUE TITLE
Add an inbuilt equalizer to the Music Player Go application 

### ISSUE THREAD

**Issue by chrisbarth01** [enricocid/Music-Player-GO#66]
#### Components
The component I want to suggest is an inbuilt equalizer for Music Player Go app

#### Proposal Description
An equalizer which is an electronic equipment that reduces frequency distortion is a necessary component in a music player application. This component allows users to adjust the music to whatever way they want it; rock, jazz, bass blast, etc. A music player without this feature isn't complete at all. After clicking the 'equalizer' option on the Music Player Go app, I found out that there was no equalizer in the app. So, I am suggesting that an inbuilt equalizer should be added to the music app. This equalizer can be designed in any form but should be of good quality which can serve the user appropriately.

#### Mockups / Examples
Below is a mock-up of my suggestion, it is a screenshot from another music player application 

---
![20190419-114816](https://user-images.githubusercontent.com/49325171/56421547-f7007a00-629a-11e9-83cc-68fbbcdeea6b.png)
---
![20190419-114822](https://user-images.githubusercontent.com/49325171/56421565-0a134a00-629b-11e9-9311-968acda3c27f.png)

---

#### Benefits
- If implemented, this feature will help users to adjust their music to however way they want it.
- It will also attract more users who are interested in equalizing their music

#### Conclusion 
This component may be a bit common but it is a very important component for a music player application.
I hope the developers can consider adding this component.

**Comment by chrisbarth01** [comment]
Can the developer do something about this?

**Comment by enricocid** [comment]
Yes, but since I'm alone you have to patiently wait 😆 I'm sorry for not being able to respond to user requests quickly/continuously but I'm in a very difficult/delicate familiar situation ... once something will resolve I will work on all feature requests. Thanks for the comprehension

**Comment by bullheadandplato** [comment]
https://github.com/bullheadandplato/AndroidEqualizer you can use this or specify to me where you want to add it and I will do PR

**Comment by enricocid** [comment]
> https://github.com/bullheadandplato/AndroidEqualizer you can use this or specify to me where you want to add it and I will do PR

I'm not sure, but I was thinking to add an option in settings to toggle system/custom equalizer, that will be opened from np dialog. Anyway, You can take Your time if You want to propose this change as my nexus 5 is not booting anymore and it will take some time to get a device for test purposes...

**Comment by enricocid** [comment]
I'm trying to implement the equalizer but I get this error:

`C:\Users\USER\.gradle\caches\transforms-2\files-2.1\6fa8f40854b8ae786e699d427205b95b\AndroidEqualizer-2.1\res\layout\dialog_fragment_equalizer.xml:15: AAPT: error: resource drawable/ic_close_black_24dp (aka com.iven.musicplayergo:drawable/ic_close_black_24dp) not found.`

and 

`java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3`

**Comment by bullheadandplato** [comment]
You can add close icon in your drawable with same name

**Comment by enricocid** [comment]
@bullheadandplato can I convert your eq to kotlin and add it to the project to customize to fit the app ?

**Comment by bullheadandplato** [comment]
yes, why not!

**Comment by enricocid** [comment]
> Hi, Check this [bullheadandplato@155ef30](https://github.com/bullheadandplato/Music-Player-GO/commit/155ef307ef6ce907ba36a361629b304551c47eaa) . If it feels okay I will do PR. Thanks.
> It look like this
> ![Screenshot_1591819973](https://user-images.githubusercontent.com/15232745/84313976-bf305200-ab80-11ea-8b37-8b15f77a806b.png)
> ![Screenshot_1591819743](https://user-images.githubusercontent.com/15232745/84313985-c48d9c80-ab80-11ea-90ab-ba73689a769f.png)

absolutely, but I suggest you to wait a little as I'm working on some major changes. I will notify You here as soon as possible ;)

**Comment by enricocid** [comment]
@sethtara as You can see in the comment above there's already a solution by @bullheadandplato for the eq.
Since I'm going to introduce some major changes I asked to @bullheadandplato to wait a little until I push these changes.

Unfortunately I can't focus on MPGO in this period. I will return to development as soon as I have solved some personal issues. Thanks

**Comment by enricocid** [comment]
@bullheadandplato the equalizer works great
I'm starting conversion to kotlin and adaptation to the app's design today.
Hope I will be able to include the eq in the upcoming update.

**Comment by enricocid** [comment]
@bullheadandplato 
Can't access Settings.equalizerModel 
It says it is private . Can't save settings 😁
Could you fix?

**Comment by bullheadandplato** [comment]
I will fix it ASAP :+1:

**Comment by enricocid** [comment]
> I will fix it ASAP 👍

Thanks. It would be great, so I can include in the next update.
Could you fix the missing drawable (ic_close_black_24dp) too?

**Comment by bullheadandplato** [comment]
Yes that is is fixed. I will check again everything.

**Comment by bullheadandplato** [comment]
> @bullheadandplato
> Can't access Settings.equalizerModel
> It says it is private . Can't save settings grin
> Could you fix?

Can yo please explain more or post code of how you was trying to save `Settings`?

**Comment by enricocid** [comment]
> > @bullheadandplato
> > Can't access Settings.equalizerModel
> > It says it is private . Can't save settings grin
> > Could you fix?
> 
> Can yo please explain more or post code of how you was trying to save `Settings`?

I'm trying to implement this method in my app

https://github.com/bullheadandplato/AndroidEqualizer/blob/9e738b13436ae8dbedbfcb0d6054585f1ab05528/app/src/main/java/com/bullhead/androidequalizer/MainActivity.java#L104

but 

Settings.**equalizerModel** is private

https://github.com/bullheadandplato/AndroidEqualizer/blob/9e738b13436ae8dbedbfcb0d6054585f1ab05528/app/src/main/java/com/bullhead/androidequalizer/MainActivity.java#L107

Thnks :)

**Comment by bullheadandplato** [comment]
Can you update equalizer dependency to `2.2` and see If issue resolves.
` implementation 'com.github.mosamabinomar:AndroidEqualizer:2.2'`

**Comment by enricocid** [comment]
> Can you update equalizer dependency to `2.2` and see If issue resolves.
> ` implementation 'com.github.mosamabinomar:AndroidEqualizer:2.2'`

I can access now. Thanks, gonna integrate tomorrow :)

**Comment by enricocid** [comment]
I ended up writing a super simple Kotlin Equalizer (~250 lines of code) fragment today, to maintain the consistency with the theme 😉👍🏻

It works great but there are some things to fix.
It will available in the next update (hopefully the next week).

Thanks @bullheadandplato, I learned so much from your equalizer

![Screenshot_20201107-190438.png](https://user-images.githubusercontent.com/7274841/98448420-28b28d80-212c-11eb-956e-27cc30d6354a.png)

**Comment by enricocid** [comment]
Equalizer has been added.

It will be available in the next update!

![Screenshot_20201108-172049](https://user-images.githubusercontent.com/7274841/98470636-5c062280-21e7-11eb-9976-8ed63830405a.png)

Closing ...

**Comment by alekksander** [comment]
And it wrongly detects my system settings and I can't use built in equalizer anymore :( this shouldn't be automated.

**Comment by enricocid** [comment]
> And it wrongly detects my system settings and I can't use built in equalizer anymore :( this shouldn't be automated. 

What you mean? Are you able to use the built in one?

Do you have audio FX as system Equalizer? 
Device? Android version? 🙂

PS: built in and system Equalizer are basically the same. Audio output is the same. They use the same system libraries to produce effects.

Provide me with the details above and I will investigate the issue.
👍🏻

**Comment by alekksander** [comment]
MPGO built in equalizer was the reason i left other  player. in previous MPGO version i was able to use it's equalizer, now i am not. android eq is disabled (i never enable it). this is android version is unmodified 8.1. i can check previous mgpo versions and check since when it's like that if You want me to do so.
thanks for interest!

**Comment by enricocid** [comment]
> MPGO built in equalizer was the reason i left other player. in previous MPGO version i was able to use it's equalizer, now i am not. android eq is disabled (i never enable it). this is android version is unmodified 8.1. i can check previous mgpo versions and check since when it's like that if You want me to do so.
> thanks for interest!

So You have disabled system equalizer from Settings but You can't open the mpgo equalizer?
Which is a bug like You said.

Do You prefer an option to decide the equalizer to use?

I'm going to post some test apk then as I don't have devices with a system equalizer unfortunately.

Thanks for having reported the issue and for Your patience. 👍🏻

**Comment by alekksander** [comment]
actually i just made sure about the equalizer and i don't have one in my android phone as well (sorry about that, i had it in previous device, therefore the confusion). anyhow i cannot use mpgo one. i think option to manually be able to choose eq in mpgo is the way to go, but i don't mind it automated as long as it works and i'm able to use it :)

**Comment by RickyM7** [comment]
@enricocid @alekksander Sorry for the intrusion but my phone has a built-in equalizer. I just disabled it to test MPGO detection and this is working perfectly. MPGO uses system eq when it is enabled and uses eq imbued when system eq is disabled.
If something related to this needs to be tested, I can test.

Device: Redmi Note 4 (Miui 11 - Android 7.0).

**Comment by enricocid** [comment]
@alekksander @RickyM7 
I'm going to add an option to let the user choose between mpgo equalizer and the system one, so You do not have to disable the system equalizer.
If You disable the system equalizer, the option will be set to enabled and mpgo one will be opened on click.

@RickyM7 what You mean by reset? Reset to flat? If yes, you can selected flat from presets :)

**Comment by RickyM7** [comment]
> what You mean by reset? Set all the indicators to zero? If yes, you can simply select flat from the presets :)

@enricocid It would be for no preset to be changed. So if you started changing some value, a new option called "Custom" would appear. This is what happens in most eqs. I'm sorry if the explanation got confusing.
