### ISSUE TITLE
Shuffle features improvements

### ISSUE THREAD

**Issue by cckole** [enricocid/Music-Player-GO#67]
### Describing the bug

I played a song and clicked on the play next button to play the next song but it restarts the current music. Pressing the play previous song button also does the same thing.

### Expected behavior

I expected the app to play the next or previous song when I clicked on the two buttons separately.

### Steps to reproduce the bug

After launching and entering the app

1. Click on any song to play 

2. While the music is playing, click on the play next button, the current music will restart. Try it with the play previous button too. You will get the same answer.

### App and device version

***Device used***: Tecno spark K7   
     Android 7.0
***App version***:  3.5.2.5

Other threads on this issue:

#57 
#64

**Comment by enricocid** [comment]
Is it the only song of the album?
If so, then it's normal.
In next versions I will skip to next album when album is finished 😆

**Comment by cckole** [comment]
Alright.. Thanks..

**Comment by enricocid** [comment]
This feature has been enhanced in the upcoming version (4.0.0) I'm about to release within this week. If you have any problems you can reopen the issue or open a new one to let me know. Thanks.
