### ISSUE TITLE
Resume on Headset reconnect

### ISSUE THREAD

**Issue by stonerl** [enricocid/Music-Player-GO#69]
Would it be possible to continue playback when a headset (wired or bluetooth) is reconnect?

**Comment by enricocid** [comment]
I'm working this week, I will have a look into this problem asap.
Thanks for reporting 😆

**Comment by gnclmorais** [comment]
Related to this issue, can we have a setting where we can turn this feature off, please? The player keeps popping up when I want to user other audio apps (like Audible, for example).

**Comment by enricocid** [comment]
Ok. It will be added an option in next MPGO iteration

**Comment by enricocid** [comment]
This one has been added, will be available in next MPGO iteration. Won't close the issue, I'm gonna post a test apk later

**Comment by enricocid** [comment]
test apk updated

**Comment by enricocid** [comment]
This one is available in 4.0.0 version I'm about to release so I'm going to close. I can't test this feature with Bluetooth devices but it is working good with wired ones.
Open a new issue if you have any problems with the upcoming version..Thanks
