### ISSUE TITLE
Add online music botton and favourite botton to this app

### ISSUE THREAD

**Issue by pzdawood** [enricocid/Music-Player-GO#70]
***proposal***
My suggestion is to add ***online music botton*** and ***favourite***  the music player-go so that the user can gat advanced benefits from this app.
***Examples***
After adding  favourite botton
![PicsArt_05-19-11 31 55](https://user-images.githubusercontent.com/38599784/57986192-8c0bb400-7a8f-11e9-9bbe-41adc53a77cb.png)
After adding online music botton
![PicsArt_05-19-11 33 05](https://user-images.githubusercontent.com/38599784/57986203-a47bce80-7a8f-11e9-9d3d-cb830292aeba.png)
After adding both these features 
![PicsArt_05-19-11 34 16](https://user-images.githubusercontent.com/38599784/57986224-beb5ac80-7a8f-11e9-85f5-d2843a45c8ba.png)
The secreeshot of the app that have both these features
![Screenshot_2019-05-19-23-25-03-291_com miui player](https://user-images.githubusercontent.com/38599784/57986232-e3aa1f80-7a8f-11e9-8a62-8141626ebec8.png)
***Benefits**
1.The benefit of adding online music botton is that the user can search and song from the app and listen without download the song if the user loves the sing he can also download the song from this app. 
 2.benefits of favourite botton is that the user can put the his favourite song in the favourite list and when he wants to listen them he directely opens the favourite list and listen the song without searching from all song. This will lead to less loss of time and extra efforts.

**Comment by enricocid** [comment]
Thanks for suggestion, this one should be pretty easy to add. Will add as soon as I get a smartphone (got my primary/test smartphone stolen at the workplace :( ). Pretty unfortunate moment...

**Comment by pzdawood** [comment]
Ok sir
