### ISSUE TITLE
Bluetooth pause resumes playback

### ISSUE THREAD

**Issue by tsunadegodaime** [enricocid/Music-Player-GO#72]
When music is playing via Bluetooth earphones (Redmi Airdots) I press the button "pause" it pauses music and after a second, playback continues by itself.

**Comment by enricocid** [comment]
Sorry for late in reply. Gonna buy bluetooth earphones and fix the issues asap

**Comment by enricocid** [comment]
Hello,

as suggested by @stonerl I implemented media buttons receiver in MPGO 4.0.0. As I can't buy new devices to test, I wrote this small utility that simulates broadcasts MPGO should receive and handle.

https://github.com/enricocid/android-media-buttons-test

I'm about to release MPGO 4.0.0 and gonna close this issue as MPGO is now ready to handle these events.
You can reopen the issue if the problem persists. Thanks
