### ISSUE TITLE
App crashed immediately after launch

### ISSUE THREAD

**Issue by SandBlock4** [enricocid/Music-Player-GO#73]
I reported issue #71, where the app crashes immediately after launch. I updated the app to the newest version on F-Droid (3.5.2.7), hoping the update will fix the issue but it still crashes in a similar way. May be related to issue #62. 
Here is the crash log for 3.5.2.7

### Logcat
```
07-20 21:40:33.605  1286  1305 I StatusBarDisable: setFlags what=0 which=1 pkg=Window{e1ee663 u0 com.iven.musicplayergo/com.iven.musicplayergo.MainActivity}
07-20 21:40:33.613   733   854 W JankService: processEntry, not beta version or commercial log off
07-20 21:40:33.620 24090 24090 D AndroidRuntime: Shutting down VM
07-20 21:40:33.620 24090 24090 E AndroidRuntime: FATAL EXCEPTION: main
07-20 21:40:33.620 24090 24090 E AndroidRuntime: Process: com.iven.musicplayergo, PID: 24090
07-20 21:40:33.620 24090 24090 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:534)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
07-20 21:40:33.620 24090 24090 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        ... 1 more
07-20 21:40:33.620 24090 24090 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: audioArtist must not be null
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at android.os.AsyncTask.get(AsyncTask.java:543)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at c.c.a.b.d$b.<init>(:1)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at c.c.a.b.d.a(Unknown Source:4)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at c.c.a.m.A(:13)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at c.c.a.d.onServiceConnected(:7)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1918)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1950)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:891)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7539)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        ... 3 more
07-20 21:40:33.620 24090 24090 E AndroidRuntime: Caused by: java.lang.IllegalStateException: audioArtist must not be null
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at c.c.a.b.d$a.doInBackground(:1)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:334)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-20 21:40:33.620 24090 24090 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)
07-20 21:40:33.620 24090 24150 I Process : Sending signal. PID: 24090 SIG: 9
07-20 21:40:33.687  1286  1424 W InputDispatcher: channel 'e1ee663 com.iven.musicplayergo/com.iven.musicplayergo.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-20 21:40:33.687  1286  1424 E InputDispatcher: channel 'e1ee663 com.iven.musicplayergo/com.iven.musicplayergo.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-20 21:40:33.692  1286  1394 I WindowManager: WIN DEATH: Window{e1ee663 u0 com.iven.musicplayergo/com.iven.musicplayergo.MainActivity}
07-20 21:40:33.692  1286  1394 V WindowManager: removeIfPossible: Window{e1ee663 u0 com.iven.musicplayergo/com.iven.musicplayergo.MainActivity}
07-20 21:40:33.692  1286  4150 I ActivityManager: Process com.iven.musicplayergo (pid 24090) has died: fore TOP
07-20 21:40:33.692  1286  1394 W InputDispatcher: Attempted to unregister already unregistered input channel 'e1ee663 com.iven.musicplayergo/com.iven.musicplayergo.MainActivity (server)'
07-20 21:40:33.692  1286  1308 W libprocessgroup: kill(-24090, 9) failed: No such process
07-20 21:40:33.692  1286  4150 D ActivityManager: cleanUpApplicationRecord app: ProcessRecord{9db0b56 24090:com.iven.musicplayergo/u0a209}, app.bad: false, restarting: false, allowRestart: true
07-20 21:40:33.692  1286  1308 I libprocessgroup: Successfully killed process cgroup uid 10209 pid 24090 in 0ms
07-20 21:40:33.692  1286  4150 W ActivityManager: Scheduling restart of crashed service com.iven.musicplayergo/.PlayerService in 1000ms
07-20 21:40:33.692   554   554 I Zygote  : Process 24090 exited due to signal (9)
07-20 21:40:33.693  1286  4150 W ActivityManager: Force removing ActivityRecord{e36f400 u0 com.iven.musicplayergo/.MainActivity t1155}: app died, no saved state
```
Tried reinstalling but it still crashes.
* OS: Android 9

**Comment by enricocid** [comment]
Hi, could you try this one?

https://drive.google.com/file/d/1DP1fvRMK00N7YLUIPUMG9MOP9f-MbWD-/view?usp=sharing

**Comment by SandBlock4** [comment]
Still not working unfortunately...
```
07-21 20:47:30.671  1286  1305 I StatusBarDisable: setFlags what=0 which=1 pkg=Window{538246c u0 com.iven.musicplayergo/com.iven.musicplayergo.MainActivity}
07-21 20:47:30.678 24729 24795 W System.err: java.lang.IllegalStateException: audioAlbum must not be null
07-21 20:47:30.678 24729 24795 W System.err:    at c.c.a.b.d$a.doInBackground(:1)
07-21 20:47:30.678 24729 24795 W System.err:    at android.os.AsyncTask$2.call(AsyncTask.java:334)
07-21 20:47:30.678 24729 24795 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-21 20:47:30.678 24729 24795 W System.err:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
07-21 20:47:30.678 24729 24795 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-21 20:47:30.678 24729 24795 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-21 20:47:30.678 24729 24795 W System.err:    at java.lang.Thread.run(Thread.java:784)
07-21 20:47:30.678 24729 24729 D AndroidRuntime: Shutting down VM
07-21 20:47:30.678 24729 24795 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
07-21 20:47:30.678 24729 24795 E AndroidRuntime: Process: com.iven.musicplayergo, PID: 24729
07-21 20:47:30.678 24729 24795 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:355)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)
07-21 20:47:30.678 24729 24795 E AndroidRuntime: Caused by: d.f: lateinit property mCategorizedMusic has not been initialized
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at c.c.a.b.d$a.doInBackground(:1)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:334)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-21 20:47:30.678 24729 24795 E AndroidRuntime:        ... 4 more
07-21 20:47:30.678 24729 24729 E AndroidRuntime: FATAL EXCEPTION: main
07-21 20:47:30.678 24729 24729 E AndroidRuntime: Process: com.iven.musicplayergo, PID: 24729
07-21 20:47:30.678 24729 24729 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:534)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
07-21 20:47:30.678 24729 24729 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        ... 1 more
07-21 20:47:30.678 24729 24729 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: d.f: lateinit property mCategorizedMusic has not been initialized
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at android.os.AsyncTask.get(AsyncTask.java:543)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at c.c.a.b.d$b.<init>(:1)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at c.c.a.b.d.a(Unknown Source:4)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at c.c.a.m.A(:13)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at c.c.a.d.onServiceConnected(:7)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1918)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1950)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:891)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7539)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        ... 3 more
07-21 20:47:30.678 24729 24729 E AndroidRuntime: Caused by: d.f: lateinit property mCategorizedMusic has not been initialized
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at c.c.a.b.d$a.doInBackground(:1)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:334)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-21 20:47:30.678 24729 24729 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)
07-21 20:47:30.679 24729 24729 I Process : Sending signal. PID: 24729 SIG: 9
07-21 20:47:30.687  1286  6061 W ActivityManager:   finishTopCrashedActivityLocked Force finishing activity com.iven.musicplayergo/.MainActivity
07-21 20:47:30.690  1286  1305 I StatusBarDisable: setFlags what=0 which=1 pkg=Window{538246c u0 com.iven.musicplayergo/com.iven.musicplayergo.MainActivity}
```

**Comment by enricocid** [comment]
https://drive.google.com/open?id=1a-c3p1UlOTuI2ne6_xZ7lP528q8IY83T

**Comment by qirsanb** [comment]
Having same issue, android 9. The above drive links are not working either.

**Comment by enricocid** [comment]
Device? 
Need to know as on my Android one devices running pie I'm not experiencing these problems.

Gonna post some apk within the next hour anyway :)

**Comment by SandBlock4** [comment]
Tried the apk from the second link some time ago, I don't see any obvious error scanning through logcat, but the application quits after showing 'No music found on your phone!' (I did not store my music in the default directory)
![Untitled](https://user-images.githubusercontent.com/30970698/62004490-6e765d00-b158-11e9-9c01-4a8066b6ec5b.png)
Copying music to my default music directory does not help.
* Phone: Huawei Mate 9

**Comment by enricocid** [comment]
There's something wrong with music fetch...

try this 

https://drive.google.com/open?id=1WY-dCVg0zoOan5baJrrIrLHaE-W23fpP

**Comment by qirsanb** [comment]
Requested access.

**Comment by enricocid** [comment]
try now

https://drive.google.com/file/d/1WY-dCVg0zoOan5baJrrIrLHaE-W23fpP/view?usp=sharing

**Comment by qirsanb** [comment]
keeps stopping.

**Comment by enricocid** [comment]
log?

**Comment by qirsanb** [comment]
Sorry but I don't have a rooted device.

**Comment by enricocid** [comment]
,try this:
https://drive.google.com/file/d/1nA0tVWG9ksp1RKAqFLGnc-jfcHoeDDWo/view?usp=sharing

You don't need root to get a log.

- Get platform tools from here

https://developer.android.com/studio/releases/platform-tools

- Open cmd terminal inside that folder

- Enable ADB on yor device, from developers options

- Run this command, and open the app
adb logcat -v long > mpgo.txt

- Once crashed press ctrl + c to end the process

- get the txt file and send here

**Comment by qirsanb** [comment]
Will get to you once I'll be on pc.

**Comment by qirsanb** [comment]
[ 07-28 15:11:13.471  6370: 6370 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.iven.musicplayergo, PID: 6370
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: audioArtist must not be null
	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
	at android.os.AsyncTask.get(AsyncTask.java:542)
	at com.iven.musicplayergo.b.d$b.<init>(Unknown Source:17)
	at com.iven.musicplayergo.b.d.a(Unknown Source:7)
	at com.iven.musicplayergo.a.J(Unknown Source:60)
	at com.iven.musicplayergo.a$e.onServiceConnected(Unknown Source:96)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	... 3 more
Caused by: java.lang.IllegalStateException: audioArtist must not be null
	at com.iven.musicplayergo.b.d$a.doInBackground(Unknown Source:129)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


[ 07-28 15:13:27.362  6860: 6884 E/AndroidRuntime ]
FATAL EXCEPTION: AsyncTask #1
Process: com.iven.musicplayergo, PID: 6860
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: audioArtist must not be null
	at com.iven.musicplayergo.b.d$a.doInBackground(Unknown Source:129)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more


[ 07-28 15:34:41.151 11800:11800 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.iven.musicplayergo, PID: 11800
d.b
	at c.c.a.b.e.a(:6)
	at com.iven.musicplayergo.MainActivity.z(:9)
	at c.c.a.g.onServiceConnected(:6)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at `com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)```

**Comment by qirsanb** [comment]
there's 2mb file, but i have managed to get one you need.

**Comment by enricocid** [comment]
Try the latest release and let me know :) I need also another info: device.
Thanks.

https://github.com/enricocid/Music-Player-GO/releases/tag/v3.6

**Comment by qirsanb** [comment]
Already added device in my first cmt. :)

**Comment by qirsanb** [comment]
`[ 07-28 20:08:12.279 22745:22745 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.iven.musicplayergo, PID: 22745
d.b
	at c.c.a.b.e.a(:6)
	at com.iven.musicplayergo.MainActivity.z(:9)
	at c.c.a.g.onServiceConnected(:6)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

[ 07-28 20:56:12.083 26319:26319 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: org.fdroid.fdroid, PID: 26319
java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.fdroid.fdroid.data.App.packageName' on a null object reference
	at org.fdroid.fdroid.NotificationHelper.shouldIgnoreEntry(NotificationHelper.java:148)
	at org.fdroid.fdroid.NotificationHelper.updateStatusLists(NotificationHelper.java:138)
	at org.fdroid.fdroid.NotificationHelper.access$100(NotificationHelper.java:36)
	at org.fdroid.fdroid.NotificationHelper$1.onReceive(NotificationHelper.java:87)
	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

Not working.

**Comment by enricocid** [comment]
Gonna post apk later

**Comment by enricocid** [comment]
There's some problem with service connection on your device

try this
https://drive.google.com/file/d/1fP9GbMIhWxkudGBehNLmuOILcU3XWP5V/view?usp=sharing

**Comment by qirsanb** [comment]
still not working. Service connection? Does it mean I'm the only one affected or all m1 devices?

**Comment by enricocid** [comment]
The service required to play music even when you remove the app from recents. :) For some reason it is not working.

Could you install thr PlayStore versione and once crashed send me a crash report? (When an app crashes play store should show you a dialog for reporting crash). So I have better instruments to identify the problem on Gplay dev console. Thanks.

**Comment by enricocid** [comment]
@qirsanb 

Here are some test apks (different approaches). Please test these 4 and tell me if one of these work.
Do not install apk on top of others, always uninstall and install the new one.

Thanks.

[#1](https://drive.google.com/file/d/1INQtZSZJToMRda1pFJeRYZVwDP9fFTrs/view?usp=sharing)

[#2](https://drive.google.com/file/d/1Ln6x3GRxbiHJzARe2x_2RWNdWEC3Ad0G/view?usp=sharing)

[#3](https://drive.google.com/file/d/1CtrkXj9BSZYj1SNGLtSasTXDkHo1BLhE/view?usp=sharing)

[#4](https://drive.google.com/file/d/1F93LlhQ10BLcMMtKtywb6VyHxfiWSK8t/view?usp=sharing)

**Comment by qirsanb** [comment]
None of these four working and I have sent feedback through Play Store.

**Comment by SandBlock4** [comment]
3.6.4.1 on Fdroid solve this for me, no more crashes
