### ISSUE TITLE
Music showing artist

### ISSUE THREAD

**Issue by ScrPits** [enricocid/Music-Player-GO#76]
Issue: playing all my songs.
currently I see artist folders which then play songs in that one "folder"
Perfered method: All songs in one area (longer then 45 sec) (no folders)

**Comment by enricocid** [comment]
Could You elaborate better? :)

**Comment by enricocid** [comment]
All songs tab has been Implemented. Will be available in 4.0 EX version. Closing.

**Comment by enricocid** [comment]
![Screenshot_20190930-121019](https://user-images.githubusercontent.com/7274841/65870013-a88ff500-e37b-11e9-9a7f-727fa92f74ac.png)

Default sorting will do the trick

**Comment by enricocid** [comment]
![Screenshot_20190930-121026](https://user-images.githubusercontent.com/7274841/65870183-e12fce80-e37b-11e9-8dbd-98b6141bdfc6.png)
