### ISSUE TITLE
Restore sort by age option.

### ISSUE THREAD

**Issue by xaiki** [enricocid/Music-Player-GO#77]
MPG used to do exactly what I needed: it'd provide me a list of my music files sorted by modification date. I'd go out, get some fresh music and be able to listen to it in the order I had gotten it. all my music was just randomly thrown in a folder, and it worked.

A few versions ago MPG started sorting alfabetically, so now I have all my numbered songs at the begining, and when I add new music I actually have to go looking for it.

I understand you're looking for a minimal ui, but may a suggest a sort button next to the folder shuffle one ?

Thanks for you amazing work and hope your family issues and relocation are all settled now.

**Comment by enricocid** [comment]
Sort options then?
Ok, I'll see what I can do :)

**Comment by enricocid** [comment]
This feature will be available in MPGO 4.0 EX. Closing.

**Comment by enricocid** [comment]
![Screenshot_20190930-121019](https://user-images.githubusercontent.com/7274841/65870197-eb51cd00-e37b-11e9-8f9e-0e7bb48b5d1c.png)
Default option will do the trick.

**Comment by xaiki** [comment]
Great ! 
You already made me happy !
Maybe instead of 'default' it should be 'by date' ?

Sent with  FairEmail [https://email.faircode.eu/]  , an open source, privacy friendly email app for Android

Mon Sep 30 05:56:26 GMT-04:00 2019 enricocid <notifications@github.com>:
