### ISSUE TITLE
Next song does not play automatically

### ISSUE THREAD

**Issue by Wilker-a** [enricocid/Music-Player-GO#79]
in the version 3.6.4.2 (under Android 5.1.1), the next song in the playlist does not play automatically. either you have to press 'next' or 'shuffle' or in another song for it to play the next song.

**Comment by x-jokay** [comment]
Can confirm this for `3.6.4.3` on Android `8.0.0` as well.

**Comment by enricocid** [comment]
Gonna publish an update asap to fix the issue. Thanks for reporting (sorry for late in reply)
