### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by abdulmalikkhan655** [enricocid/Music-Player-GO#8]
Hello, @enricocidI want to contribute in "Music-Player-GO" so i  want to designed a new logo for "Music-Player-GO" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by enricocid** [comment]
Thanks, but I'm ok with actual icon. I think Julian did a great work. 
Anyway, if You have any idea for the UI you're welcome
https://github.com/enricocid/Music-Player-GO/issues/7

**Comment by abdulmalikkhan655** [comment]
what is UL  sir

**Comment by abdulmalikkhan655** [comment]
i have no idea sorry bro
