### ISSUE TITLE
Precise volume control

### ISSUE THREAD

**Issue by harisont** [enricocid/Music-Player-GO#81]
Hey, I am adapting your app to my own needs and the first thing I did was to write code so that the user can adjust the volume more precisely (100 steps).
I don't know if you are interested in a feature such as this one, as I see you are keeping everything very minimal (which I appreciate, it's the reason why I chose to customize this player and not another), but in case you are I can make a pull request. Let me know!

**Comment by enricocid** [comment]
Thanks! It'd be awesome to have such a feature.😆

**Comment by harisont** [comment]
Great! I'll improve a certain little thing later on today andmake a PR then!

**Comment by enricocid** [comment]
Super! Ok, don't worry, take your time 😆👌

**Comment by enricocid** [comment]
Thanks :)

**Comment by harisont** [comment]
Non c'è di che!
