### ISSUE TITLE
Navbar should be black in dark mode

### ISSUE THREAD

**Issue by Jnss98b** [enricocid/Music-Player-GO#86]
Would be nice if you could just make this app draw edge to edge instead too

![Screenshot_20190915-013142](https://user-images.githubusercontent.com/24306400/64916994-b5e09900-d758-11e9-92cd-36a40c37815d.jpg)

**Comment by enricocid** [comment]
I'm investigating the issue and it's weird as it is already black in dark theme

https://github.com/enricocid/Music-Player-GO/blob/7a1d7c512812f1cdedad2309c6c960d89d4a229c/project/app/src/main/res/values/styles.xml#L19

Is it navigation bar? or the new gestures navigation?

**Comment by Jnss98b** [comment]
Does is really matter which navigation method it is when your app isn't even edge to edge yet? They act pretty much the same unless you actually draw your app content under the navbar.

**Comment by Jnss98b** [comment]
Are you using the default navbar color? Devices like from Samsung and OnePlus have white navbars as the default color unlike Pixels and the rest which default to black

**Comment by Jnss98b** [comment]
I'm not Android Q though. That's just a regular navbar. The problem here it seems is that you're using the default navbar color provided by the system here because you thought it would be black

**Comment by Jnss98b** [comment]
But some devices have white or light gray as the default navbar colors

**Comment by enricocid** [comment]
> I'm not Android Q though. That's just a regular navbar. The problem here it seems is that you're using the default navbar color provided by the system here because you thought it would be black like tons of other apps out there

Because I'm forcing black navbar in the app's dark theme. In fact, it is black on all the devices I'm using for testing (Nexus 5 running android 8, Redmi 3 running Lineage OS Android 7.1.1 and Mi A2 lite running Android 9).

```
<style name="AppThemeInverted" parent="Theme.MaterialComponents.NoActionBar">
        <item name="icon_color">@android:color/white</item>
        <item name="card_color">@android:color/black</item>
        <item name="controls_panel_stroke">@color/gray_900</item>
        <item name="android:windowBackground">@android:color/black</item>
        **<item name="android:navigationBarColor">@android:color/black</item>**
        <item name="android:windowLightStatusBar" tools:targetApi="23">true</item>
        <item name="android:windowAnimationStyle">@style/WindowAnimationTransition</item>
    </style>
```

Could You please share with me info about Android version and ROM you're using?

**Comment by Jnss98b** [comment]
No luck there :(

![Screenshot_20191115-075509](https://user-images.githubusercontent.com/24306400/68945422-5e71a000-077e-11ea-868a-2a4625249f03.jpg)

**Comment by Jnss98b** [comment]
I'm just running the stock OOS 9 that comes with the OP6. 9.0.3 to be specific

**Comment by enricocid** [comment]
Ok, don't worry. Gonna solve somehow :P

**Comment by Jnss98b** [comment]
> Because I'm forcing black navbar in the app's dark theme (android:navigationBarColor). In fact, it is black on all the devices I'm using for testing (Nexus 5 running android 8, Redmi 3 running Lineage OS Android 7.1.1 and Mi A2 lite running Android 9).

Aww man this is not the first time this has happen (navbar color doesn't change to what the app asked for on oos). Dw man this is oneplus' fault then, although I think you can work around that somehow because some devs managed to do just that (telegram is one example)

**Comment by Jnss98b** [comment]
I thought you are one of the majority of app devs that don't bother to change the navbar color (looking at you, spotify). But yeah, you're just a victim of oneplus breaking app compatibility lol.

**Comment by Jnss98b** [comment]
Maybe you can try extending the app edge-to-edge too? Then you wouldn't have to deal with changing the navbar color for different themes

**Comment by enricocid** [comment]
I can, but you still need to set navbar color to transparent

**Comment by Jnss98b** [comment]
Yes but that's a one-time thing and that hasn't failed with any app on my device

**Comment by enricocid** [comment]
Hello,

as You suggested I implemented edge-to-edge following guidelines. It is disabled by default but You can enable going to options.
If You enable it system bars become transparent matching the view color.
This option will be available only for devices with sdk >= android oreo 8.1 as it has both system bars dark options, just to avoid visual problems.
In Android Q system bar icons color should be automatically selected.

Test apk:

https://drive.google.com/open?id=1imK75ncC5pBlHJkfs6EZyL0FW1_DSP08

**Comment by Jnss98b** [comment]
It finally worked! Thanks you so much! Is this coming to the stable release channel soon?
![Screenshot_20191130-134248](https://user-images.githubusercontent.com/24306400/69904690-6b45e480-1377-11ea-9e1f-563df00a59fa.jpg)

**Comment by enricocid** [comment]
Glad it worked :)
Yes, within the next week I'm going to publish a big update ;)

**Comment by Jnss98b** [comment]
Oh yeah I think the Now playing popup could use some tweak too. It looks like it's not edge to edge yet
![Screenshot_20191130-150454](https://user-images.githubusercontent.com/24306400/69905544-009aa600-1383-11ea-902b-e01c5e07721d.jpg)
![Screenshot_20191130-150503](https://user-images.githubusercontent.com/24306400/69905545-009aa600-1383-11ea-94f3-06be9a55ef85.jpg)

**Comment by enricocid** [comment]
Yeah I noticed. It is weird as I applied settings from guidelines

**Comment by enricocid** [comment]
try this:

https://drive.google.com/open?id=1J3tF5yw2hoWN6LMeyAFDmaEVUbOh3U8o

seems like You need to reapply edge-to-edge when You open a botton sheet dialog...

**Comment by Jnss98b** [comment]
Yep that fixed it. Thanks for the quick responses!
![Screenshot_20191130-162834](https://user-images.githubusercontent.com/24306400/69906238-7bb58980-138e-11ea-95e6-d7d011731109.jpg)

**Comment by enricocid** [comment]
Great! Thanks

**Comment by Jnss98b** [comment]
Unrelated but I noticed you actually desaturate the accent color in dark mode like mentioned in MD guidelines. That's a nice touch. This is like the first non-Google app that does that that I have ever seen.
