### ISSUE TITLE
Play Next

### ISSUE THREAD

**Issue by bliet** [enricocid/Music-Player-GO#87]
Nice Player. Two questions:
Is there a plan to support Playlists?
Is it posible to play a song/album after the current song (other music players have a option like "play next" or "add do current playlist")?

**Comment by enricocid** [comment]
This feature is already scheduled. It will be added on the new version of MPGO, which is in the process of full rewriting 😉
Anyway, there's already an issue for this request so I'm closing


https://github.com/enricocid/Music-Player-GO/issues/31
