### ISSUE TITLE
Indicator Fast Scroll: remove delay/animations between selection and scrolling

### ISSUE THREAD

**Issue by bliet** [enricocid/Music-Player-GO#88]
When I open the player and want to scroll to "Z" the animations need much time. Could be there a option that i can "jump" to Z (or anywhere else) without an animation?
[example.zip](https://github.com/enricocid/Music-Player-GO/files/3614286/example.zip)

**Comment by enricocid** [comment]
Perfect. Gonna add this to the new version of MPGO:

- I will add direct scrolling.
- I'll try to include two buttons to quick scroll to top/bottom

**Comment by enricocid** [comment]
Issue fixed

https://github.com/enricocid/Music-Player-GO/commit/3200e2dfeb14e93d46f177a9bb2ac61f67859354

The [new release](https://github.com/enricocid/Music-Player-GO/releases/tag/v3.6.6.2) is already available on GitHub and it will be online on Google Play within the next few hours ;)

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks
