### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [enricocid/Music-Player-GO#9]
Would you mind making the `.apk` available by other means than Playstore (for folks "outside" that walled garden)? I could then offer shipping it via [my repo](https://apt.izzysoft.de/fdroid/repo), so the F-Droid client can be used to install the app and keep it up-to-date. Of course you could also decide to go straight for the official F-Droid repo (for which mine often acts as stepping-stone).

**Comment by IzzySoft** [comment]
@enricocid you don't need to "manage a repo" – that part you can leave to me. All you had to do is providing the APK file. Multiple possibilities for that, ordered by preference:

* whenever you make a new release, tag it (e.g. `v1.2.3` for version 1.2.3) and attach the `.apk` file ***as `*.apk`*** to it. Easy to do once you know how, should't take more that 2 minutes per release (some minutes more if you also want to provide release information like what has changed, which of course is very appreciated but not mandatory as one also could check commits). A short howto can be found in the Github help article [Creating Releases](https://help.github.com/articles/creating-releases/).  
This is **by far** the best method.
* alternatively: just check in the `.apk` file in the repo as e.g. `app-release.apk` and keep it updated. Disadvantage: it will bloat the repo with time, and each one forking/cloning it will have to carry the full load.
* last resort fallback: have a **fixed** URL (like `https://example.com/goplayer.apk`) which always ships the latest version **AND** where the web server provides a Last-Modified field in the header.

I strongly recommend the first solution (which btw is what most Android app repos do). Especially the release schema (`v1.2.3`) would also prepare you for a future inclusion with the official F-Droid repo.

**Comment by enricocid** [comment]
Ok, just created a new release with apk attached
Thank You

**Comment by IzzySoft** [comment]
Thanks a lot! Find it [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.iven.musicplayergo) then. If you'd agree, I'd forward it to the maintainers of the official repo to pick it (that repo is more trusted than mine, and gives you more "publicity"). They might need a little support to get things started (or not even that) – and afterwards it would mostly be a "self-runner" as long as you tag your releases. That OK with you?

(PS: Sorry for the delay, but somehow the notification must have missed me)

**Comment by enricocid** [comment]
Ok!:)

**Comment by IzzySoft** [comment]
[Done](https://gitlab.com/fdroid/rfp/issues/582) then :innocent:

**Comment by enricocid** [comment]
Thank You! 😁

**Comment by IzzySoft** [comment]
Sensational! Guess we just set a new record: the RFP has already [been picked up](https://gitlab.com/fdroid/fdroiddata/merge_requests/3195). So you can expect your app being listed in the official repo within a few days, if everything goes right (i.e. no build issues pop up or the like).

Congrats!

**Comment by enricocid** [comment]
The app is online, closing the issue. Thank You guys, really appreciate your help 😁

**Comment by licaon-kter** [comment]
@enricocid Please keep a consistent tag scheme, `v3.6.9.1` was followed by `3.6.9.2` _(notice the missing `v`?)_, so F-Droid fails to build: https://f-droid.org/wiki/page/com.iven.musicplayergo/lastbuild_131

**Comment by enricocid** [comment]
Fixed, thanks 😁

**Comment by licaon-kter** [comment]
I've referenced a MR that fixed it for this version (only), now I'd have to reverse this...hopefully on time as a new cycle has started on the buildserver.

**Comment by enricocid** [comment]
@IzzySoft 
I just noticed that graphics are not getting updated?
Is there something wrong in my repo? :)

Thank You

**Comment by IzzySoft** [comment]
What do you mean? If I compare the screenshots [shown here](https://f-droid.org/packages/com.iven.musicplayergo/), they seem to be the ones in your Fastlane at HEAD. If you think there's something wrong, please give a few more details :wink:

**Comment by enricocid** [comment]
> What do you mean? If I compare the screenshots [shown here](https://f-droid.org/packages/com.iven.musicplayergo/), they seem to be the ones in your Fastlane at HEAD. If you think there's something wrong, please give a few more details 😉

Italian listing screenshots are not updated for some reason :D

I dropped resources from the it folder on the assumption that those in the en-US one were enough.

**Comment by IzzySoft** [comment]
> Italian listing screenshots are not updated for some reason :D

[there are none in your repo](https://github.com/enricocid/Music-Player-GO/tree/main/fastlane/metadata/android/it).

> I dropped resources from the it folder on the assumption that those in the en-US one were enough ...

Sorry, nope. You've hit a long-standing bug: once a screenshot is there, it's not removed anymore. You can only replace it. Check with the fdroidserver issue tracker for the bug – and no, I cannot help with that, sorry.

**Comment by enricocid** [comment]
> > Italian listing screenshots are not updated for some reason :D
> 
> [there are none in your repo](https://github.com/enricocid/Music-Player-GO/tree/main/fastlane/metadata/android/it).
> 
> > I dropped resources from the it folder on the assumption that those in the en-US one were enough ...
> 
> Sorry, nope. You've hit a long-standing bug: once a screenshot is there, it's not removed anymore. You can only replace it. Check with the fdroidserver issue tracker for the bug – and no, I cannot help with that, sorry.

Not a problem 👍🏻
Thank you 😁
