### ISSUE TITLE
Wrong sorting if lower case

### ISSUE THREAD

**Issue by bliet** [enricocid/Music-Player-GO#90]
If an artist name starts with lowercase letters, they will not be sorted correctly. They appear at the end of the list after Z.

I just changed some names for the demo. 
![Screenshot_20190920-180933](https://user-images.githubusercontent.com/3314090/65342068-388eab80-dbd2-11e9-8ad2-59dad7ca60b8.png)

**Comment by enricocid** [comment]
The issue was fixed and it will be available in the new version of [MPGO](https://github.com/enricocid/Music-Player-GO/tree/master-mpgo-ex) :) Thanks for reporting.
