### ISSUE TITLE
[Feature Request] Repeat Option

### ISSUE THREAD

**Issue by MrTeeXD** [enricocid/Music-Player-GO#92]
This is the cleanest Music Player i have ever seen. There is one thing missing, there does not seem to be a repeat mode that allows me to repeat the song once of forever. It would be great if there was an option like that.

**Comment by enricocid** [comment]
If you long click on skip prev button repeat 1x will be enabled (the icon becomes accented).
In the 4.0 version I'm preparing there will be also repeat infinite 😁

**Comment by MrTeeXD** [comment]
Oh, i did not know that. Thanks :smiley:
