### ISSUE TITLE
Precise volume control is not precise anymore

### ISSUE THREAD

**Issue by harisont** [enricocid/Music-Player-GO#93]
Hi again! 
After I made the pull request with the code for precise volume control I reinstalled the app from fdroid. I love the new user interface, but I just noticed that the volume is not precise anymore! It looks like it's 100 steps in the seekbar, but then it's actually the usual 20 that the android operating system provides (for me, this results in WAY TOO HIGH minimum volume). I've seen there's a commit about using audio manager, and that might be the problem.

**Comment by harisont** [comment]
Looking forward to it but no pressure at all, I still have my ugly version :)

**Comment by enricocid** [comment]
Hello,

I restored the original implementation, could You try and let me know if everything is ok now? :)

https://drive.google.com/open?id=1n__InrgYQC0Qi73x3kUL3OmvCP7LC-qG

Thanks

**Comment by harisont** [comment]
Perfetto!

**Comment by enricocid** [comment]
Thanks. Update has been pushed! :)
