### ISSUE TITLE
List of supported file types? 

### ISSUE THREAD

**Issue by guitaristtom** [enricocid/Music-Player-GO#94]
Would you be able to add a list of supported file types to the README.md file? 

It would be nice to know if it can play FLAC, OGG, and/or WAV files without needing to download and do my own testing.

**Comment by enricocid** [comment]
I'm using MediaPlayer API. For a list of supported formats you can refer to this page:

https://developer.android.com/guide/topics/media/media-formats.html#audio-codecs

**Comment by guitaristtom** [comment]
Would you be able to make a note of that in the readme? I had searched up "supported" and nothing came up.

I have actually started to use this media player, and it's really nice and simple so far.

**Comment by enricocid** [comment]
Ok

**Comment by guitaristtom** [comment]
Thank you. 

I didn't mean to sound entitled or mad at all, I was just trying to help you out with your documentation to make it easier for potential new users.

**Comment by enricocid** [comment]
No no, don't worry.
I'm abroad and I'm a bit busy/tired so I'm not using the PC. I will update the readme asap with list of supported files. :)

**Comment by guitaristtom** [comment]
Sounds good.

**Comment by enricocid** [comment]
List of supported audio files added.  :)
Closing.
