### ISSUE TITLE
Starts to play music allways when someone calls me

### ISSUE THREAD

**Issue by ecxod** [enricocid/Music-Player-GO#96]
The program itself is OK, but I had to uninstall it because it always started to play the last song I listened when I got a call. I am not sure if it also started when I called someone, but it always started when someone else called me. I have a personal wish, please do not remove the alpha status of this program until it has not been thoroughly tested. 

Please excuse my English, I forgot to specify the android version. 
I use a Android 6.0 Baseband Version X6069_LWG_M0_V0.0_S160806 2016/08/06 15:27
The Kernel-Version is 3.18.19 jenkins@80-12 #1
BUILD-Nummer : CUBOT_MAX_V04_20160812

**Comment by enricocid** [comment]
Thanks for reporting. Android version?

The same happens to me also on Android Nougat.

**Comment by enricocid** [comment]
Hello,
could You try this apk and let me know if the problem persists? Thanks

https://drive.google.com/open?id=1vhIgvMqlFjUHP8bvpihTH0vWF1FL8cWI

**Comment by enricocid** [comment]
https://drive.google.com/open?id=1hoxi8zNwe41SZIJoGaHfJjaARGIb7s9b
