### ISSUE TITLE
Stopped starting, cannot install from F-droid

### ISSUE THREAD

**Issue by TheSavageSam** [enricocid/Music-Player-GO#98]
I am using Android 9. F-droid says that file is not found.

**Comment by enricocid** [comment]
Is it crashing or you are not able to install from f-droid?

For the crash, I published an update 2 days ago, it will be available soon on f-droid.

For f-droid: I can actually install the app from f-droid...

**Comment by TheSavageSam** [comment]
The update solved the issues I had. Thank you!
